"""
WeChat OAuth service endpoints. Generated by Copilot
"""
from flask import Blueprint, request, jsonify, current_app
from flask_jwt_extended import jwt_required, get_jwt_identity
from ..extensions import limiter
from ..manager.wechat_manager import WeChatManager
from ..manager.user_manager import UserManager
from ..security import make_tokens, verify_password
from ..utils import error

wechat_bp = Blueprint("wechat", __name__)
wechat_manager = WeChatManager()
user_manager = UserManager()


@wechat_bp.route("/qr", methods=["GET"])
@limiter.limit(lambda: current_app.config.get("RATELIMIT_AUTH", "5 per minute"))
def get_qr_code():
    """
    Generate WeChat QR code parameters for login.
    Returns the parameters needed to construct the QR code URL.
    """
    ticket_data = wechat_manager.get_qr_ticket()
    
    if not ticket_data:
        return jsonify(error("500", "WeChat configuration not available")), 500
    
    # Construct the QR code URL
    qr_url = (
        f"{wechat_manager.WECHAT_OPEN_BASE}/connect/qrconnect"
        f"?appid={ticket_data['appid']}"
        f"&redirect_uri={ticket_data['redirect_uri']}"
        f"&response_type=code"
        f"&scope={ticket_data['scope']}"
        f"&state={ticket_data['state']}"
        f"#wechat_redirect"
    )
    
    return jsonify({
        "qr_url": qr_url,
        "appid": ticket_data['appid'],
        "state": ticket_data['state']
    }), 200


@wechat_bp.route("/callback", methods=["POST"])
@limiter.limit(lambda: current_app.config.get("RATELIMIT_AUTH", "5 per minute"))
def wechat_callback():
    """
    Handle WeChat OAuth callback.
    Exchange code for access token, get user info, and login/register user.
    """
    data = request.get_json(force=True) or {}
    code = data.get("code")
    
    if not code:
        return jsonify(error("400", "Authorization code required")), 400
    
    # Exchange code for access token
    token_data = wechat_manager.get_access_token(code)
    if not token_data:
        return jsonify(error("401", "Failed to get WeChat access token")), 401
    
    access_token = token_data.get("access_token")
    openid = token_data.get("openid")
    unionid = token_data.get("unionid")
    
    if not unionid:
        return jsonify(error("401", "Failed to get WeChat unionid")), 401
    
    # Get user info from WeChat
    user_info = wechat_manager.get_user_info(access_token, openid)
    if not user_info:
        return jsonify(error("401", "Failed to get WeChat user info")), 401
    
    nickname = user_info.get("nickname", "WeChat User")
    avatar_url = user_info.get("headimgurl")
    
    # Find or create user
    user = wechat_manager.find_user_by_unionid(unionid)
    if not user:
        # Create new user from WeChat
        user = wechat_manager.create_wechat_user(unionid, nickname, avatar_url)
    
    # Generate tokens
    tokens = make_tokens(identity=user.id, token_version=user.token_version)
    
    return jsonify({
        "access_token": tokens["access_token"],
        "expires_in": 60 * 30,
        "refresh_token": tokens["refresh_token"],
        "refresh_expires_in": 60 * 60 * 24 * 7,
        "token_type": "Bearer",
        "user": {
            "id": user.id,
            "username": user.username,
            "email": user.email if not user.is_wechat_user else None,
            "is_wechat_user": user.is_wechat_user,
            "avatar_url": user.avatar_url
        }
    }), 200


@wechat_bp.route("/bind", methods=["POST"])
@jwt_required()
@limiter.limit(lambda: current_app.config.get("RATELIMIT_AUTH", "5 per minute"))
def bind_wechat():
    """
    Bind WeChat account to existing email/password user.
    Requires the user to provide their email and password for verification.
    """
    identity = get_jwt_identity()
    current_user = user_manager.get_user(identity)
    
    if not current_user:
        return jsonify(error("401", "Invalid token")), 401
    
    data = request.get_json(force=True) or {}
    code = data.get("code")
    
    if not code:
        return jsonify(error("400", "WeChat authorization code required")), 400
    
    # Exchange code for access token
    token_data = wechat_manager.get_access_token(code)
    if not token_data:
        return jsonify(error("401", "Failed to get WeChat access token")), 401
    
    access_token = token_data.get("access_token")
    openid = token_data.get("openid")
    unionid = token_data.get("unionid")
    
    if not unionid:
        return jsonify(error("401", "Failed to get WeChat unionid")), 401
    
    # Get user info for avatar
    user_info = wechat_manager.get_user_info(access_token, openid)
    avatar_url = user_info.get("headimgurl") if user_info else None
    
    # Bind WeChat to current user
    try:
        user = wechat_manager.bind_wechat_to_user(current_user, unionid, avatar_url)
    except ValueError as e:
        if str(e) == "WECHAT_ALREADY_BOUND":
            return jsonify(error("409", "This WeChat account is already bound to another user")), 409
        raise
    
    return jsonify({
        "message": "WeChat account bound successfully",
        "user": {
            "id": user.id,
            "username": user.username,
            "email": user.email,
            "wechat_bound": user.wechat_unionid is not None,
            "avatar_url": user.avatar_url
        }
    }), 200
