"""
Import manager layer for health record batch import. Generated by Copilot
"""
import json
import pandas as pd
from datetime import datetime
from typing import List, Dict, Tuple, Optional, Any
from dateutil import parser as date_parser
from zoneinfo import ZoneInfo
from ..extensions import db
from ..models import HealthRecord, RecordSubject, Member, ImportLog
from ..manager.member_manager import MemberManager
from ..resilience.policy import db_breaker, with_retry

# Validation constants
BP_MIN = 30  # Minimum blood pressure (mmHg)
BP_MAX = 250  # Maximum blood pressure (mmHg)
HR_MIN = 30  # Minimum heart rate (bpm)
HR_MAX = 150  # Maximum heart rate (bpm)
NOTE_MAX_LENGTH = 500  # Maximum note length (characters)


class ImportManager:
    def __init__(self):
        self.member_mgr = MemberManager()
        # Beijing timezone for default
        self.default_tz = ZoneInfo("Asia/Shanghai")

    def parse_file(self, file_stream, file_extension: str) -> List[Dict[str, Any]]:
        """
        Parse Excel (.xlsx) or CSV (.csv) file into list of dicts.
        
        Args:
            file_stream: File stream object
            file_extension: File extension (.xlsx or .csv)
            
        Returns:
            List of dictionaries, each representing a row
            
        Raises:
            ValueError: If file format is invalid or parsing fails
        """
        try:
            if file_extension.lower() in ['.xlsx', '.xls']:
                # Read Excel file, only first sheet
                df = pd.read_excel(file_stream, sheet_name=0)
            elif file_extension.lower() == '.csv':
                # Read CSV with UTF-8 BOM support
                df = pd.read_csv(file_stream, encoding='utf-8-sig')
            else:
                raise ValueError(f"Unsupported file format: {file_extension}")
            
            # Skip empty rows
            df = df.dropna(how='all')
            
            # Convert to list of dicts
            records = df.to_dict('records')
            
            return records
        except Exception as e:
            raise ValueError(f"Failed to parse file: {str(e)}")

    def validate_row(self, row: Dict[str, Any], user_id: int, row_number: int) -> Tuple[bool, Optional[Dict], Optional[str]]:
        """
        Validate a single row of data.
        
        Args:
            row: Dictionary containing row data
            user_id: User ID for member lookup
            row_number: Row number for error reporting
            
        Returns:
            Tuple of (is_valid, cleaned_data, error_message)
        """
        cleaned = {}
        
        # Define expected column names (support both Chinese and English)
        member_name_cols = ['成员名称', 'Member Name', 'member_name', '姓名']
        timestamp_cols = ['测量时间', 'Timestamp', 'timestamp', '时间']
        systolic_cols = ['收缩压', 'Systolic', 'systolic', 'SBP']
        diastolic_cols = ['舒张压', 'Diastolic', 'diastolic', 'DBP']
        heart_rate_cols = ['心率', 'Heart Rate', 'heart_rate', 'HR']
        tags_cols = ['标签', 'Tags', 'tags', '标记']
        note_cols = ['备注', 'Note', 'note', '说明']
        
        def get_value(cols):
            """Get value from row using multiple possible column names"""
            for col in cols:
                if col in row and pd.notna(row[col]):
                    return row[col]
            return None
        
        # 1. Validate member name (required)
        member_name = get_value(member_name_cols)
        if not member_name:
            return False, None, "成员名称为必填项"
        
        # Normalize member name and match
        member_name_str = str(member_name).strip()
        if not member_name_str:
            return False, None, "成员名称不能为空"
        
        # Special handling for Self/自己/本人
        if member_name_str.lower() in ['self', '自己', '本人']:
            member = self.member_mgr.get_or_create_self_member(user_id)
        else:
            # Find member by name (case-insensitive)
            household = self.member_mgr.get_household(user_id)
            if not household:
                return False, None, "用户家庭不存在"
            
            member = Member.query.filter(
                Member.household_id == household.id,
                Member.status == 'active',
                db.func.lower(Member.full_name) == member_name_str.lower()
            ).first()
            
            if not member:
                return False, None, f"成员名称 '{member_name_str}' 不存在"
        
        cleaned['member_id'] = member.id
        cleaned['household_id'] = member.household_id
        
        # 2. Validate timestamp (required)
        timestamp_str = get_value(timestamp_cols)
        if not timestamp_str:
            return False, None, "测量时间为必填项"
        
        try:
            # Parse timestamp
            if isinstance(timestamp_str, datetime):
                dt = timestamp_str
            else:
                dt = date_parser.parse(str(timestamp_str))
            
            # Add default timezone if naive
            if dt.tzinfo is None:
                dt = dt.replace(tzinfo=self.default_tz)
            
            # Convert to UTC for storage
            dt_utc = dt.astimezone(ZoneInfo("UTC"))
            # Store as naive UTC (for MySQL compatibility)
            cleaned['timestamp'] = dt_utc.replace(tzinfo=None)
        except Exception:
            return False, None, "测量时间格式无效"
        
        # 3. Validate systolic (required)
        systolic = get_value(systolic_cols)
        if systolic is None or pd.isna(systolic):
            return False, None, "收缩压为必填项"
        
        try:
            systolic_val = int(float(systolic))
            if systolic_val < BP_MIN or systolic_val > BP_MAX:
                return False, None, f"收缩压必须在 {BP_MIN}-{BP_MAX} mmHg 范围内"
            cleaned['systolic'] = systolic_val
        except (ValueError, TypeError):
            return False, None, "收缩压必须是有效数字"
        
        # 4. Validate diastolic (required)
        diastolic = get_value(diastolic_cols)
        if diastolic is None or pd.isna(diastolic):
            return False, None, "舒张压为必填项"
        
        try:
            diastolic_val = int(float(diastolic))
            if diastolic_val < BP_MIN or diastolic_val > BP_MAX:
                return False, None, f"舒张压必须在 {BP_MIN}-{BP_MAX} mmHg 范围内"
            cleaned['diastolic'] = diastolic_val
        except (ValueError, TypeError):
            return False, None, "舒张压必须是有效数字"
        
        # Check systolic > diastolic
        if cleaned['systolic'] <= cleaned['diastolic']:
            return False, None, "收缩压必须大于舒张压"
        
        # 5. Validate heart rate (optional)
        heart_rate = get_value(heart_rate_cols)
        if heart_rate is not None and pd.notna(heart_rate):
            try:
                hr_val = int(float(heart_rate))
                if hr_val < HR_MIN or hr_val > HR_MAX:
                    return False, None, f"心率必须在 {HR_MIN}-{HR_MAX} bpm 范围内"
                cleaned['heart_rate'] = hr_val
            except (ValueError, TypeError):
                return False, None, "心率必须是有效数字"
        else:
            cleaned['heart_rate'] = None
        
        # 6. Parse tags (optional)
        tags_str = get_value(tags_cols)
        if tags_str and pd.notna(tags_str):
            # Split by semicolon and strip whitespace
            tags_list = [t.strip() for t in str(tags_str).split(';') if t.strip()]
            cleaned['tags'] = tags_list
        else:
            cleaned['tags'] = []
        
        # 7. Parse note (optional)
        note = get_value(note_cols)
        if note and pd.notna(note):
            note_str = str(note).strip()
            if len(note_str) > NOTE_MAX_LENGTH:
                return False, None, f"备注不能超过 {NOTE_MAX_LENGTH} 字符"
            cleaned['note'] = note_str
        else:
            cleaned['note'] = None
        
        return True, cleaned, None

    @db_breaker
    @with_retry()
    def batch_import(self, user_id: int, rows: List[Dict[str, Any]], skip_errors: bool = True) -> Dict[str, Any]:
        """
        Batch import health records.
        
        Args:
            user_id: User ID
            rows: List of row dictionaries
            skip_errors: If True, skip invalid rows and continue; if False, abort on first error
            
        Returns:
            Dictionary with import results:
            {
                "total": 100,
                "success": 95,
                "failed": 5,
                "errors": [
                    {"row": 10, "data": {...}, "reason": "..."},
                    ...
                ]
            }
        """
        total = len(rows)
        success_rows = []
        error_rows = []
        
        # Validate all rows first
        for idx, row in enumerate(rows, start=1):
            is_valid, cleaned_data, error_msg = self.validate_row(row, user_id, idx)
            if is_valid:
                success_rows.append((idx, cleaned_data))
            else:
                error_rows.append({
                    "row": idx,
                    "data": {k: (v if not pd.notna(v) else (v if isinstance(v, (str, int, float, bool)) else str(v))) for k, v in row.items()},
                    "reason": error_msg
                })
                if not skip_errors:
                    # Abort on first error
                    return {
                        "total": total,
                        "success": 0,
                        "failed": total,
                        "errors": error_rows
                    }
        
        # Batch insert successful rows using transaction
        if success_rows:
            try:
                for row_num, cleaned in success_rows:
                    # Create health record
                    record = HealthRecord(
                        user_id=user_id,
                        systolic=cleaned['systolic'],
                        diastolic=cleaned['diastolic'],
                        heart_rate=cleaned['heart_rate'],
                        timestamp=cleaned['timestamp'],
                        tags=json.dumps(cleaned['tags'], ensure_ascii=False),
                        note=cleaned['note']
                    )
                    db.session.add(record)
                    db.session.flush()  # Get record ID
                    
                    # Create record subject association
                    subject = RecordSubject(
                        record_id=record.id,
                        household_id=cleaned['household_id'],
                        member_id=cleaned['member_id'],
                        created_by_user_id=user_id
                    )
                    db.session.add(subject)
                
                db.session.commit()
            except Exception as e:
                db.session.rollback()
                # If batch insert fails, mark all as failed
                return {
                    "total": total,
                    "success": 0,
                    "failed": total,
                    "errors": [{
                        "row": 0,
                        "data": {},
                        "reason": f"Database insert failed: {str(e)}"
                    }]
                }
        
        return {
            "total": total,
            "success": len(success_rows),
            "failed": len(error_rows),
            "errors": error_rows
        }

    @db_breaker
    @with_retry()
    def save_import_log(self, user_id: int, filename: str, result: Dict[str, Any]) -> ImportLog:
        """
        Save import operation audit log.
        
        Args:
            user_id: User ID
            filename: Imported filename
            result: Import result dictionary
            
        Returns:
            ImportLog instance
        """
        # Determine status
        if result['failed'] == 0:
            status = 'success'
        elif result['success'] == 0:
            status = 'failed'
        else:
            status = 'partial'
        
        log = ImportLog(
            user_id=user_id,
            filename=filename,
            total_rows=result['total'],
            success_rows=result['success'],
            failed_rows=result['failed'],
            status=status,
            error_summary=json.dumps(result.get('errors', []), ensure_ascii=False)
        )
        
        db.session.add(log)
        db.session.commit()
        
        return log
