"""
Medical History Attachment manager layer. Generated by Copilot
"""
from __future__ import annotations

from pathlib import Path
from typing import List, Optional, Tuple
from uuid import uuid4

from flask import current_app
from werkzeug.datastructures import FileStorage
from werkzeug.utils import secure_filename

from ..extensions import db
from ..models import MedicalHistory, MedicalHistoryAttachment
from ..resilience.policy import db_breaker, with_retry


class MedicalHistoryAttachmentManager:
    @db_breaker
    def list(self, history_id: int, page: int, size: int) -> Tuple[int, List[MedicalHistoryAttachment]]:
        q = MedicalHistoryAttachment.query.filter_by(medical_history_id=history_id)
        total = q.count()
        items = (
            q.order_by(MedicalHistoryAttachment.created_at.desc())
            .offset((page - 1) * size)
            .limit(size)
            .all()
        )
        return total, items

    @db_breaker
    def get(self, attachment_id: int, history_id: int, household_id: int) -> Optional[MedicalHistoryAttachment]:
        return MedicalHistoryAttachment.query.filter_by(
            id=attachment_id,
            medical_history_id=history_id,
            household_id=household_id,
        ).first()

    @db_breaker
    @with_retry()
    def create(
        self,
        history: MedicalHistory,
        file_name: str,
        file_ext: str,
        mime_type: str,
        file_size: int,
        storage_key: str,
        created_by_user_id: int,
    ) -> MedicalHistoryAttachment:
        item = MedicalHistoryAttachment(
            household_id=history.household_id,
            member_id=history.member_id,
            medical_history_id=history.id,
            file_name=file_name,
            file_ext=file_ext,
            mime_type=mime_type,
            file_size=file_size,
            storage_provider="local",
            storage_key=storage_key,
            created_by_user_id=created_by_user_id,
        )
        db.session.add(item)
        db.session.commit()
        return item

    @db_breaker
    @with_retry()
    def delete(self, item: MedicalHistoryAttachment) -> None:
        db.session.delete(item)
        db.session.commit()

    def _base_dir(self) -> Path:
        configured = current_app.config.get("ATTACHMENT_LOCAL_BASE_PATH", "instance/uploads")
        base = Path(configured)
        if not base.is_absolute():
            base = Path(current_app.root_path).parent / base
        base.mkdir(parents=True, exist_ok=True)
        return base

    def build_storage_key(self, history: MedicalHistory, original_filename: str) -> str:
        safe = secure_filename(original_filename) or "file"
        return f"medical-history/{history.household_id}/{history.member_id}/{history.id}/{uuid4().hex}_{safe}"

    def save_file(self, file: FileStorage, storage_key: str) -> Path:
        full_path = self._base_dir() / Path(storage_key)
        full_path.parent.mkdir(parents=True, exist_ok=True)
        file.save(full_path)
        return full_path

    def get_full_path(self, storage_key: str) -> Path:
        return self._base_dir() / Path(storage_key)

    def remove_file(self, storage_key: str) -> None:
        full_path = self.get_full_path(storage_key)
        if full_path.exists():
            full_path.unlink()
