"""
WeChat mini-app integration manager. Generated by Copilot
"""
import secrets
import requests
from typing import Optional, Dict, Any
from flask import current_app
from ..extensions import db
from ..models import User
from ..security import hash_password


class WeChatManager:
    """Manager for WeChat mini-app API interactions"""

    def __init__(self):
        self.api_base_url = "https://api.weixin.qq.com"

    def code2session(self, js_code: str) -> Optional[Dict[str, Any]]:
        """
        Exchange js_code for session_key and openid via WeChat API.
        
        Args:
            js_code: Temporary login code from wx.login()
            
        Returns:
            Dict with openid, session_key, unionid (if available)
            None if request fails
        """
        app_id = current_app.config.get("WECHAT_APP_ID")
        app_secret = current_app.config.get("WECHAT_APP_SECRET")
        
        if not app_id or not app_secret:
            raise ValueError("WeChat AppID and AppSecret not configured")
        
        url = f"{self.api_base_url}/sns/jscode2session"
        params = {
            "appid": app_id,
            "secret": app_secret,
            "js_code": js_code,
            "grant_type": "authorization_code"
        }
        
        try:
            response = requests.get(url, params=params, timeout=10)
            response.raise_for_status()
            data = response.json()
            
            # Check for WeChat API errors
            if "errcode" in data and data["errcode"] != 0:
                return None
                
            return data
        except (requests.RequestException, requests.Timeout, ValueError) as e:
            # Log error for debugging (in production, use proper logging)
            return None

    def get_or_create_user_by_openid(self, openid: str, session_key: str, 
                                     unionid: Optional[str] = None,
                                     user_info: Optional[Dict[str, Any]] = None) -> User:
        """
        Get existing user by openid or create new WeChat user.
        
        Args:
            openid: WeChat openid
            session_key: WeChat session key
            unionid: WeChat unionid (optional)
            user_info: Additional user info from mini-app (optional)
            
        Returns:
            User object
        """
        # Try to find existing user by openid
        user = User.query.filter_by(wechat_openid=openid).first()
        
        if user:
            # Update session key
            user.wechat_session_key = session_key
            if unionid:
                user.wechat_unionid = unionid
            db.session.commit()
            return user
        
        # Try to find by unionid if available
        if unionid:
            user = User.query.filter_by(wechat_unionid=unionid).first()
            if user:
                # Bind openid to existing unionid user
                user.wechat_openid = openid
                user.wechat_session_key = session_key
                db.session.commit()
                return user
        
        # Create new user for WeChat
        username = user_info.get("nickName", f"wx_{openid[:8]}") if user_info else f"wx_{openid[:8]}"
        # Use openid as temporary email (will be updated when user binds email)
        email = f"wechat_{openid}@temp.local"
        # Generate a secure random password that user won't know (they use WeChat login)
        temp_password = secrets.token_urlsafe(32)
        
        user = User(
            username=username,
            email=email,
            password_hash=hash_password(temp_password),
            wechat_openid=openid,
            wechat_session_key=session_key,
            wechat_unionid=unionid,
            token_version=0
        )
        
        db.session.add(user)
        db.session.commit()
        return user

    def bind_wechat_to_user(self, user_id: int, openid: str, 
                           session_key: str, unionid: Optional[str] = None) -> bool:
        """
        Bind WeChat account to existing user.
        
        Args:
            user_id: Existing user ID
            openid: WeChat openid
            session_key: WeChat session key
            unionid: WeChat unionid (optional)
            
        Returns:
            True if successful, False otherwise
        """
        user = User.query.get(user_id)
        if not user:
            return False
        
        # Check if openid is already bound to another user
        existing = User.query.filter(
            User.wechat_openid == openid,
            User.id != user_id
        ).first()
        
        if existing:
            return False
        
        user.wechat_openid = openid
        user.wechat_session_key = session_key
        if unionid:
            user.wechat_unionid = unionid
        
        db.session.commit()
        return True

    def unbind_wechat_from_user(self, user_id: int) -> bool:
        """
        Unbind WeChat account from user.
        
        Args:
            user_id: User ID
            
        Returns:
            True if successful, False otherwise
        """
        user = User.query.get(user_id)
        if not user:
            return False
        
        user.wechat_openid = None
        user.wechat_session_key = None
        user.wechat_unionid = None
        
        db.session.commit()
        return True
