// Generated by Zhuang
// Custom webpack config to fix React Scripts 5.0.1 dev server issues

const path = require('path');

module.exports = {
  devServer: {
    host: 'localhost',
    port: 3000,
    allowedHosts: ['localhost', '127.0.0.1'],
    historyApiFallback: true,
    static: {
      directory: path.join(__dirname, 'public'),
    },
    client: {
      webSocketURL: {
        hostname: 'localhost',
        pathname: '/ws',
        port: 3000,
        protocol: 'ws'
      }
    },
    headers: {
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, PATCH, OPTIONS',
      'Access-Control-Allow-Headers': 'X-Requested-With, content-type, Authorization'
    }
  }
};
