/**
 * E2E Tests for Chart Improvements - Issues #50 and #51
 * Generated by Copilot
 * 
 * Tests unified Y-axis, color scheme, and abnormal BP highlighting
 */

const { test, expect } = require('@playwright/test');

// Helper function for unique test users
function generateTestUser() {
  const timestamp = Date.now();
  return {
    username: `e2e_chart_user_${timestamp}`,
    email: `chart.test.${timestamp}@example.com`,
    password: 'TestPassword123!'
  };
}

// Helper function for user registration
async function registerUser(page, user) {
  await page.goto('/register');
  await page.fill('[data-testid="register-username"]', user.username);
  await page.fill('[data-testid="register-email"]', user.email);
  await page.fill('[data-testid="register-password"]', user.password);
  await page.fill('[data-testid="register-confirm"]', user.password);
  await page.fill('[data-testid="register-age"]', '30');
  await page.selectOption('[data-testid="register-gender"]', 'M');
  await page.fill('[data-testid="register-height"]', '175');
  await page.fill('[data-testid="register-weight"]', '70');
  await page.click('[data-testid="register-submit"]');
  await expect(page.locator('.ant-message-success')).toBeVisible({ timeout: 5000 });
}

// Helper function for user login
async function loginUser(page, user) {
  await page.goto('/login');
  await page.fill('[data-testid="login-email"]', user.email);
  await page.fill('[data-testid="login-password"]', user.password);
  await page.click('[data-testid="login-submit"]');
  await expect(page.locator('h2:has-text("健康仪表板")')).toBeVisible({ timeout: 10000 });
}

// Helper function to create health records via API
async function createHealthRecords(page) {
  // Create normal BP record (110/70)
  await page.goto('/health-records');
  await page.click('button:has-text("添加记录")');
  await page.fill('input[placeholder="收缩压"]', '110');
  await page.fill('input[placeholder="舒张压"]', '70');
  await page.fill('input[placeholder="心率"]', '72');
  await page.fill('textarea[data-testid="notes"]', 'Normal BP test record');
  const modal1 = page.locator('.ant-modal');
  await modal1.locator('button[type="submit"]').first().click();
  await expect(page.locator('.ant-message-success')).toBeVisible({ timeout: 5000 });
  
  // Create high systolic BP record (125/75) - abnormal
  await page.click('button:has-text("添加记录")');
  await page.fill('input[placeholder="收缩压"]', '125');
  await page.fill('input[placeholder="舒张压"]', '75');
  await page.fill('input[placeholder="心率"]', '78');
  await page.fill('textarea[data-testid="notes"]', 'High systolic BP test record');
  const modal2 = page.locator('.ant-modal');
  await modal2.locator('button[type="submit"]').first().click();
  await expect(page.locator('.ant-message-success')).toBeVisible({ timeout: 5000 });
  
  // Create high diastolic BP record (115/85) - abnormal
  await page.click('button:has-text("添加记录")');
  await page.fill('input[placeholder="收缩压"]', '115');
  await page.fill('input[placeholder="舒张压"]', '85');
  await page.fill('input[placeholder="心率"]', '70');
  await page.fill('textarea[data-testid="notes"]', 'High diastolic BP test record');
  const modal3 = page.locator('.ant-modal');
  await modal3.locator('button[type="submit"]').first().click();
  await expect(page.locator('.ant-message-success')).toBeVisible({ timeout: 5000 });
}

test.describe('Chart Improvements - Issues #50 and #51', () => {
  
  test('should display unified Y-axis and proper color scheme', async ({ page }) => {
    const user = generateTestUser();
    await registerUser(page, user);
    await loginUser(page, user);
    
    // Create test health records
    await createHealthRecords(page);
    
    // Navigate to dashboard
    await page.goto('/dashboard');
    await expect(page.locator('h2:has-text("健康仪表板")')).toBeVisible();
    
    // Wait for chart to load
    await page.waitForTimeout(2000);
    
    // Check that chart container exists and has data
    const chartContainer = page.locator('.health-chart');
    await expect(chartContainer).toBeVisible({ timeout: 10000 });
    
    // Verify download button is visible (indicates chart has data)
    await expect(page.locator('button:has-text("下载图表")')).toBeVisible();
    
    // Check statistics reflect the test data
    await expect(page.locator('text=总记录数')).toBeVisible();
    await expect(page.locator('text=本周记录')).toBeVisible();
    
    console.log('✅ Chart with unified Y-axis and color scheme is displayed');
  });
  
  test('should show correct statistics for abnormal BP values', async ({ page }) => {
    const user = generateTestUser();
    await registerUser(page, user);
    await loginUser(page, user);
    
    // Create test records with known values
    await createHealthRecords(page);
    
    // Navigate to dashboard
    await page.goto('/dashboard');
    await expect(page.locator('h2:has-text("健康仪表板")')).toBeVisible();
    
    // Wait for data to load
    await page.waitForTimeout(3000);
    
    // Verify statistics show the test data
    // We created 3 records, so total should be 3
    const totalRecords = page.locator('.ant-statistic-content').filter({ hasText: '3' }).first();
    await expect(totalRecords).toBeVisible({ timeout: 5000 });
    
    // Average calculations: (110+125+115)/3 = 116.67 ≈ 117
    await expect(page.locator('text=平均收缩压')).toBeVisible();
    // Average diastolic: (70+75+85)/3 = 76.67 ≈ 77  
    await expect(page.locator('text=平均舒张压')).toBeVisible();
    
    console.log('✅ Statistics correctly reflect abnormal BP test data');
  });
  
  test('should handle timezone consistency', async ({ page }) => {
    const user = generateTestUser();
    await registerUser(page, user);
    await loginUser(page, user);
    
    // Create a record and verify timestamp consistency
    await page.goto('/health-records');
    await page.click('button:has-text("添加记录")');
    await page.fill('input[placeholder="收缩压"]', '120');
    await page.fill('input[placeholder="舒张压"]', '80');
    await page.fill('input[placeholder="心率"]', '72');
    await page.fill('textarea[data-testid="notes"]', 'Timezone consistency test');
    
    const modal = page.locator('.ant-modal');
    await modal.locator('button[type="submit"]').first().click();
    await expect(page.locator('.ant-message-success')).toBeVisible({ timeout: 5000 });
    
    // Verify the record appears in the table with proper timestamp
    await expect(page.locator('text=Timezone consistency test')).toBeVisible({ timeout: 5000 });
    
    // Navigate to dashboard and verify data consistency
    await page.goto('/dashboard');
    await expect(page.locator('h2:has-text("健康仪表板")')).toBeVisible();
    
    // Should show at least 1 record
    const recordCount = page.locator('.ant-statistic-content').first();
    await expect(recordCount).toBeVisible();
    
    console.log('✅ Timezone consistency maintained across record creation and display');
  });
  
  test('should display download button when chart has data', async ({ page }) => {
    const user = generateTestUser();
    await registerUser(page, user);
    await loginUser(page, user);
    
    // Initially, dashboard might show "暂无数据"
    await page.goto('/dashboard');
    
    // Create at least one record
    await page.goto('/health-records');
    await page.click('button:has-text("添加记录")');
    await page.fill('input[placeholder="收缩压"]', '130');
    await page.fill('input[placeholder="舒张压"]', '85');
    await page.fill('input[placeholder="心率"]', '75');
    await page.fill('textarea[data-testid="notes"]', 'Test record for chart display');
    
    const modal = page.locator('.ant-modal');
    await modal.locator('button[type="submit"]').first().click();
    await expect(page.locator('.ant-message-success')).toBeVisible({ timeout: 5000 });
    
    // Return to dashboard
    await page.goto('/dashboard');
    await expect(page.locator('h2:has-text("健康仪表板")')).toBeVisible();
    
    // Wait for chart to load and verify download button appears
    await page.waitForTimeout(3000);
    await expect(page.locator('button:has-text("下载图表")')).toBeVisible({ timeout: 10000 });
    
    console.log('✅ Chart download button appears when data is present');
  });
});