/**
 * E2E Test: Threshold Governance - Draft → Preview → Publish flow
 * Generated by Copilot
 */
const { test, expect } = require('@playwright/test');

// Configuration
const BASE_URL = process.env.BASE_URL || 'http://localhost:3000';
const API_BASE = process.env.API_BASE || 'http://localhost:5000';

test.describe('Threshold Governance Flow', () => {
  let superAdminToken;
  let draftId;

  test.beforeAll(async ({ request }) => {
    // Create super admin user and login
    const registerResponse = await request.post(`${API_BASE}/api/v1/auth/register`, {
      data: {
        username: 'superadmin_e2e',
        email: 'superadmin_e2e@example.com',
        password: 'SuperAdmin123!',
        age: 30
      }
    });

    // Manually promote to SUPER_ADMIN via database would be needed in real scenario
    // For test purposes, assume we have a super admin account or use admin API

    const loginResponse = await request.post(`${API_BASE}/api/v1/auth/login`, {
      data: {
        email: 'superadmin_e2e@example.com',
        password: 'SuperAdmin123!'
      }
    });

    const loginData = await loginResponse.json();
    superAdminToken = loginData.access_token;
  });

  test('should create draft threshold profile', async ({ request }) => {
    const response = await request.post(`${API_BASE}/api/v1/admin/thresholds/draft`, {
      headers: {
        'Authorization': `Bearer ${superAdminToken}`
      },
      data: {
        systolic_healthy: [90, 120],
        systolic_borderline: [120, 140],
        diastolic_healthy: [60, 80],
        diastolic_borderline: [80, 90],
        systolic_min: 90,
        systolic_max: 140,
        diastolic_min: 60,
        diastolic_max: 90
      }
    });

    expect(response.status()).toBe(201);
    const data = await response.json();
    expect(data).toHaveProperty('id');
    expect(data.status).toBe('draft');
    draftId = data.id;
  });

  test('should preview draft effects on sample records', async ({ request }) => {
    // First create some health records
    for (let i = 0; i < 5; i++) {
      await request.post(`${API_BASE}/api/v1/health`, {
        headers: {
          'Authorization': `Bearer ${superAdminToken}`
        },
        data: {
          systolic: 100 + i * 10,
          diastolic: 70 + i * 5,
          heart_rate: 70,
          timestamp: new Date().toISOString(),
          tags: ['测试'],
          note: `E2E测试记录 ${i}`
        }
      });
    }

    // Preview draft
    const response = await request.get(
      `${API_BASE}/api/v1/thresholds/preview?draft_id=${draftId}&sample=5`,
      {
        headers: {
          'Authorization': `Bearer ${superAdminToken}`
        }
      }
    );

    expect(response.status()).toBe(200);
    const data = await response.json();
    expect(data).toHaveProperty('preview');
    expect(data.preview.length).toBeGreaterThan(0);
    
    // Verify threshold_status is computed
    data.preview.forEach(record => {
      expect(record).toHaveProperty('threshold_status');
      expect(['healthy', 'borderline', 'out_of_range']).toContain(record.threshold_status);
    });
  });

  test('should publish draft as active profile', async ({ request }) => {
    const response = await request.post(`${API_BASE}/api/v1/admin/thresholds/publish`, {
      headers: {
        'Authorization': `Bearer ${superAdminToken}`
      },
      data: {
        draft_id: draftId
      }
    });

    expect(response.status()).toBe(200);
    const data = await response.json();
    expect(data).toHaveProperty('version');
    expect(data).toHaveProperty('published_at');
    expect(data.version).toBeGreaterThan(0);
  });

  test('should retrieve active profile', async ({ request }) => {
    const response = await request.get(`${API_BASE}/api/v1/thresholds/active`, {
      headers: {
        'Authorization': `Bearer ${superAdminToken}`
      }
    });

    expect(response.status()).toBe(200);
    const data = await response.json();
    expect(data).toHaveProperty('profile');
    expect(data).toHaveProperty('version');
    expect(data.profile).toHaveProperty('systolic_healthy');
    expect(data.meta.stale).toBe(false);
  });

  test('should record audit log for publish action', async ({ request }) => {
    const response = await request.get(`${API_BASE}/api/v1/admin/thresholds/audit`, {
      headers: {
        'Authorization': `Bearer ${superAdminToken}`
      }
    });

    expect(response.status()).toBe(200);
    const data = await response.json();
    expect(data).toHaveProperty('logs');
    expect(data.logs.length).toBeGreaterThan(0);

    // Find publish action
    const publishLog = data.logs.find(log => log.action === 'publish');
    expect(publishLog).toBeDefined();
    expect(publishLog).toHaveProperty('actor_id');
    expect(publishLog).toHaveProperty('version');
  });

  test('should export audit logs as CSV', async ({ request }) => {
    const response = await request.get(`${API_BASE}/api/v1/admin/thresholds/audit/export`, {
      headers: {
        'Authorization': `Bearer ${superAdminToken}`
      }
    });

    expect(response.status()).toBe(200);
    expect(response.headers()['content-type']).toContain('text/csv');
    
    const csvData = await response.text();
    expect(csvData).toContain('id,action,actor_id');
  });

  test('should create health records without backend threshold fields', async ({ request }) => {
    // Create a new health record - backend no longer stores threshold status
    const response = await request.post(`${API_BASE}/api/v1/health`, {
      headers: {
        'Authorization': `Bearer ${superAdminToken}`
      },
      data: {
        systolic: 110,
        diastolic: 75,
        heart_rate: 72,
        timestamp: new Date().toISOString(),
        tags: ['自动标注测试'],
        note: '测试前端动态计算阈值状态'
      }
    });

    expect(response.status()).toBe(201);
    const data = await response.json();
    // Backend should NOT return threshold fields anymore
    expect(data).not.toHaveProperty('threshold_status');
    expect(data).not.toHaveProperty('threshold_version');
    // Frontend will compute these dynamically using active threshold config
  });
});

test.describe('Threshold Governance UI Flow', () => {
  let page;

  test.beforeEach(async ({ browser }) => {
    page = await browser.newPage();
    
    // Login as super admin
    await page.goto(`${BASE_URL}/login`);
    await page.fill('input[type="email"]', 'superadmin_e2e@example.com');
    await page.fill('input[type="password"]', 'SuperAdmin123!');
    await page.click('button[type="submit"]');
    
    // Wait for redirect after login
    await page.waitForURL(`${BASE_URL}/dashboard`, { timeout: 5000 });
  });

  test.afterEach(async () => {
    await page.close();
  });

  test('should navigate to threshold management page', async () => {
    // Navigate to threshold management (adjust selector based on actual UI)
    await page.goto(`${BASE_URL}/admin/thresholds`);
    
    // Verify page loaded
    await expect(page.locator('h1')).toContainText('阈值');
  });

  test('should create draft via UI form', async () => {
    await page.goto(`${BASE_URL}/admin/thresholds`);
    
    // Fill form
    await page.fill('input[name="systolic_healthy_min"]', '90');
    await page.fill('input[name="systolic_healthy_max"]', '120');
    await page.fill('input[name="diastolic_healthy_min"]', '60');
    await page.fill('input[name="diastolic_healthy_max"]', '80');
    
    // Submit
    await page.click('button:has-text("保存草稿")');
    
    // Verify success message
    await expect(page.locator('.ant-message-success')).toBeVisible({ timeout: 3000 });
  });

  test('should display preview table', async () => {
    await page.goto(`${BASE_URL}/admin/thresholds`);
    
    // Switch to preview tab
    await page.click('div[role="tab"]:has-text("预览")');
    
    // Wait for table to load
    await page.waitForSelector('table', { timeout: 5000 });
    
    // Verify table has data
    const rowCount = await page.locator('table tbody tr').count();
    expect(rowCount).toBeGreaterThan(0);
  });
});
