/**
 * Health Chart Component using ECharts
 * Generated by Zhuang
 */
import React, { useEffect, useState, useCallback } from 'react';
import ReactEChartsCore from 'echarts-for-react/lib/core';
import * as echarts from 'echarts/core';
import { LineChart } from 'echarts/charts';
import {
  GridComponent,
  TooltipComponent,
  LegendComponent,
  DataZoomComponent,
  TitleComponent,
} from 'echarts/components';
import { CanvasRenderer } from 'echarts/renderers';
import { Empty, Select, Space, Button } from 'antd';
import { DownloadOutlined } from '@ant-design/icons';
import dayjs from 'dayjs';
import { useTranslation } from 'react-i18next';

const { Option } = Select;

// Register ECharts components
echarts.use([
  LineChart,
  GridComponent,
  TooltipComponent,
  LegendComponent,
  DataZoomComponent,
  TitleComponent,
  CanvasRenderer,
]);

const HealthChart = ({ records = [] }) => {
  const { t } = useTranslation();
  const [timeRange, setTimeRange] = useState('week'); // week, month, all
  const [filteredRecords, setFilteredRecords] = useState([]);

  const filterRecordsByTimeRange = useCallback(() => {
    if (!records.length) {
      setFilteredRecords([]);
      return;
    }

    let filtered = [...records];
    const now = dayjs();

    switch (timeRange) {
      case 'week':
        filtered = records.filter(record => 
          dayjs(record.timestamp).isAfter(now.subtract(7, 'day'))
        );
        break;
      case 'month':
        filtered = records.filter(record => 
          dayjs(record.timestamp).isAfter(now.subtract(30, 'day'))
        );
        break;
      default:
        // 'all' - use all records
        break;
    }

    // Sort by timestamp
    filtered.sort((a, b) => new Date(a.timestamp) - new Date(b.timestamp));
    setFilteredRecords(filtered);
  }, [records, timeRange]);

  useEffect(() => {
    filterRecordsByTimeRange();
  }, [filterRecordsByTimeRange]);

  const downloadChart = () => {
    const chartInstance = document.querySelector('.health-chart canvas');
    if (chartInstance) {
      const link = document.createElement('a');
      link.download = `health-chart-${timeRange}-${dayjs().format('YYYY-MM-DD')}.png`;
      link.href = chartInstance.toDataURL();
      link.click();
    }
  };

  if (!filteredRecords.length) {
    return (
      <div>
        <Space style={{ marginBottom: 16 }}>
          <Select value={timeRange} onChange={setTimeRange} style={{ width: 120 }}>
      <Option value="week">{t('chart.range.week')}</Option>
      <Option value="month">{t('chart.range.month')}</Option>
      <Option value="all">{t('chart.range.all')}</Option>
          </Select>
        </Space>
    <Empty description={t('chart.noData')} />
      </div>
    );
  }

  // Prepare data for ECharts
  const timeAxis = filteredRecords.map(record => 
    dayjs(record.timestamp).format('MM-DD HH:mm')
  );
  
  // Backend fields are `systolic` and `diastolic`; coerce to numbers, use nulls for missing values
  const toNumOrNull = (v) => {
    const n = Number(v);
    return Number.isFinite(n) ? n : null;
  };
  const systolicData = filteredRecords.map(record => toNumOrNull(record.systolic));
  const diastolicData = filteredRecords.map(record => toNumOrNull(record.diastolic));
  const heartRateData = filteredRecords.map(record => toNumOrNull(record.heart_rate));

  // Generated by Copilot: Detect abnormal blood pressure values for highlighting
  // Normal range: systolic < 120 AND diastolic < 80
  const isAbnormalBP = (systolic, diastolic) => {
    if (systolic === null || diastolic === null) return false;
    return systolic >= 120 || diastolic >= 80;
  };

  // Generate color arrays for data points based on normal/abnormal values
  const systolicColors = filteredRecords.map((record, index) => {
    const systolic = systolicData[index];
    const diastolic = diastolicData[index];
    return isAbnormalBP(systolic, diastolic) ? '#ff4d4f' : '#1890ff'; // Red for abnormal, blue for normal
  });

  const diastolicColors = filteredRecords.map((record, index) => {
    const systolic = systolicData[index];
    const diastolic = diastolicData[index];
    return isAbnormalBP(systolic, diastolic) ? '#ff4d4f' : '#52c41a'; // Red for abnormal, green for normal
  });

  const option = {
    title: {
  text: t('dashboard.chartTitle'),
      left: 'center',
    },
  tooltip: {
      trigger: 'axis',
      axisPointer: {
        type: 'cross',
      },
      formatter: function (params) {
        let result = `${params[0].axisValue}<br/>`;
        params.forEach(param => {
          if (param.value !== null) {
      const unit = param.seriesName === t('chart.series.hr') ? ' bpm' : ' mmHg';
      result += `${param.seriesName}: ${param.value}${unit}<br/>`;
          }
        });
        return result;
      },
    },
    legend: {
      data: [t('chart.series.systolic'), t('chart.series.diastolic'), t('chart.series.hr')],
      top: 30,
    },
    grid: {
      left: '3%',
      right: '4%',
      bottom: '10%',
      top: '15%',
      containLabel: true,
    },
    xAxis: {
      type: 'category',
      boundaryGap: false,
      data: timeAxis,
      axisLabel: {
        rotate: 45,
      },
    },
    yAxis: {
      type: 'value',
      name: t('chart.yaxis.unified'),
      position: 'left',
      axisLabel: {
        formatter: '{value}',
      },
      min: 40,
      max: 200,
    },
    series: [
      {
        name: t('chart.series.systolic'),
        type: 'line',
        data: systolicData.map((value, index) => ({
          value,
          itemStyle: { color: systolicColors[index] }
        })),
        lineStyle: {
          color: '#1890ff', // Blue line for systolic pressure
        },
        connectNulls: false,
        symbol: 'circle',
        symbolSize: 6,
        emphasis: {
          itemStyle: {
            borderWidth: 2,
          },
        },
      },
      {
        name: t('chart.series.diastolic'),
        type: 'line',
        data: diastolicData.map((value, index) => ({
          value,
          itemStyle: { color: diastolicColors[index] }
        })),
        lineStyle: {
          color: '#52c41a', // Green line for diastolic pressure
        },
        connectNulls: false,
        symbol: 'circle',
        symbolSize: 6,
        emphasis: {
          itemStyle: {
            borderWidth: 2,
          },
        },
      },
      {
        name: t('chart.series.hr'),
        type: 'line',
        data: heartRateData,
        itemStyle: {
          color: '#722ed1', // Purple for heart rate
        },
        lineStyle: {
          color: '#722ed1',
        },
        connectNulls: false,
        symbol: 'triangle',
        symbolSize: 6,
        emphasis: {
          itemStyle: {
            borderColor: '#722ed1',
            borderWidth: 2,
          },
        },
      },
    ],
    dataZoom: [
      {
        type: 'inside',
        start: 0,
        end: 100,
      },
      {
        start: 0,
        end: 100,
      },
    ],
  };

  return (
    <div>
      <Space style={{ marginBottom: 16, justifyContent: 'space-between', width: '100%' }}>
        <Select value={timeRange} onChange={setTimeRange} style={{ width: 120 }}>
          <Option value="week">{t('chart.range.week')}</Option>
          <Option value="month">{t('chart.range.month')}</Option>
          <Option value="all">{t('chart.range.all')}</Option>
        </Select>
        <Button 
          icon={<DownloadOutlined />} 
          onClick={downloadChart}
          type="default"
        >
          {t('chart.download')}
        </Button>
      </Space>
      
      <ReactEChartsCore
        echarts={echarts}
        option={option}
        style={{ height: '400px', width: '100%' }}
        className="health-chart"
      />
    </div>
  );
};

export default HealthChart;
