/**
 * Tag Selector Component
 * Generated by Zhuang
 */
import React from 'react';
import { Select, Tag, Tooltip } from 'antd';

const { Option } = Select;

const TagSelector = ({ value = [], onChange, placeholder = "选择或添加标签", options = [], ...rest }) => {

  // Predefined common tags
  const commonTags = [
    '晨起',
    '睡前',
    '运动前',
    '运动后',
    '餐前',
    '餐后',
    '服药前',
    '服药后',
    '工作时',
    '休息时',
    '紧张时',
    '放松时',
    '头痛',
    '头晕',
    '胸闷',
    '心悸',
  '疲劳',
  ];

  const handleChange = (newValue) => onChange?.(newValue);

  return (
    <div className="tag-selector">
      <Select
        mode="tags" // Generated by Zhuang: allow free input by typing and Enter
        style={{ width: '100%' }}
        placeholder={placeholder}
        value={value}
        onChange={handleChange}
        allowClear
        showSearch
        optionLabelProp="label"
        {...rest}
      >
        {Array.from(new Set([...
          commonTags,
          ...(options || []),
          ...(value || []),
        ])).map(tag => (
          <Option key={tag} value={tag} label={tag} title={tag}>
            <Tooltip title={tag} placement="right">
              <Tag color="blue" style={{ maxWidth: 240, overflow: 'hidden', textOverflow: 'ellipsis' }}>{tag}</Tag>
            </Tooltip>
          </Option>
        ))}
      </Select>
    </div>
  );
};

export default TagSelector;
