/**
 * Time Discrepancy Warning Component
 * Generated by Copilot
 */
import React, { useState, useEffect, useCallback } from 'react';
import { Alert, Button, Typography, Space, Divider } from 'antd';
import { ClockCircleOutlined, SyncOutlined, CloseOutlined } from '@ant-design/icons';
import { checkTimeDiscrepancy, formatTimeDiscrepancy, shouldRecheckTimeSync } from '../utils/timeSync';

const { Text } = Typography;

const TimeDiscrepancyWarning = () => {
  const [discrepancyData, setDiscrepancyData] = useState(null);
  const [loading, setLoading] = useState(false);
  const [dismissed, setDismissed] = useState(false);

  const checkTime = useCallback(async () => {
    setLoading(true);
    try {
      const data = await checkTimeDiscrepancy();
      setDiscrepancyData(data);
    } catch (error) {
      console.error('Failed to check time discrepancy:', error);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    // Only check if we should recheck or have no data
    if (shouldRecheckTimeSync() || !discrepancyData) {
      checkTime();
    }
  }, [checkTime, discrepancyData]);

  const handleDismiss = () => {
    setDismissed(true);
  };

  const handleRecheck = () => {
    setDismissed(false);
    checkTime();
  };

  // Don't show if dismissed or no discrepancy
  if (dismissed || !discrepancyData || !discrepancyData.hasDiscrepancy) {
    return null;
  }

  return (
    <Alert
      message="Time Synchronization Warning"
      description={
        <Space direction="vertical" style={{ width: '100%' }}>
          <Text>
            <ClockCircleOutlined style={{ marginRight: 8 }} />
            Your system time appears to be out of sync with the server by{' '}
            <Text strong>{formatTimeDiscrepancy(discrepancyData.discrepancy)}</Text>.
          </Text>
          <Text type="secondary">
            This may cause authentication issues. Please check your system time settings.
          </Text>
          <Divider style={{ margin: '8px 0' }} />
          <Space size="small">
            <Text type="secondary" style={{ fontSize: '12px' }}>
              Server time: {discrepancyData.serverTime?.toLocaleString()}
            </Text>
            <Text type="secondary" style={{ fontSize: '12px' }}>
              |
            </Text>
            <Text type="secondary" style={{ fontSize: '12px' }}>
              Your time: {discrepancyData.clientTime?.toLocaleString()}
            </Text>
          </Space>
          <Space>
            <Button 
              size="small" 
              icon={<SyncOutlined />} 
              onClick={handleRecheck}
              loading={loading}
            >
              Recheck
            </Button>
            <Button 
              size="small" 
              icon={<CloseOutlined />} 
              onClick={handleDismiss}
            >
              Dismiss
            </Button>
          </Space>
        </Space>
      }
      type="warning"
      showIcon
      style={{
        margin: '16px 0',
        border: '1px solid #faad14',
        backgroundColor: '#fffbe6'
      }}
    />
  );
};

export default TimeDiscrepancyWarning;