/**
 * Time Synchronization Warning Component
 * Generated by Copilot - addresses time discrepancy issues
 */
import React, { useState, useEffect } from 'react';
import { Alert, Button, Space } from 'antd';
import { ClockCircleOutlined, SyncOutlined } from '@ant-design/icons';
import { useTranslation } from 'react-i18next';
import TimeSyncService from '../services/timeSync';

const TimeSyncWarning = () => {
  const { t } = useTranslation();
  const [syncStatus, setSyncStatus] = useState(null);
  const [checking, setChecking] = useState(false);
  const [dismissed, setDismissed] = useState(false);

  const checkTimeSync = async () => {
    setChecking(true);
    try {
      const status = await TimeSyncService.checkTimeSync();
      setSyncStatus(status);
    } catch (error) {
      console.error('Time sync check failed:', error);
    } finally {
      setChecking(false);
    }
  };

  useEffect(() => {
    // Check time sync on component mount
    checkTimeSync();
  }, []);

  // Don't show warning if sync is OK, dismissed, or we haven't checked yet
  if (!syncStatus || syncStatus.syncOk || dismissed) {
    return null;
  }

  const discrepancyFormatted = TimeSyncService.formatDiscrepancy(syncStatus.discrepancy);
  const direction = TimeSyncService.getDiscrepancyDirection(syncStatus.discrepancy);

  const message = (
    <div>
      <div style={{ fontWeight: 500, marginBottom: 8 }}>
        {t('timeSync.warning.title', 'System Time Synchronization Issue')}
      </div>
      <div style={{ marginBottom: 8 }}>
        {t('timeSync.warning.message', 'Your system time appears to be {{direction}} server time by {{discrepancy}}. This may cause authentication issues.', {
          direction: direction === 'ahead' ? t('timeSync.ahead', 'ahead of') : t('timeSync.behind', 'behind'),
          discrepancy: discrepancyFormatted
        })}
      </div>
      <div style={{ fontSize: '12px', color: '#666' }}>
        {t('timeSync.details', 'Client: {{clientTime}} | Server: {{serverTime}}', {
          clientTime: new Date(syncStatus.clientTime).toLocaleString(),
          serverTime: new Date(syncStatus.serverTime).toLocaleString()
        })}
      </div>
    </div>
  );

  const action = (
    <Space>
      <Button
        size="small"
        icon={<SyncOutlined />}
        loading={checking}
        onClick={checkTimeSync}
      >
        {t('timeSync.recheck', 'Recheck')}
      </Button>
      <Button
        size="small"
        onClick={() => setDismissed(true)}
      >
        {t('timeSync.dismiss', 'Dismiss')}
      </Button>
    </Space>
  );

  return (
    <Alert
      message={message}
      type="warning"
      icon={<ClockCircleOutlined />}
      action={action}
      closable={false}
      banner
      style={{
        marginBottom: 16,
        border: '1px solid #faad14',
        borderRadius: 6
      }}
    />
  );
};

export default TimeSyncWarning;