import { defineConfig, devices } from '@playwright/test';

/**
 * Optimized Playwright configuration for reliable E2E tests
 * Generated by Zhuang
 */
export default defineConfig({
  testDir: './tests',
  fullyParallel: false, // Sequential execution for reliability
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 1 : 0, // Minimal retries for faster feedback
  workers: 1, // Single worker to avoid conflicts
  reporter: [['html'], ['list'], ['junit', { outputFile: 'test-results.xml' }]],
  timeout: 60000, // 60 second timeout per test
  
  use: {
    baseURL: 'http://localhost:3000',
    trace: 'retain-on-failure',
    screenshot: 'only-on-failure',
    video: 'retain-on-failure',
    actionTimeout: 15000, // 15 second timeout for actions
    navigationTimeout: 30000, // 30 second timeout for navigation
  },

  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
  ],
  
  // No webServer config - services are manually started
});
