"""
Test cases for health record endpoints. Generated by Zhuang
"""
import json
import pytest
from datetime import datetime


class TestHealthEndpoints:
    """Test health record related endpoints"""
    
    def test_create_health_record(self, client, auth_headers):
        """Test creating a new health record"""
        access_headers = auth_headers['access']
        
        record_data = {
            'systolic': 120,
            'diastolic': 80,
            'heart_rate': 72,
            'timestamp': '2025-08-22T10:00:00Z',
            'tags': ['morning', 'resting'],
            'note': 'Morning measurement'
        }
        
        response = client.post('/api/v1/health', json=record_data, headers=access_headers)
        assert response.status_code == 201
        
        data = response.get_json()
        assert data['systolic'] == 120
        assert data['diastolic'] == 80
        assert data['heart_rate'] == 72
        assert data['tags'] == ['morning', 'resting']
        assert data['note'] == 'Morning measurement'
        assert 'id' in data
        assert 'created_at' in data
    
    def test_create_health_record_unauthorized(self, client):
        """Test creating health record without authorization"""
        record_data = {
            'systolic': 120,
            'diastolic': 80,
            'heart_rate': 72
        }
        
        response = client.post('/api/v1/health', json=record_data)
        assert response.status_code == 401
    
    def test_create_health_record_missing_fields(self, client, auth_headers):
        """Test creating health record with missing required fields"""
        access_headers = auth_headers['access']

        record_data = {
            'systolic': 120
            # Missing diastolic (required), heart_rate is optional
        }

        response = client.post('/api/v1/health', json=record_data, headers=access_headers)
        assert response.status_code == 400

        # Test missing systolic
        record_data = {
            'diastolic': 80
            # Missing systolic (required)
        }

        response = client.post('/api/v1/health', json=record_data, headers=access_headers)
        assert response.status_code == 400
    
    def test_list_health_records(self, client, auth_headers):
        """Test listing health records"""
        access_headers = auth_headers['access']
        
        # Create a few records first
        records = [
            {'systolic': 120, 'diastolic': 80, 'heart_rate': 72, 'tags': ['morning']},
            {'systolic': 130, 'diastolic': 85, 'heart_rate': 75, 'tags': ['evening']},
            {'systolic': 125, 'diastolic': 82, 'heart_rate': 70, 'tags': ['afternoon']}
        ]
        
        for record in records:
            client.post('/api/v1/health', json=record, headers=access_headers)
        
        # Test listing all records
        response = client.get('/api/v1/health', headers=access_headers)
        assert response.status_code == 200
        
        data = response.get_json()
        assert 'records' in data
        assert 'pagination' in data
        assert len(data['records']) == 3
    
    def test_list_health_records_pagination(self, client, auth_headers):
        """Test health records pagination"""
        access_headers = auth_headers['access']
        
        # Create multiple records
        for i in range(25):
            record = {
                'systolic': 120 + i,
                'diastolic': 80,
                'heart_rate': 72,
                'tags': [f'test{i}']
            }
            client.post('/api/v1/health', json=record, headers=access_headers)
        
        # Test first page
        response = client.get('/api/v1/health?page=1&size=10', headers=access_headers)
        assert response.status_code == 200
        
        data = response.get_json()
        assert len(data['records']) == 10
        assert data['pagination']['page'] == 1
        assert data['pagination']['size'] == 10
        assert data['pagination']['total'] == 25
        assert data['pagination']['pages'] == 3
        
        # Test second page
        response = client.get('/api/v1/health?page=2&size=10', headers=access_headers)
        assert response.status_code == 200
        
        data = response.get_json()
        assert len(data['records']) == 10
        assert data['pagination']['page'] == 2
    
    def test_list_health_records_filter_by_tags(self, client, auth_headers):
        """Test filtering health records by tags"""
        access_headers = auth_headers['access']
        
        # Create records with different tags
        records = [
            {'systolic': 120, 'diastolic': 80, 'heart_rate': 72, 'tags': ['morning', 'home']},
            {'systolic': 130, 'diastolic': 85, 'heart_rate': 75, 'tags': ['evening', 'work']},
            {'systolic': 125, 'diastolic': 82, 'heart_rate': 70, 'tags': ['morning', 'gym']}
        ]
        
        for record in records:
            client.post('/api/v1/health', json=record, headers=access_headers)
        
        # Filter by 'morning' tag
        response = client.get('/api/v1/health?tags=morning', headers=access_headers)
        assert response.status_code == 200
        
        data = response.get_json()
        assert len(data['records']) == 2
        for record in data['records']:
            assert 'morning' in record['tags']

        # Generated by Zhuang: Filter by multiple tags should use OR semantics
        response = client.get('/api/v1/health?tags=morning,work', headers=access_headers)
        assert response.status_code == 200
        data = response.get_json()
        # morning matches 2, work matches 1, but one record may overlap; in our dataset it's 3 total
        assert len(data['records']) == 3
        # Ensure each record has at least one of the requested tags
        for record in data['records']:
            assert any(t in record['tags'] for t in ['morning', 'work'])
    
    def test_get_health_record(self, client, auth_headers):
        """Test getting a specific health record"""
        access_headers = auth_headers['access']
        
        # Create a record first
        record_data = {
            'systolic': 120,
            'diastolic': 80,
            'heart_rate': 72,
            'note': 'Test record'
        }
        
        create_response = client.post('/api/v1/health', json=record_data, headers=access_headers)
        record_id = create_response.get_json()['id']
        
        # Get the specific record
        response = client.get(f'/api/v1/health/{record_id}', headers=access_headers)
        assert response.status_code == 200
        
        data = response.get_json()
        assert data['id'] == record_id
        assert data['systolic'] == 120
        assert data['note'] == 'Test record'
    
    def test_get_health_record_not_found(self, client, auth_headers):
        """Test getting non-existent health record"""
        access_headers = auth_headers['access']
        
        response = client.get('/api/v1/health/999', headers=access_headers)
        assert response.status_code == 404
    
    def test_update_health_record(self, client, auth_headers):
        """Test updating a health record"""
        access_headers = auth_headers['access']
        
        # Create a record first
        record_data = {
            'systolic': 120,
            'diastolic': 80,
            'heart_rate': 72,
            'note': 'Original note'
        }
        
        create_response = client.post('/api/v1/health', json=record_data, headers=access_headers)
        record_id = create_response.get_json()['id']
        
        # Update the record
        update_data = {
            'systolic': 125,
            'note': 'Updated note'
        }
        
        response = client.put(f'/api/v1/health/{record_id}', json=update_data, headers=access_headers)
        assert response.status_code == 200
        
        data = response.get_json()
        assert data['systolic'] == 125
        assert data['diastolic'] == 80  # Should remain unchanged
        assert data['note'] == 'Updated note'
    
    def test_delete_health_record(self, client, auth_headers):
        """Test deleting a health record"""
        access_headers = auth_headers['access']
        
        # Create a record first
        record_data = {
            'systolic': 120,
            'diastolic': 80,
            'heart_rate': 72
        }
        
        create_response = client.post('/api/v1/health', json=record_data, headers=access_headers)
        record_id = create_response.get_json()['id']
        
        # Delete the record
        response = client.delete(f'/api/v1/health/{record_id}', headers=access_headers)
        assert response.status_code == 200
        
        # Verify it's deleted
        get_response = client.get(f'/api/v1/health/{record_id}', headers=access_headers)
        assert get_response.status_code == 404
    
    def test_health_record_ownership(self, client, auth_headers):
        """Test that users can only access their own health records"""
        access_headers = auth_headers['access']
        
        # Create a record with first user
        record_data = {
            'systolic': 120,
            'diastolic': 80,
            'heart_rate': 72
        }
        
        create_response = client.post('/api/v1/health', json=record_data, headers=access_headers)
        record_id = create_response.get_json()['id']
        
        # Create a second user
        client.post('/api/v1/auth/register', json={
            'username': 'user2',
            'email': 'user2@example.com',
            'password': 'password123'
        })
        
        # Login as second user
        login_response = client.post('/api/v1/auth/login', json={
            'email': 'user2@example.com',
            'password': 'password123'
        })
        
        user2_token = login_response.get_json()['access_token']
        user2_headers = {'Authorization': f'Bearer {user2_token}'}
        
        # Second user should not be able to access first user's record
        response = client.get(f'/api/v1/health/{record_id}', headers=user2_headers)
        assert response.status_code == 404  # Or 403, depending on implementation

    def test_blood_pressure_validation_ranges(self, client, auth_headers):
        """Test blood pressure validation with new ranges (30-250)"""
        access_headers = auth_headers['access']

        # Test valid boundary values
        valid_records = [
            {'systolic': 31, 'diastolic': 30},  # Lower boundary (systolic must be > diastolic)
            {'systolic': 250, 'diastolic': 249},  # Upper boundary
            {'systolic': 120, 'diastolic': 80},  # Normal values
        ]

        for record in valid_records:
            response = client.post('/api/v1/health', json=record, headers=access_headers)
            assert response.status_code == 201, f"Valid record should be accepted: {record}"

        # Test invalid values - below range
        invalid_low_records = [
            {'systolic': 29, 'diastolic': 80},
            {'systolic': 120, 'diastolic': 29},
            {'systolic': 20, 'diastolic': 20},
        ]

        for record in invalid_low_records:
            response = client.post('/api/v1/health', json=record, headers=access_headers)
            assert response.status_code == 400, f"Invalid low record should be rejected: {record}"
            data = response.get_json()
            assert 'details' in data
            assert any('30-250' in detail['message'] for detail in data['details'])

        # Test invalid values - above range
        invalid_high_records = [
            {'systolic': 251, 'diastolic': 80},
            {'systolic': 120, 'diastolic': 251},
            {'systolic': 300, 'diastolic': 300},
        ]

        for record in invalid_high_records:
            response = client.post('/api/v1/health', json=record, headers=access_headers)
            assert response.status_code == 400, f"Invalid high record should be rejected: {record}"
            data = response.get_json()
            assert 'details' in data
            assert any('30-250' in detail['message'] for detail in data['details'])

    def test_systolic_greater_than_diastolic_validation(self, client, auth_headers):
        """Test that systolic pressure must be greater than diastolic pressure"""
        access_headers = auth_headers['access']

        # Test invalid cases where systolic <= diastolic
        invalid_records = [
            {'systolic': 80, 'diastolic': 80},  # Equal
            {'systolic': 70, 'diastolic': 80},  # Systolic lower
            {'systolic': 100, 'diastolic': 120},  # Systolic much lower
        ]

        for record in invalid_records:
            response = client.post('/api/v1/health', json=record, headers=access_headers)
            assert response.status_code == 400, f"Invalid BP relationship should be rejected: {record}"
            data = response.get_json()
            assert 'details' in data
            assert any('greater than diastolic' in detail['message'] for detail in data['details'])

        # Test valid case where systolic > diastolic
        valid_record = {'systolic': 120, 'diastolic': 80}
        response = client.post('/api/v1/health', json=valid_record, headers=access_headers)
        assert response.status_code == 201

    def test_heart_rate_validation_ranges(self, client, auth_headers):
        """Test heart rate validation with new ranges (30-150)"""
        access_headers = auth_headers['access']

        # Test valid heart rate values
        valid_records = [
            {'systolic': 120, 'diastolic': 80, 'heart_rate': 30},  # Lower boundary
            {'systolic': 120, 'diastolic': 80, 'heart_rate': 150},  # Upper boundary
            {'systolic': 120, 'diastolic': 80, 'heart_rate': 72},  # Normal value
            {'systolic': 120, 'diastolic': 80},  # No heart rate (optional)
        ]

        for record in valid_records:
            response = client.post('/api/v1/health', json=record, headers=access_headers)
            assert response.status_code == 201, f"Valid record should be accepted: {record}"

        # Test invalid heart rate values
        invalid_records = [
            {'systolic': 120, 'diastolic': 80, 'heart_rate': 29},  # Below range
            {'systolic': 120, 'diastolic': 80, 'heart_rate': 151},  # Above range
            {'systolic': 120, 'diastolic': 80, 'heart_rate': 200},  # Much above range
        ]

        for record in invalid_records:
            response = client.post('/api/v1/health', json=record, headers=access_headers)
            assert response.status_code == 400, f"Invalid heart rate should be rejected: {record}"
            data = response.get_json()
            assert 'details' in data
            assert any('30-150' in detail['message'] for detail in data['details'])

    def test_heart_rate_optional_validation(self, client, auth_headers):
        """Test that heart rate field is optional"""
        access_headers = auth_headers['access']

        # Test various ways to omit heart rate
        optional_records = [
            {'systolic': 120, 'diastolic': 80},  # No heart_rate field
            {'systolic': 120, 'diastolic': 80, 'heart_rate': None},  # Explicit None
            {'systolic': 120, 'diastolic': 80, 'heart_rate': ''},  # Empty string
            {'systolic': 120, 'diastolic': 80, 'heart_rate': 0},  # Zero
        ]

        for record in optional_records:
            response = client.post('/api/v1/health', json=record, headers=access_headers)
            assert response.status_code == 201, f"Record without heart rate should be accepted: {record}"
            data = response.get_json()
            # Heart rate should be None in response when omitted
            if 'heart_rate' not in record or record['heart_rate'] in [None, '', 0]:
                assert data['heart_rate'] is None

    def test_update_validation_with_new_rules(self, client, auth_headers):
        """Test updating records with new validation rules"""
        access_headers = auth_headers['access']

        # Create a valid record first
        record_data = {'systolic': 120, 'diastolic': 80, 'heart_rate': 72}
        create_response = client.post('/api/v1/health', json=record_data, headers=access_headers)
        record_id = create_response.get_json()['id']

        # Test invalid updates
        invalid_updates = [
            {'systolic': 29},  # Below range
            {'diastolic': 251},  # Above range
            {'systolic': 70, 'diastolic': 80},  # Systolic <= diastolic
            {'heart_rate': 151},  # Heart rate above range
        ]

        for update_data in invalid_updates:
            response = client.put(f'/api/v1/health/{record_id}', json=update_data, headers=access_headers)
            assert response.status_code == 400, f"Invalid update should be rejected: {update_data}"
            data = response.get_json()
            assert 'details' in data

        # Test valid updates
        valid_updates = [
            {'systolic': 130},  # Valid systolic
            {'diastolic': 85},  # Valid diastolic
            {'heart_rate': 75},  # Valid heart rate
            {'heart_rate': None},  # Remove heart rate
        ]

        for update_data in valid_updates:
            response = client.put(f'/api/v1/health/{record_id}', json=update_data, headers=access_headers)
            assert response.status_code == 200, f"Valid update should be accepted: {update_data}"

    def test_non_numeric_validation(self, client, auth_headers):
        """Test validation with non-numeric inputs"""
        access_headers = auth_headers['access']

        # Test non-numeric inputs
        invalid_records = [
            {'systolic': 'abc', 'diastolic': 80},
            {'systolic': 120, 'diastolic': 'xyz'},
            {'systolic': 120, 'diastolic': 80, 'heart_rate': 'invalid'},
            {'systolic': 120.5, 'diastolic': 80},  # Decimal should be rejected as non-integer
        ]

        for record in invalid_records:
            response = client.post('/api/v1/health', json=record, headers=access_headers)
            assert response.status_code == 400, f"Non-numeric record should be rejected: {record}"
            data = response.get_json()
            assert 'details' in data
