"""
Test time synchronization functionality
Generated by Copilot - addresses time discrepancy issues
"""
import pytest
from datetime import datetime, timezone
from src.app import create_app


class TestTimeSync:
    @pytest.fixture
    def app(self):
        app = create_app()
        app.config['TESTING'] = True
        return app

    @pytest.fixture
    def client(self, app):
        return app.test_client()

    def test_time_endpoint_success(self, client):
        """Test that the time endpoint returns proper UTC time"""
        response = client.get('/api/v1/auth/time')
        
        assert response.status_code == 200
        data = response.get_json()
        
        # Check required fields
        assert 'server_time' in data
        assert 'timestamp' in data
        assert 'timezone' in data
        
        # Verify timezone is UTC
        assert data['timezone'] == 'UTC'
        
        # Verify server_time ends with Z (UTC format)
        assert data['server_time'].endswith('Z')
        
        # Verify timestamp is a valid integer (Unix timestamp)
        assert isinstance(data['timestamp'], int)
        assert data['timestamp'] > 0
        
        # Verify server_time can be parsed
        server_time = datetime.fromisoformat(data['server_time'].replace('Z', '+00:00'))
        assert server_time.tzinfo == timezone.utc
        
        # Verify timestamp matches server_time
        expected_timestamp = int(server_time.timestamp())
        # Allow small discrepancy due to processing time
        assert abs(data['timestamp'] - expected_timestamp) <= 1

    def test_time_endpoint_no_auth_required(self, client):
        """Test that the time endpoint doesn't require authentication"""
        # Should work without any authentication headers
        response = client.get('/api/v1/auth/time')
        assert response.status_code == 200

    def test_time_endpoint_consistency(self, client):
        """Test that multiple calls return consistent time progression"""
        import time
        
        # First call
        response1 = client.get('/api/v1/auth/time')
        assert response1.status_code == 200
        data1 = response1.get_json()
        
        # Small delay
        time.sleep(0.1)
        
        # Second call
        response2 = client.get('/api/v1/auth/time')
        assert response2.status_code == 200
        data2 = response2.get_json()
        
        # Second timestamp should be greater than or equal to first
        assert data2['timestamp'] >= data1['timestamp']
        
        # Parse times
        time1 = datetime.fromisoformat(data1['server_time'].replace('Z', '+00:00'))
        time2 = datetime.fromisoformat(data2['server_time'].replace('Z', '+00:00'))
        
        # Second time should be after first time
        assert time2 >= time1
        
    def test_time_endpoint_format(self, client):
        """Test that the time endpoint returns properly formatted ISO string"""
        response = client.get('/api/v1/auth/time')
        assert response.status_code == 200
        data = response.get_json()
        
        server_time = data['server_time']
        
        # Should be in ISO format with Z suffix
        assert server_time.endswith('Z')
        
        # Should be parseable as ISO datetime
        try:
            parsed_time = datetime.fromisoformat(server_time.replace('Z', '+00:00'))
            assert parsed_time.tzinfo == timezone.utc
        except ValueError:
            pytest.fail(f"Server time '{server_time}' is not a valid ISO format")