"""
Tests for time synchronization functionality. Generated by Copilot
"""
import pytest
from datetime import datetime, UTC, timedelta
from unittest.mock import patch
from src.app import create_app


class TestTimeSyncEndpoints:
    """Test time synchronization related endpoints"""

    def test_server_time_endpoint(self, client):
        """Test server time endpoint returns correct format"""
        response = client.get('/api/v1/auth/server-time')
        assert response.status_code == 200
        
        data = response.get_json()
        assert 'server_time' in data
        assert 'timestamp' in data
        
        # Verify the server_time is in ISO format with Z suffix
        assert data['server_time'].endswith('Z')
        
        # Verify timestamp is a number (milliseconds)
        assert isinstance(data['timestamp'], int)
        assert data['timestamp'] > 0
        
        # Verify timestamp matches server_time
        server_time = datetime.fromisoformat(data['server_time'].replace('Z', '+00:00'))
        expected_timestamp = int(server_time.timestamp() * 1000)
        # Allow small difference due to processing time
        assert abs(data['timestamp'] - expected_timestamp) < 1000

    def test_server_time_consistency(self, client):
        """Test multiple calls to server time endpoint are consistent"""
        responses = []
        for _ in range(3):
            response = client.get('/api/v1/auth/server-time')
            assert response.status_code == 200
            responses.append(response.get_json())
        
        # All responses should be within a reasonable time window (5 seconds)
        timestamps = [r['timestamp'] for r in responses]
        assert max(timestamps) - min(timestamps) < 5000  # 5 seconds

    def test_server_time_no_auth_required(self, client):
        """Test server time endpoint doesn't require authentication"""
        # No auth headers needed
        response = client.get('/api/v1/auth/server-time')
        assert response.status_code == 200
        
        data = response.get_json()
        assert 'server_time' in data
        assert 'timestamp' in data

    @patch('src.service.auth_service.datetime')
    def test_server_time_uses_utc(self, mock_datetime, client):
        """Test server time endpoint uses UTC"""
        # Mock datetime.now(UTC) to return a specific time
        fixed_time = datetime(2024, 1, 1, 12, 0, 0, tzinfo=UTC)
        mock_datetime.now.return_value = fixed_time
        
        response = client.get('/api/v1/auth/server-time')
        assert response.status_code == 200
        
        data = response.get_json()
        assert data['server_time'] == '2024-01-01T12:00:00Z'
        assert data['timestamp'] == int(fixed_time.timestamp() * 1000)
        
        # Verify datetime.now was called with UTC
        mock_datetime.now.assert_called_with(UTC)

    def test_server_time_headers(self, client):
        """Test server time endpoint has correct headers"""
        response = client.get('/api/v1/auth/server-time')
        assert response.status_code == 200
        assert response.headers['Content-Type'] == 'application/json'