"""
Test cases for import service endpoints. Generated by Copilot
"""
import json
import pytest
import pandas as pd
from io import BytesIO
from src.models import HealthRecord, ImportLog


class TestImportServiceUpload:
    """Test import upload endpoint"""
    
    def test_upload_without_auth(self, client):
        """Test upload without authentication"""
        response = client.post('/api/v1/import/upload')
        assert response.status_code == 401
    
    def test_upload_without_file(self, client, auth_headers):
        """Test upload without file"""
        access_headers = auth_headers['access']
        
        response = client.post('/api/v1/import/upload', headers=access_headers)
        assert response.status_code == 400
        
        data = response.get_json()
        assert '上传文件' in data['message']
    
    def test_upload_valid_excel(self, client, auth_headers):
        """Test uploading valid Excel file"""
        access_headers = auth_headers['access']
        
        # Create sample Excel file
        data_dict = {
            '成员名称': ['Self', 'Self'],
            '测量时间': ['2025-12-19 08:30:00', '2025-12-19 09:00:00'],
            '收缩压': [120, 125],
            '舒张压': [80, 82],
            '心率': [72, 75],
            '标签': ['晨起', '餐后'],
            '备注': ['正常', '正常']
        }
        df = pd.DataFrame(data_dict)
        
        excel_file = BytesIO()
        df.to_excel(excel_file, index=False, engine='openpyxl')
        excel_file.seek(0)
        
        # Upload file
        response = client.post(
            '/api/v1/import/upload',
            data={'file': (excel_file, 'test.xlsx')},
            headers=access_headers,
            content_type='multipart/form-data'
        )
        
        assert response.status_code == 200
        
        data = response.get_json()
        assert data['total'] == 2
        assert data['success'] == 2
        assert data['failed'] == 0
        assert '导入完成' in data['message']
        
        # Verify records in database
        records = HealthRecord.query.all()
        assert len(records) == 2
        
        # Verify import log created
        logs = ImportLog.query.all()
        assert len(logs) == 1
        assert logs[0].status == 'success'
    
    def test_upload_valid_csv(self, client, auth_headers):
        """Test uploading valid CSV file"""
        access_headers = auth_headers['access']
        
        # Create sample CSV file
        csv_content = """成员名称,测量时间,收缩压,舒张压,心率,标签,备注
Self,2025-12-19 08:30:00,120,80,72,晨起,正常
Self,2025-12-19 09:00:00,125,82,75,餐后,正常"""
        
        csv_file = BytesIO(csv_content.encode('utf-8-sig'))
        
        # Upload file
        response = client.post(
            '/api/v1/import/upload',
            data={'file': (csv_file, 'test.csv')},
            headers=access_headers,
            content_type='multipart/form-data'
        )
        
        assert response.status_code == 200
        
        data = response.get_json()
        assert data['total'] == 2
        assert data['success'] == 2
        assert data['failed'] == 0
    
    def test_upload_partial_success(self, client, auth_headers):
        """Test upload with some invalid rows"""
        access_headers = auth_headers['access']
        
        # Create CSV with one invalid row
        csv_content = """成员名称,测量时间,收缩压,舒张压,心率,标签,备注
Self,2025-12-19 08:30:00,120,80,72,晨起,正常
不存在的成员,2025-12-19 09:00:00,125,82,75,餐后,正常
Self,2025-12-19 10:00:00,130,85,78,午休,正常"""
        
        csv_file = BytesIO(csv_content.encode('utf-8-sig'))
        
        # Upload file
        response = client.post(
            '/api/v1/import/upload',
            data={'file': (csv_file, 'test.csv')},
            headers=access_headers,
            content_type='multipart/form-data'
        )
        
        assert response.status_code == 200
        
        data = response.get_json()
        assert data['total'] == 3
        assert data['success'] == 2
        assert data['failed'] == 1
        assert len(data['errors']) == 1
        assert data['errors'][0]['row'] == 2
        
        # Verify import log status is partial
        log = ImportLog.query.first()
        assert log.status == 'partial'
    
    def test_upload_unsupported_format(self, client, auth_headers):
        """Test uploading unsupported file format"""
        access_headers = auth_headers['access']
        
        txt_file = BytesIO(b"some text content")
        
        response = client.post(
            '/api/v1/import/upload',
            data={'file': (txt_file, 'test.txt')},
            headers=access_headers,
            content_type='multipart/form-data'
        )
        
        assert response.status_code == 400
        
        data = response.get_json()
        assert '不支持的文件格式' in data['message']
    
    def test_upload_empty_file(self, client, auth_headers):
        """Test uploading empty file"""
        access_headers = auth_headers['access']
        
        empty_file = BytesIO(b"")
        
        response = client.post(
            '/api/v1/import/upload',
            data={'file': (empty_file, 'test.xlsx')},
            headers=access_headers,
            content_type='multipart/form-data'
        )
        
        assert response.status_code == 400
        
        data = response.get_json()
        assert '文件为空' in data['message']
    
    def test_upload_file_too_large(self, client, auth_headers):
        """Test uploading file exceeding size limit"""
        access_headers = auth_headers['access']
        
        # Create a file larger than 5MB
        large_content = b"x" * (6 * 1024 * 1024)
        large_file = BytesIO(large_content)
        
        response = client.post(
            '/api/v1/import/upload',
            data={'file': (large_file, 'large.xlsx')},
            headers=access_headers,
            content_type='multipart/form-data'
        )
        
        assert response.status_code == 400
        
        data = response.get_json()
        assert '文件大小超过限制' in data['message']
    
    def test_upload_too_many_rows(self, client, auth_headers):
        """Test uploading file with too many rows"""
        access_headers = auth_headers['access']
        
        # Create Excel with more than 1000 rows
        data_dict = {
            '成员名称': ['Self'] * 1001,
            '测量时间': ['2025-12-19 08:30:00'] * 1001,
            '收缩压': [120] * 1001,
            '舒张压': [80] * 1001
        }
        df = pd.DataFrame(data_dict)
        
        excel_file = BytesIO()
        df.to_excel(excel_file, index=False, engine='openpyxl')
        excel_file.seek(0)
        
        response = client.post(
            '/api/v1/import/upload',
            data={'file': (excel_file, 'large.xlsx')},
            headers=access_headers,
            content_type='multipart/form-data'
        )
        
        assert response.status_code == 400
        
        data = response.get_json()
        assert '行数超过限制' in data['message']
    
    def test_upload_with_skip_errors_false(self, client, auth_headers):
        """Test upload with skip_errors=false"""
        access_headers = auth_headers['access']
        
        # Create CSV with one invalid row
        csv_content = """成员名称,测量时间,收缩压,舒张压,心率,标签,备注
Self,2025-12-19 08:30:00,120,80,72,晨起,正常
不存在的成员,2025-12-19 09:00:00,125,82,75,餐后,正常"""
        
        csv_file = BytesIO(csv_content.encode('utf-8-sig'))
        
        # Upload file with skip_errors=false
        response = client.post(
            '/api/v1/import/upload',
            data={
                'file': (csv_file, 'test.csv'),
                'skip_errors': 'false'
            },
            headers=access_headers,
            content_type='multipart/form-data'
        )
        
        assert response.status_code == 200
        
        data = response.get_json()
        assert data['total'] == 2
        assert data['success'] == 0
        assert data['failed'] == 2
        
        # Verify no records imported
        records = HealthRecord.query.all()
        assert len(records) == 0
    
    def test_upload_with_various_member_names(self, client, auth_headers, app):
        """Test upload with various member name formats"""
        access_headers = auth_headers['access']
        
        # Create CSV with different member name variations
        csv_content = """成员名称,测量时间,收缩压,舒张压
Self,2025-12-19 08:30:00,120,80
self,2025-12-19 09:00:00,122,81
自己,2025-12-19 10:00:00,118,79
本人,2025-12-19 11:00:00,121,80"""
        
        csv_file = BytesIO(csv_content.encode('utf-8-sig'))
        
        response = client.post(
            '/api/v1/import/upload',
            data={'file': (csv_file, 'test.csv')},
            headers=access_headers,
            content_type='multipart/form-data'
        )
        
        assert response.status_code == 200
        
        data = response.get_json()
        assert data['total'] == 4
        assert data['success'] == 4
        assert data['failed'] == 0
        
        # Verify all records imported
        records = HealthRecord.query.all()
        assert len(records) == 4
    
    def test_upload_with_tags(self, client, auth_headers):
        """Test upload with semicolon-separated tags"""
        access_headers = auth_headers['access']
        
        csv_content = """成员名称,测量时间,收缩压,舒张压,标签
Self,2025-12-19 08:30:00,120,80,晨起;空腹;正常"""
        
        csv_file = BytesIO(csv_content.encode('utf-8-sig'))
        
        response = client.post(
            '/api/v1/import/upload',
            data={'file': (csv_file, 'test.csv')},
            headers=access_headers,
            content_type='multipart/form-data'
        )
        
        assert response.status_code == 200
        
        # Verify tags parsed correctly
        record = HealthRecord.query.first()
        tags = json.loads(record.tags)
        assert len(tags) == 3
        assert '晨起' in tags
        assert '空腹' in tags
        assert '正常' in tags
    
    def test_upload_with_timezone_handling(self, client, auth_headers):
        """Test upload with various timestamp formats"""
        access_headers = auth_headers['access']
        
        csv_content = """成员名称,测量时间,收缩压,舒张压
Self,2025-12-19 08:30:00,120,80
Self,2025-12-19T09:00:00,122,81
Self,2025/12/19 10:00,118,79"""
        
        csv_file = BytesIO(csv_content.encode('utf-8-sig'))
        
        response = client.post(
            '/api/v1/import/upload',
            data={'file': (csv_file, 'test.csv')},
            headers=access_headers,
            content_type='multipart/form-data'
        )
        
        assert response.status_code == 200
        
        data = response.get_json()
        assert data['total'] == 3
        assert data['success'] == 3
        assert data['failed'] == 0
