"""
Tests for Issue #51: Improved chart color contrast and clarity
Generated by Copilot
"""
import pytest
from datetime import datetime, UTC
from src.app import create_app
from src.extensions import db


class TestIssue51ColorImprovements:
    """Test color scheme improvements from Issue #51"""
    
    @pytest.fixture
    def app(self):
        app = create_app()
        app.config.update({
            "TESTING": True,
            "SQLALCHEMY_DATABASE_URI": "sqlite:///:memory:",
            "JWT_SECRET_KEY": "test-secret-key"
        })
        
        with app.app_context():
            db.create_all()
            yield app
            
    @pytest.fixture
    def client(self, app):
        return app.test_client()
        
    @pytest.fixture
    def user_tokens(self, client):
        """Create user and return access tokens"""
        user_data = {
            "username": "color_test_user",
            "email": "colortest@test.com", 
            "password": "testpass123"
        }
        
        # Register user
        client.post("/api/v1/auth/register", json=user_data)
        
        # Login to get tokens
        login_resp = client.post("/api/v1/auth/login", json={
            "email": "colortest@test.com",
            "password": "testpass123"
        })
        
        data = login_resp.get_json()
        return data["access_token"], data["refresh_token"]
    
    def test_color_scheme_data_structure(self, client, user_tokens):
        """Test that data structure supports the new color scheme requirements"""
        access_token, _ = user_tokens
        headers = {"Authorization": f"Bearer {access_token}"}
        
        # Create test records with different BP classifications
        test_cases = [
            # Normal BP cases - should use line colors (blue/green)
            {"systolic": 110, "diastolic": 70, "classification": "normal", "expected_systolic_color": "blue", "expected_diastolic_color": "green"},
            {"systolic": 115, "diastolic": 75, "classification": "normal", "expected_systolic_color": "blue", "expected_diastolic_color": "green"},
            {"systolic": 119, "diastolic": 79, "classification": "normal", "expected_systolic_color": "blue", "expected_diastolic_color": "green"},
            
            # Abnormal BP cases - should use red color for both
            {"systolic": 120, "diastolic": 78, "classification": "abnormal", "expected_systolic_color": "red", "expected_diastolic_color": "green"},  # systolic high
            {"systolic": 118, "diastolic": 80, "classification": "abnormal", "expected_systolic_color": "blue", "expected_diastolic_color": "red"},   # diastolic high
            {"systolic": 125, "diastolic": 85, "classification": "abnormal", "expected_systolic_color": "red", "expected_diastolic_color": "red"},     # both high
        ]
        
        # Create records
        for i, case in enumerate(test_cases):
            record_data = {
                "systolic": case["systolic"],
                "diastolic": case["diastolic"],
                "heart_rate": 75,
                "timestamp": datetime.now(UTC).isoformat().replace("+00:00", "Z"),
                "tags": ["颜色测试"],
                "note": f"Color test {i+1}: {case['classification']} BP"
            }
            
            resp = client.post("/api/v1/health", json=record_data, headers=headers)
            assert resp.status_code == 201
            
        # Retrieve records
        list_resp = client.get("/api/v1/health", headers=headers)
        assert list_resp.status_code == 200
        
        records = list_resp.get_json()["records"]
        color_test_records = [r for r in records if "Color test" in r.get("note", "")]
        
        assert len(color_test_records) == len(test_cases)
        
        # Verify data structure for color logic
        for record in color_test_records:
            systolic = record["systolic"]
            diastolic = record["diastolic"]
            
            # Test the color classification logic (matches frontend implementation)
            is_abnormal_bp = (systolic >= 120) or (diastolic >= 80)
            
            # Verify we have the data needed for color decisions
            assert systolic is not None
            assert diastolic is not None
            assert isinstance(systolic, int)
            assert isinstance(diastolic, int)
            
            print(f"✓ BP {systolic}/{diastolic}: {'abnormal' if is_abnormal_bp else 'normal'}")
    
    def test_color_hex_values_documentation(self):
        """Document the specific color values used in Issue #51"""
        
        # Colors as specified in Issue #51 requirements
        color_scheme = {
            # Line colors (线条颜色)
            "systolic_line": "#1890ff",     # 收缩压(高压)线条：蓝色
            "diastolic_line": "#52c41a",    # 舒张压(低压)线条：绿色
            "heart_rate_line": "#1890ff",   # 心率线条：蓝色 (unchanged)
            
            # Data point colors (数据点颜色)
            "normal_systolic": "#1890ff",   # 正常血压收缩压点：蓝色 (与线条同色)
            "normal_diastolic": "#52c41a",  # 正常血压舒张压点：绿色 (与线条同色)
            "abnormal_bp": "#ff4d4f",       # 异常血压点：红色 (both systolic and diastolic)
        }
        
        # Verify color contrast requirements
        assert color_scheme["systolic_line"] != color_scheme["diastolic_line"], "Line colors must be different for contrast"
        assert color_scheme["abnormal_bp"] not in [color_scheme["systolic_line"], color_scheme["diastolic_line"]], "Abnormal color must stand out"
        
        # Verify color accessibility (basic check)
        blue = color_scheme["systolic_line"]
        green = color_scheme["diastolic_line"] 
        red = color_scheme["abnormal_bp"]
        
        assert blue.startswith("#") and len(blue) == 7, "Blue color must be valid hex"
        assert green.startswith("#") and len(green) == 7, "Green color must be valid hex"
        assert red.startswith("#") and len(red) == 7, "Red color must be valid hex"
        
        print("✓ Color scheme validation passed:")
        for key, value in color_scheme.items():
            print(f"  {key}: {value}")
    
    def test_blood_pressure_classification_accuracy(self):
        """Test the accuracy of BP classification for color assignment"""
        
        test_cases = [
            # Normal BP (< 120 AND < 80) - should use line colors
            (110, 70, False),
            (115, 75, False), 
            (119, 79, False),
            
            # Abnormal BP (>= 120 OR >= 80) - should use red
            (120, 70, True),   # systolic boundary
            (110, 80, True),   # diastolic boundary
            (120, 80, True),   # both at boundary
            (130, 85, True),   # both high
            (140, 95, True),   # hypertension
        ]
        
        for systolic, diastolic, expected_abnormal in test_cases:
            # This matches the frontend logic in HealthChart.js
            is_abnormal = (systolic >= 120) or (diastolic >= 80)
            
            assert is_abnormal == expected_abnormal, \
                f"BP {systolic}/{diastolic} classification incorrect: expected {'abnormal' if expected_abnormal else 'normal'}"
            
            if expected_abnormal:
                expected_colors = "both red"
            else:
                expected_colors = "blue/green"
                
            print(f"✓ BP {systolic}/{diastolic}: {'abnormal' if is_abnormal else 'normal'} -> {expected_colors}")


# Run with: python -m pytest tests/test_issue_51.py -v