"""
Test cases for health record endpoints. Generated by Zhuang
Updated to test new validation rules. Generated by Copilot
"""
import json
import pytest
from datetime import datetime


class TestHealthEndpoints:
    """Test health record related endpoints"""
    
    def test_create_health_record(self, client, auth_headers):
        """Test creating a new health record"""
        access_headers = auth_headers['access']
        
        record_data = {
            'systolic': 120,
            'diastolic': 80,
            'heart_rate': 72,
            'timestamp': '2025-08-22T10:00:00Z',
            'tags': ['morning', 'resting'],
            'note': 'Morning measurement'
        }
        
        response = client.post('/api/v1/health', json=record_data, headers=access_headers)
        assert response.status_code == 201
        
        data = response.get_json()
        assert data['systolic'] == 120
        assert data['diastolic'] == 80
        assert data['heart_rate'] == 72
        assert data['tags'] == ['morning', 'resting']
        assert data['note'] == 'Morning measurement'
        assert 'id' in data
        assert 'created_at' in data

    # Generated by Copilot: AC-1 Blood pressure range validation tests
    @pytest.mark.parametrize("systolic,diastolic,expected_status", [
        (29, 80, 400),   # Systolic too low
        (251, 80, 400),  # Systolic too high
        (120, 29, 400),  # Diastolic too low
        (120, 251, 400), # Diastolic too high
        (30, 30, 400),   # Edge case: systolic = diastolic (should fail systolic > diastolic)
        (31, 30, 201),   # Edge case: minimum valid systolic > diastolic
        (250, 249, 201), # Edge case: maximum valid systolic > diastolic
        (120, 80, 201),  # Valid case
    ])
    def test_blood_pressure_range_validation(self, client, auth_headers, systolic, diastolic, expected_status):
        """Test blood pressure range validation (AC-1)"""
        access_headers = auth_headers['access']
        
        record_data = {
            'systolic': systolic,
            'diastolic': diastolic,
            'heart_rate': 72
        }
        
        response = client.post('/api/v1/health', json=record_data, headers=access_headers)
        assert response.status_code == expected_status
        
        if expected_status == 400:
            data = response.get_json()
            assert 'error' in data or 'message' in data

    # Generated by Copilot: AC-2 Heart rate range validation tests
    @pytest.mark.parametrize("heart_rate,expected_status", [
        (29, 400),    # Too low
        (151, 400),   # Too high
        (30, 201),    # Minimum valid
        (150, 201),   # Maximum valid
        (72, 201),    # Normal valid
        (None, 201),  # Optional - should be allowed
    ])
    def test_heart_rate_range_validation(self, client, auth_headers, heart_rate, expected_status):
        """Test heart rate range validation (AC-2)"""
        access_headers = auth_headers['access']
        
        record_data = {
            'systolic': 120,
            'diastolic': 80
        }
        if heart_rate is not None:
            record_data['heart_rate'] = heart_rate
        
        response = client.post('/api/v1/health', json=record_data, headers=access_headers)
        assert response.status_code == expected_status

    # Generated by Copilot: AC-3 Systolic > Diastolic validation tests
    @pytest.mark.parametrize("systolic,diastolic,expected_status", [
        (80, 80, 400),   # Equal - should fail
        (79, 80, 400),   # Systolic < Diastolic - should fail
        (81, 80, 201),   # Systolic > Diastolic - should pass
        (120, 80, 201),  # Normal valid case
    ])
    def test_systolic_greater_than_diastolic_validation(self, client, auth_headers, systolic, diastolic, expected_status):
        """Test systolic pressure must be greater than diastolic pressure (AC-3)"""
        access_headers = auth_headers['access']
        
        record_data = {
            'systolic': systolic,
            'diastolic': diastolic,
            'heart_rate': 72
        }
        
        response = client.post('/api/v1/health', json=record_data, headers=access_headers)
        assert response.status_code == expected_status

    # Generated by Copilot: AC-4 Heart rate optional test
    def test_heart_rate_optional(self, client, auth_headers):
        """Test that heart rate field is optional (AC-4)"""
        access_headers = auth_headers['access']
        
        # Test without heart_rate field
        record_data = {
            'systolic': 120,
            'diastolic': 80
        }
        
        response = client.post('/api/v1/health', json=record_data, headers=access_headers)
        assert response.status_code == 201
        
        data = response.get_json()
        assert data['heart_rate'] is None

    # Generated by Copilot: AC-5 Valid submission test
    def test_valid_submission_flow(self, client, auth_headers):
        """Test successful submission with all valid data (AC-5)"""
        access_headers = auth_headers['access']
        
        record_data = {
            'systolic': 135,
            'diastolic': 85,
            'heart_rate': 78,
            'tags': ['morning'],
            'note': 'Valid test record'
        }
        
        response = client.post('/api/v1/health', json=record_data, headers=access_headers)
        assert response.status_code == 201
        
        data = response.get_json()
        assert data['systolic'] == 135
        assert data['diastolic'] == 85
        assert data['heart_rate'] == 78

    # Generated by Copilot: AC-6 Backend API validation error responses
    @pytest.mark.parametrize("invalid_data,expected_message_contains", [
        ({'systolic': 25, 'diastolic': 80}, 'range'),
        ({'systolic': 260, 'diastolic': 80}, 'range'),
        ({'systolic': 120, 'diastolic': 25}, 'range'),
        ({'systolic': 120, 'diastolic': 260}, 'range'),
        ({'systolic': 80, 'diastolic': 85}, 'greater'),
        ({'systolic': 120, 'diastolic': 80, 'heart_rate': 25}, 'range'),
        ({'systolic': 120, 'diastolic': 80, 'heart_rate': 155}, 'range'),
        ({'systolic': 'invalid', 'diastolic': 80}, 'Invalid'),
        ({'systolic': 120, 'diastolic': 'invalid'}, 'Invalid'),
        ({'systolic': 120, 'diastolic': 80, 'heart_rate': 'invalid'}, 'Invalid'),
    ])
    def test_backend_validation_error_responses(self, client, auth_headers, invalid_data, expected_message_contains):
        """Test backend API returns proper 400 error responses (AC-6)"""
        access_headers = auth_headers['access']
        
        response = client.post('/api/v1/health', json=invalid_data, headers=access_headers)
        assert response.status_code == 400
        
        data = response.get_json()
        assert 'error' in data or 'message' in data
        error_text = str(data).lower()
        assert expected_message_contains.lower() in error_text

    # Generated by Copilot: Test update validation rules
    def test_update_record_validation(self, client, auth_headers):
        """Test update record applies same validation rules"""
        access_headers = auth_headers['access']
        
        # Create a valid record first
        record_data = {
            'systolic': 120,
            'diastolic': 80,
            'heart_rate': 72
        }
        
        create_response = client.post('/api/v1/health', json=record_data, headers=access_headers)
        record_id = create_response.get_json()['id']
        
        # Test invalid update - systolic out of range
        update_data = {'systolic': 25}
        response = client.put(f'/api/v1/health/{record_id}', json=update_data, headers=access_headers)
        assert response.status_code == 400
        
        # Test invalid update - systolic <= diastolic
        update_data = {'systolic': 75}  # Current diastolic is 80
        response = client.put(f'/api/v1/health/{record_id}', json=update_data, headers=access_headers)
        assert response.status_code == 400
        
        # Test valid update
        update_data = {'systolic': 130}
        response = client.put(f'/api/v1/health/{record_id}', json=update_data, headers=access_headers)
        assert response.status_code == 200

    # Generated by Copilot: Edge cases and boundary testing
    @pytest.mark.parametrize("test_case", [
        {'systolic': 30, 'diastolic': 30, 'desc': 'Equal values at minimum'},
        {'systolic': 250, 'diastolic': 250, 'desc': 'Equal values at maximum'},
        {'systolic': '', 'diastolic': 80, 'desc': 'Empty string systolic'},
        {'systolic': 120, 'diastolic': '', 'desc': 'Empty string diastolic'},
        {'systolic': None, 'diastolic': 80, 'desc': 'None systolic'},
        {'systolic': 120, 'diastolic': None, 'desc': 'None diastolic'},
    ])
    def test_edge_cases_and_boundary_values(self, client, auth_headers, test_case):
        """Test edge cases and boundary values"""
        access_headers = auth_headers['access']
        
        record_data = {
            'systolic': test_case['systolic'],
            'diastolic': test_case['diastolic']
        }
        
        response = client.post('/api/v1/health', json=record_data, headers=access_headers)
        # All these edge cases should fail
        assert response.status_code == 400
    
    def test_create_health_record_unauthorized(self, client):
        """Test creating health record without authorization"""
        record_data = {
            'systolic': 120,
            'diastolic': 80,
            'heart_rate': 72
        }
        
        response = client.post('/api/v1/health', json=record_data)
        assert response.status_code == 401
    
    def test_create_health_record_missing_fields(self, client, auth_headers):
        """Test creating health record with missing required fields"""
        access_headers = auth_headers['access']
        
        record_data = {
            'systolic': 120
            # Missing diastolic and heart_rate
        }
        
        response = client.post('/api/v1/health', json=record_data, headers=access_headers)
        assert response.status_code == 400
    
    def test_list_health_records(self, client, auth_headers):
        """Test listing health records"""
        access_headers = auth_headers['access']
        
        # Create a few records first
        records = [
            {'systolic': 120, 'diastolic': 80, 'heart_rate': 72, 'tags': ['morning']},
            {'systolic': 130, 'diastolic': 85, 'heart_rate': 75, 'tags': ['evening']},
            {'systolic': 125, 'diastolic': 82, 'heart_rate': 70, 'tags': ['afternoon']}
        ]
        
        for record in records:
            client.post('/api/v1/health', json=record, headers=access_headers)
        
        # Test listing all records
        response = client.get('/api/v1/health', headers=access_headers)
        assert response.status_code == 200
        
        data = response.get_json()
        assert 'records' in data
        assert 'pagination' in data
        assert len(data['records']) == 3
    
    def test_list_health_records_pagination(self, client, auth_headers):
        """Test health records pagination"""
        access_headers = auth_headers['access']
        
        # Create multiple records
        for i in range(25):
            record = {
                'systolic': 120 + i,
                'diastolic': 80,
                'heart_rate': 72,
                'tags': [f'test{i}']
            }
            client.post('/api/v1/health', json=record, headers=access_headers)
        
        # Test first page
        response = client.get('/api/v1/health?page=1&size=10', headers=access_headers)
        assert response.status_code == 200
        
        data = response.get_json()
        assert len(data['records']) == 10
        assert data['pagination']['page'] == 1
        assert data['pagination']['size'] == 10
        assert data['pagination']['total'] == 25
        assert data['pagination']['pages'] == 3
        
        # Test second page
        response = client.get('/api/v1/health?page=2&size=10', headers=access_headers)
        assert response.status_code == 200
        
        data = response.get_json()
        assert len(data['records']) == 10
        assert data['pagination']['page'] == 2
    
    def test_list_health_records_filter_by_tags(self, client, auth_headers):
        """Test filtering health records by tags"""
        access_headers = auth_headers['access']
        
        # Create records with different tags
        records = [
            {'systolic': 120, 'diastolic': 80, 'heart_rate': 72, 'tags': ['morning', 'home']},
            {'systolic': 130, 'diastolic': 85, 'heart_rate': 75, 'tags': ['evening', 'work']},
            {'systolic': 125, 'diastolic': 82, 'heart_rate': 70, 'tags': ['morning', 'gym']}
        ]
        
        for record in records:
            client.post('/api/v1/health', json=record, headers=access_headers)
        
        # Filter by 'morning' tag
        response = client.get('/api/v1/health?tags=morning', headers=access_headers)
        assert response.status_code == 200
        
        data = response.get_json()
        assert len(data['records']) == 2
        for record in data['records']:
            assert 'morning' in record['tags']

        # Generated by Zhuang: Filter by multiple tags should use OR semantics
        response = client.get('/api/v1/health?tags=morning,work', headers=access_headers)
        assert response.status_code == 200
        data = response.get_json()
        # morning matches 2, work matches 1, but one record may overlap; in our dataset it's 3 total
        assert len(data['records']) == 3
        # Ensure each record has at least one of the requested tags
        for record in data['records']:
            assert any(t in record['tags'] for t in ['morning', 'work'])
    
    def test_get_health_record(self, client, auth_headers):
        """Test getting a specific health record"""
        access_headers = auth_headers['access']
        
        # Create a record first
        record_data = {
            'systolic': 120,
            'diastolic': 80,
            'heart_rate': 72,
            'note': 'Test record'
        }
        
        create_response = client.post('/api/v1/health', json=record_data, headers=access_headers)
        record_id = create_response.get_json()['id']
        
        # Get the specific record
        response = client.get(f'/api/v1/health/{record_id}', headers=access_headers)
        assert response.status_code == 200
        
        data = response.get_json()
        assert data['id'] == record_id
        assert data['systolic'] == 120
        assert data['note'] == 'Test record'
    
    def test_get_health_record_not_found(self, client, auth_headers):
        """Test getting non-existent health record"""
        access_headers = auth_headers['access']
        
        response = client.get('/api/v1/health/999', headers=access_headers)
        assert response.status_code == 404
    
    def test_update_health_record(self, client, auth_headers):
        """Test updating a health record"""
        access_headers = auth_headers['access']
        
        # Create a record first
        record_data = {
            'systolic': 120,
            'diastolic': 80,
            'heart_rate': 72,
            'note': 'Original note'
        }
        
        create_response = client.post('/api/v1/health', json=record_data, headers=access_headers)
        record_id = create_response.get_json()['id']
        
        # Update the record
        update_data = {
            'systolic': 125,
            'note': 'Updated note'
        }
        
        response = client.put(f'/api/v1/health/{record_id}', json=update_data, headers=access_headers)
        assert response.status_code == 200
        
        data = response.get_json()
        assert data['systolic'] == 125
        assert data['diastolic'] == 80  # Should remain unchanged
        assert data['note'] == 'Updated note'
    
    def test_delete_health_record(self, client, auth_headers):
        """Test deleting a health record"""
        access_headers = auth_headers['access']
        
        # Create a record first
        record_data = {
            'systolic': 120,
            'diastolic': 80,
            'heart_rate': 72
        }
        
        create_response = client.post('/api/v1/health', json=record_data, headers=access_headers)
        record_id = create_response.get_json()['id']
        
        # Delete the record
        response = client.delete(f'/api/v1/health/{record_id}', headers=access_headers)
        assert response.status_code == 200
        
        # Verify it's deleted
        get_response = client.get(f'/api/v1/health/{record_id}', headers=access_headers)
        assert get_response.status_code == 404
    
    def test_health_record_ownership(self, client, auth_headers):
        """Test that users can only access their own health records"""
        access_headers = auth_headers['access']
        
        # Create a record with first user
        record_data = {
            'systolic': 120,
            'diastolic': 80,
            'heart_rate': 72
        }
        
        create_response = client.post('/api/v1/health', json=record_data, headers=access_headers)
        record_id = create_response.get_json()['id']
        
        # Create a second user
        client.post('/api/v1/auth/register', json={
            'username': 'user2',
            'email': 'user2@example.com',
            'password': 'password123'
        })
        
        # Login as second user
        login_response = client.post('/api/v1/auth/login', json={
            'email': 'user2@example.com',
            'password': 'password123'
        })
        
        user2_token = login_response.get_json()['access_token']
        user2_headers = {'Authorization': f'Bearer {user2_token}'}
        
        # Second user should not be able to access first user's record
        response = client.get(f'/api/v1/health/{record_id}', headers=user2_headers)
        assert response.status_code == 404  # Or 403, depending on implementation
