"""
Test cases for health record endpoints. Generated by Zhuang
"""
import json
import pytest
from datetime import datetime


class TestHealthEndpoints:
    """Test health record related endpoints"""
    
    def test_create_health_record(self, client, auth_headers):
        """Test creating a new health record"""
        access_headers = auth_headers['access']
        
        record_data = {
            'systolic': 120,
            'diastolic': 80,
            'heart_rate': 72,
            'timestamp': '2025-08-22T10:00:00Z',
            'tags': ['morning', 'resting'],
            'note': 'Morning measurement'
        }
        
        response = client.post('/api/v1/health', json=record_data, headers=access_headers)
        assert response.status_code == 201
        
        data = response.get_json()
        assert data['systolic'] == 120
        assert data['diastolic'] == 80
        assert data['heart_rate'] == 72
        assert data['tags'] == ['morning', 'resting']
        assert data['note'] == 'Morning measurement'
        assert 'id' in data
        assert 'created_at' in data
    
    def test_create_health_record_unauthorized(self, client):
        """Test creating health record without authorization"""
        record_data = {
            'systolic': 120,
            'diastolic': 80,
            'heart_rate': 72
        }
        
        response = client.post('/api/v1/health', json=record_data)
        assert response.status_code == 401
    
    def test_create_health_record_missing_fields(self, client, auth_headers):
        """Test creating health record with missing required fields"""
        access_headers = auth_headers['access']
        
        record_data = {
            'systolic': 120
            # Missing diastolic and heart_rate
        }
        
        response = client.post('/api/v1/health', json=record_data, headers=access_headers)
        assert response.status_code == 400
    
    def test_list_health_records(self, client, auth_headers):
        """Test listing health records"""
        access_headers = auth_headers['access']
        
        # Create a few records first
        records = [
            {'systolic': 120, 'diastolic': 80, 'heart_rate': 72, 'tags': ['morning']},
            {'systolic': 130, 'diastolic': 85, 'heart_rate': 75, 'tags': ['evening']},
            {'systolic': 125, 'diastolic': 82, 'heart_rate': 70, 'tags': ['afternoon']}
        ]
        
        for record in records:
            client.post('/api/v1/health', json=record, headers=access_headers)
        
        # Test listing all records
        response = client.get('/api/v1/health', headers=access_headers)
        assert response.status_code == 200
        
        data = response.get_json()
        assert 'records' in data
        assert 'pagination' in data
        assert len(data['records']) == 3
    
    def test_list_health_records_pagination(self, client, auth_headers):
        """Test health records pagination"""
        access_headers = auth_headers['access']
        
        # Create multiple records
        for i in range(25):
            record = {
                'systolic': 120 + i,
                'diastolic': 80,
                'heart_rate': 72,
                'tags': [f'test{i}']
            }
            client.post('/api/v1/health', json=record, headers=access_headers)
        
        # Test first page
        response = client.get('/api/v1/health?page=1&size=10', headers=access_headers)
        assert response.status_code == 200
        
        data = response.get_json()
        assert len(data['records']) == 10
        assert data['pagination']['page'] == 1
        assert data['pagination']['size'] == 10
        assert data['pagination']['total'] == 25
        assert data['pagination']['pages'] == 3
        
        # Test second page
        response = client.get('/api/v1/health?page=2&size=10', headers=access_headers)
        assert response.status_code == 200
        
        data = response.get_json()
        assert len(data['records']) == 10
        assert data['pagination']['page'] == 2
    
    def test_list_health_records_filter_by_tags(self, client, auth_headers):
        """Test filtering health records by tags"""
        access_headers = auth_headers['access']
        
        # Create records with different tags
        records = [
            {'systolic': 120, 'diastolic': 80, 'heart_rate': 72, 'tags': ['morning', 'home']},
            {'systolic': 130, 'diastolic': 85, 'heart_rate': 75, 'tags': ['evening', 'work']},
            {'systolic': 125, 'diastolic': 82, 'heart_rate': 70, 'tags': ['morning', 'gym']}
        ]
        
        for record in records:
            client.post('/api/v1/health', json=record, headers=access_headers)
        
        # Filter by 'morning' tag
        response = client.get('/api/v1/health?tags=morning', headers=access_headers)
        assert response.status_code == 200
        
        data = response.get_json()
        assert len(data['records']) == 2
        for record in data['records']:
            assert 'morning' in record['tags']

        # Generated by Zhuang: Filter by multiple tags should use OR semantics
        response = client.get('/api/v1/health?tags=morning,work', headers=access_headers)
        assert response.status_code == 200
        data = response.get_json()
        # morning matches 2, work matches 1, but one record may overlap; in our dataset it's 3 total
        assert len(data['records']) == 3
        # Ensure each record has at least one of the requested tags
        for record in data['records']:
            assert any(t in record['tags'] for t in ['morning', 'work'])
    
    def test_get_health_record(self, client, auth_headers):
        """Test getting a specific health record"""
        access_headers = auth_headers['access']
        
        # Create a record first
        record_data = {
            'systolic': 120,
            'diastolic': 80,
            'heart_rate': 72,
            'note': 'Test record'
        }
        
        create_response = client.post('/api/v1/health', json=record_data, headers=access_headers)
        record_id = create_response.get_json()['id']
        
        # Get the specific record
        response = client.get(f'/api/v1/health/{record_id}', headers=access_headers)
        assert response.status_code == 200
        
        data = response.get_json()
        assert data['id'] == record_id
        assert data['systolic'] == 120
        assert data['note'] == 'Test record'
    
    def test_get_health_record_not_found(self, client, auth_headers):
        """Test getting non-existent health record"""
        access_headers = auth_headers['access']
        
        response = client.get('/api/v1/health/999', headers=access_headers)
        assert response.status_code == 404
    
    def test_update_health_record(self, client, auth_headers):
        """Test updating a health record"""
        access_headers = auth_headers['access']
        
        # Create a record first
        record_data = {
            'systolic': 120,
            'diastolic': 80,
            'heart_rate': 72,
            'note': 'Original note'
        }
        
        create_response = client.post('/api/v1/health', json=record_data, headers=access_headers)
        record_id = create_response.get_json()['id']
        
        # Update the record
        update_data = {
            'systolic': 125,
            'note': 'Updated note'
        }
        
        response = client.put(f'/api/v1/health/{record_id}', json=update_data, headers=access_headers)
        assert response.status_code == 200
        
        data = response.get_json()
        assert data['systolic'] == 125
        assert data['diastolic'] == 80  # Should remain unchanged
        assert data['note'] == 'Updated note'
    
    def test_delete_health_record(self, client, auth_headers):
        """Test deleting a health record"""
        access_headers = auth_headers['access']
        
        # Create a record first
        record_data = {
            'systolic': 120,
            'diastolic': 80,
            'heart_rate': 72
        }
        
        create_response = client.post('/api/v1/health', json=record_data, headers=access_headers)
        record_id = create_response.get_json()['id']
        
        # Delete the record
        response = client.delete(f'/api/v1/health/{record_id}', headers=access_headers)
        assert response.status_code == 200
        
        # Verify it's deleted
        get_response = client.get(f'/api/v1/health/{record_id}', headers=access_headers)
        assert get_response.status_code == 404
    
    def test_health_record_ownership(self, client, auth_headers):
        """Test that users can only access their own health records"""
        access_headers = auth_headers['access']
        
        # Create a record with first user
        record_data = {
            'systolic': 120,
            'diastolic': 80,
            'heart_rate': 72
        }
        
        create_response = client.post('/api/v1/health', json=record_data, headers=access_headers)
        record_id = create_response.get_json()['id']
        
        # Create a second user
        client.post('/api/v1/auth/register', json={
            'username': 'user2',
            'email': 'user2@example.com',
            'password': 'password123'
        })
        
        # Login as second user
        login_response = client.post('/api/v1/auth/login', json={
            'email': 'user2@example.com',
            'password': 'password123'
        })
        
        user2_token = login_response.get_json()['access_token']
        user2_headers = {'Authorization': f'Bearer {user2_token}'}
        
        # Second user should not be able to access first user's record
        response = client.get(f'/api/v1/health/{record_id}', headers=user2_headers)
        assert response.status_code == 404  # Or 403, depending on implementation

    # ---------------- New validation tests (Generated by Copilot) ----------------
    @pytest.mark.parametrize("systolic,diastolic", [
        (29, 80),  # systolic below range
        (251, 80), # systolic above range
        (120, 29), # diastolic below range
        (120, 251) # diastolic above range
    ])
    def test_create_invalid_bp_range(self, client, auth_headers, systolic, diastolic):
        access_headers = auth_headers['access']
        payload = {"systolic": systolic, "diastolic": diastolic}
        resp = client.post('/api/v1/health', json=payload, headers=access_headers)
        assert resp.status_code == 400
        msg = resp.get_json().get('message')
        assert '30-250' in msg

    def test_create_invalid_relation(self, client, auth_headers):
        access_headers = auth_headers['access']
        payload = {"systolic": 120, "diastolic": 120}
        resp = client.post('/api/v1/health', json=payload, headers=access_headers)
        assert resp.status_code == 400
        assert 'greater' in resp.get_json().get('message', '').lower()

    @pytest.mark.parametrize("heart_rate", [29, 151])
    def test_create_invalid_heart_rate_range(self, client, auth_headers, heart_rate):
        access_headers = auth_headers['access']
        payload = {"systolic": 120, "diastolic": 80, "heart_rate": heart_rate}
        resp = client.post('/api/v1/health', json=payload, headers=access_headers)
        assert resp.status_code == 400
        assert '30-150' in resp.get_json().get('message')

    def test_create_heart_rate_optional(self, client, auth_headers):
        access_headers = auth_headers['access']
        payload = {"systolic": 130, "diastolic": 85}
        resp = client.post('/api/v1/health', json=payload, headers=access_headers)
        assert resp.status_code == 201
        data = resp.get_json()
        assert data['heart_rate'] is None or data['heart_rate'] == None  # explicit None

    @pytest.mark.parametrize("field,value", [
        ("systolic", "abc"),
        ("diastolic", "abc"),
        ("heart_rate", "xyz")
    ])
    def test_create_invalid_non_numeric(self, client, auth_headers, field, value):
        access_headers = auth_headers['access']
        payload = {"systolic": 120, "diastolic": 80}
        payload[field] = value
        resp = client.post('/api/v1/health', json=payload, headers=access_headers)
        assert resp.status_code == 400
        assert 'Invalid' in resp.get_json().get('message', '')

    def test_update_invalid_relation(self, client, auth_headers):
        access_headers = auth_headers['access']
        # Create valid record
        create = client.post('/api/v1/health', json={"systolic": 140, "diastolic": 80}, headers=access_headers)
        rid = create.get_json()['id']
        # Update only diastolic to invalid relation
        upd = client.put(f'/api/v1/health/{rid}', json={"diastolic": 140}, headers=access_headers)
        assert upd.status_code == 400
        assert 'Systolic' in upd.get_json().get('message', '')

    def test_update_heart_rate_optional_and_range(self, client, auth_headers):
        access_headers = auth_headers['access']
        create = client.post('/api/v1/health', json={"systolic": 120, "diastolic": 80, "heart_rate": 90}, headers=access_headers)
        rid = create.get_json()['id']
        # Clear heart rate
        upd = client.put(f'/api/v1/health/{rid}', json={"heart_rate": ""}, headers=access_headers)
        assert upd.status_code == 200
        # Set out of range
        upd2 = client.put(f'/api/v1/health/{rid}', json={"heart_rate": 151}, headers=access_headers)
        assert upd2.status_code == 400
        assert '30-150' in upd2.get_json().get('message', '')
