"""
Tests for WeChat mini-app integration. Generated by Copilot
"""
import pytest
from unittest.mock import patch, MagicMock
from src.models import User
from src.extensions import db


class TestWeChatAuth:
    """Tests for WeChat authentication endpoints"""

    @patch('src.manager.wechat_manager.requests.get')
    def test_wechat_login_success(self, mock_get, client, app):
        """Test successful WeChat login with new user"""
        # Mock WeChat API response
        mock_response = MagicMock()
        mock_response.json.return_value = {
            "openid": "test_openid_123",
            "session_key": "test_session_key",
            "unionid": "test_unionid_456"
        }
        mock_response.raise_for_status = MagicMock()
        mock_get.return_value = mock_response
        
        # Configure WeChat credentials
        app.config['WECHAT_APP_ID'] = 'test_app_id'
        app.config['WECHAT_APP_SECRET'] = 'test_app_secret'
        
        response = client.post('/api/v1/wechat/auth/login', json={
            'code': 'test_js_code',
            'userInfo': {
                'nickName': 'TestUser',
                'avatarUrl': 'https://example.com/avatar.jpg'
            }
        })
        
        assert response.status_code == 200
        data = response.get_json()
        assert 'access_token' in data
        assert 'refresh_token' in data
        assert data['token_type'] == 'Bearer'
        assert data['expires_in'] == 1800
        assert 'user' in data
        assert data['user']['username'] == 'TestUser'
        assert data['user']['is_wechat_temp'] is True

    @patch('src.manager.wechat_manager.requests.get')
    def test_wechat_login_existing_user(self, mock_get, client, app):
        """Test WeChat login with existing user"""
        with app.app_context():
            # Create existing user with WeChat binding
            user = User(
                username='ExistingUser',
                email='existing@example.com',
                password_hash='dummy_hash',
                wechat_openid='test_openid_123',
                wechat_session_key='old_session_key'
            )
            db.session.add(user)
            db.session.commit()
            user_id = user.id
        
        # Mock WeChat API response
        mock_response = MagicMock()
        mock_response.json.return_value = {
            "openid": "test_openid_123",
            "session_key": "new_session_key"
        }
        mock_response.raise_for_status = MagicMock()
        mock_get.return_value = mock_response
        
        app.config['WECHAT_APP_ID'] = 'test_app_id'
        app.config['WECHAT_APP_SECRET'] = 'test_app_secret'
        
        response = client.post('/api/v1/wechat/auth/login', json={
            'code': 'test_js_code'
        })
        
        assert response.status_code == 200
        data = response.get_json()
        assert 'access_token' in data
        assert data['user']['username'] == 'ExistingUser'
        
        # Verify session key was updated
        with app.app_context():
            updated_user = User.query.get(user_id)
            assert updated_user.wechat_session_key == 'new_session_key'

    def test_wechat_login_missing_code(self, client, app):
        """Test WeChat login without code parameter"""
        app.config['WECHAT_APP_ID'] = 'test_app_id'
        app.config['WECHAT_APP_SECRET'] = 'test_app_secret'
        
        response = client.post('/api/v1/wechat/auth/login', json={})
        
        assert response.status_code == 400
        data = response.get_json()
        assert 'code' in data or 'message' in data

    @patch('src.manager.wechat_manager.requests.get')
    def test_wechat_login_invalid_code(self, mock_get, client, app):
        """Test WeChat login with invalid code"""
        # Mock WeChat API error response
        mock_response = MagicMock()
        mock_response.json.return_value = {
            "errcode": 40029,
            "errmsg": "invalid code"
        }
        mock_response.raise_for_status = MagicMock()
        mock_get.return_value = mock_response
        
        app.config['WECHAT_APP_ID'] = 'test_app_id'
        app.config['WECHAT_APP_SECRET'] = 'test_app_secret'
        
        response = client.post('/api/v1/wechat/auth/login', json={
            'code': 'invalid_code'
        })
        
        assert response.status_code == 401
        data = response.get_json()
        assert 'code' in data or 'message' in data

    def test_wechat_login_no_config(self, client):
        """Test WeChat login without configured credentials"""
        response = client.post('/api/v1/wechat/auth/login', json={
            'code': 'test_js_code'
        })
        
        assert response.status_code == 500  # Should fail due to missing config


class TestWeChatBinding:
    """Tests for WeChat account binding"""

    @patch('src.manager.wechat_manager.requests.get')
    def test_bind_wechat_to_user(self, mock_get, client, app, auth_headers):
        """Test binding WeChat account to existing user"""
        # Mock WeChat API response
        mock_response = MagicMock()
        mock_response.json.return_value = {
            "openid": "new_openid_789",
            "session_key": "new_session_key"
        }
        mock_response.raise_for_status = MagicMock()
        mock_get.return_value = mock_response
        
        app.config['WECHAT_APP_ID'] = 'test_app_id'
        app.config['WECHAT_APP_SECRET'] = 'test_app_secret'
        
        response = client.post('/api/v1/wechat/auth/bind',
                              json={'code': 'test_js_code'},
                              headers=auth_headers['access'])
        
        assert response.status_code == 200
        data = response.get_json()
        assert data['message'] == 'WeChat account bound successfully'

    @patch('src.manager.wechat_manager.requests.get')
    def test_bind_wechat_already_bound(self, mock_get, client, app, auth_headers):
        """Test binding WeChat account that's already bound to another user"""
        with app.app_context():
            # Create another user with the same openid
            other_user = User(
                username='OtherUser',
                email='other@example.com',
                password_hash='dummy_hash',
                wechat_openid='occupied_openid'
            )
            db.session.add(other_user)
            db.session.commit()
        
        # Mock WeChat API response with occupied openid
        mock_response = MagicMock()
        mock_response.json.return_value = {
            "openid": "occupied_openid",
            "session_key": "test_session_key"
        }
        mock_response.raise_for_status = MagicMock()
        mock_get.return_value = mock_response
        
        app.config['WECHAT_APP_ID'] = 'test_app_id'
        app.config['WECHAT_APP_SECRET'] = 'test_app_secret'
        
        response = client.post('/api/v1/wechat/auth/bind',
                              json={'code': 'test_js_code'},
                              headers=auth_headers['access'])
        
        assert response.status_code == 409
        data = response.get_json()
        assert 'code' in data or 'message' in data

    def test_unbind_wechat(self, client, app, auth_headers):
        """Test unbinding WeChat account"""
        # Get the test user and bind WeChat first
        with app.app_context():
            test_user = User.query.filter_by(email='test@example.com').first()
            test_user.wechat_openid = 'test_openid'
            test_user.wechat_session_key = 'test_session_key'
            db.session.commit()
        
        response = client.post('/api/v1/wechat/auth/unbind',
                              headers=auth_headers['access'])
        
        assert response.status_code == 200
        data = response.get_json()
        assert data['message'] == 'WeChat account unbound successfully'
        
        # Verify WeChat data was cleared
        with app.app_context():
            updated_user = User.query.filter_by(email='test@example.com').first()
            assert updated_user.wechat_openid is None
            assert updated_user.wechat_session_key is None


class TestWeChatUserManagement:
    """Tests for WeChat user management"""

    def test_update_email_for_wechat_user(self, client, auth_headers):
        """Test updating email for WeChat-only user"""
        response = client.post('/api/v1/wechat/auth/update-email',
                              json={
                                  'email': 'newemail@example.com',
                                  'password': 'newpassword123'
                              },
                              headers=auth_headers['access'])
        
        assert response.status_code == 200
        data = response.get_json()
        assert data['message'] == 'Email updated successfully'
        assert data['user']['email'] == 'newemail@example.com'

    def test_update_email_duplicate(self, client, app, auth_headers):
        """Test updating email to one that already exists"""
        with app.app_context():
            # Create another user with the target email
            other_user = User(
                username='OtherUser',
                email='occupied@example.com',
                password_hash='dummy_hash'
            )
            db.session.add(other_user)
            db.session.commit()
        
        response = client.post('/api/v1/wechat/auth/update-email',
                              json={'email': 'occupied@example.com'},
                              headers=auth_headers['access'])
        
        assert response.status_code == 409
        data = response.get_json()
        assert 'code' in data or 'message' in data

    def test_update_email_missing(self, client, auth_headers):
        """Test updating email without providing new email"""
        response = client.post('/api/v1/wechat/auth/update-email',
                              json={},
                              headers=auth_headers['access'])
        
        assert response.status_code == 400
        data = response.get_json()
        assert 'code' in data or 'message' in data
