"""
Unit tests for Medical History Attachment API. Generated by Copilot
"""
from io import BytesIO

BASE = "/api/v1/medical-history"


def _register_and_login(client, suffix: str = "") -> dict:
    client.post(
        "/api/v1/auth/register",
        json={
            "username": f"user_attach{suffix}",
            "email": f"user_attach{suffix}@example.com",
            "password": "password123",
            "age": 30,
            "gender": "male",
            "weight": 70,
        },
    )
    resp = client.post(
        "/api/v1/auth/login",
        json={"email": f"user_attach{suffix}@example.com", "password": "password123"},
    )
    data = resp.get_json()
    return {"Authorization": f"Bearer {data['access_token']}"}


def _get_self_member_id(client, headers: dict) -> int:
    resp = client.get("/api/v1/members", headers=headers)
    members = resp.get_json()["members"]
    return members[0]["id"]


def _create_history(client, headers, member_id):
    resp = client.post(
        BASE,
        json={
            "member_id": member_id,
            "disease_name": "Hypertension",
            "onset_date": "2020-01-15",
            "is_ongoing": True,
            "is_on_medication": False,
        },
        headers=headers,
    )
    return resp.get_json()["id"]


def _upload_attachment(client, headers, history_id, name="report.pdf", content=b"pdf-bytes"):
    return client.post(
        f"{BASE}/{history_id}/attachments",
        data={"file": (BytesIO(content), name)},
        headers=headers,
        content_type="multipart/form-data",
    )


class TestMedicalHistoryAttachmentApi:
    def test_upload_list_download_delete_success(self, client):
        headers = _register_and_login(client, "1")
        member_id = _get_self_member_id(client, headers)
        history_id = _create_history(client, headers, member_id)

        upload_resp = _upload_attachment(client, headers, history_id)
        assert upload_resp.status_code == 201
        item = upload_resp.get_json()
        attachment_id = item["id"]
        assert item["file_name"] == "report.pdf"

        list_resp = client.get(f"{BASE}/{history_id}/attachments?page=1&size=10", headers=headers)
        assert list_resp.status_code == 200
        assert list_resp.get_json()["pagination"]["total"] == 1

        dl_resp = client.get(f"{BASE}/{history_id}/attachments/{attachment_id}/download", headers=headers)
        assert dl_resp.status_code == 200
        assert b"attachment" in dl_resp.headers.get("Content-Disposition", "").encode("utf-8")
        assert dl_resp.data == b"pdf-bytes"

        del_resp = client.delete(f"{BASE}/{history_id}/attachments/{attachment_id}", headers=headers)
        assert del_resp.status_code == 200

        missing_resp = client.get(f"{BASE}/{history_id}/attachments/{attachment_id}/download", headers=headers)
        assert missing_resp.status_code == 404

    def test_upload_invalid_extension(self, client):
        headers = _register_and_login(client, "2")
        member_id = _get_self_member_id(client, headers)
        history_id = _create_history(client, headers, member_id)
        resp = _upload_attachment(client, headers, history_id, name="bad.exe", content=b"abc")
        assert resp.status_code == 400

    def test_upload_size_exceeded(self, client):
        headers = _register_and_login(client, "3")
        member_id = _get_self_member_id(client, headers)
        history_id = _create_history(client, headers, member_id)
        huge = b"a" * (21 * 1024 * 1024)
        resp = _upload_attachment(client, headers, history_id, name="big.pdf", content=huge)
        assert resp.status_code == 400

    def test_forbidden_cross_user_access(self, client):
        h1 = _register_and_login(client, "4a")
        h2 = _register_and_login(client, "4b")
        member_id = _get_self_member_id(client, h1)
        history_id = _create_history(client, h1, member_id)
        upload_resp = _upload_attachment(client, h1, history_id, "x.pdf", b"x")
        attachment_id = upload_resp.get_json()["id"]

        list_resp = client.get(f"{BASE}/{history_id}/attachments", headers=h2)
        assert list_resp.status_code == 404

        dl_resp = client.get(f"{BASE}/{history_id}/attachments/{attachment_id}/download", headers=h2)
        assert dl_resp.status_code == 404

        del_resp = client.delete(f"{BASE}/{history_id}/attachments/{attachment_id}", headers=h2)
        assert del_resp.status_code == 404
