"""
Test cases for import manager. Generated by Copilot
"""
import pytest
import pandas as pd
from io import BytesIO
from datetime import datetime
from src.manager.import_manager import ImportManager
from src.models import HealthRecord, RecordSubject, Member, Household, ImportLog
from src.extensions import db


@pytest.fixture
def import_manager():
    """Create an ImportManager instance."""
    return ImportManager()


@pytest.fixture
def setup_user_with_members(app):
    """Create a user with household and members."""
    from src.models import User
    from src.security import hash_password
    
    # Create user
    user = User(
        username='testuser',
        email='test@example.com',
        password_hash=hash_password('password123'),
        role='USER',
        age=30
    )
    db.session.add(user)
    db.session.flush()
    
    # Create household
    household = Household(
        owner_user_id=user.id,
        name='Test Household'
    )
    db.session.add(household)
    db.session.flush()
    
    # Create members
    self_member = Member(
        household_id=household.id,
        full_name='Self',
        status='active'
    )
    db.session.add(self_member)
    
    father = Member(
        household_id=household.id,
        full_name='父亲',
        gender='male',
        age=60,
        status='active'
    )
    db.session.add(father)
    
    mother = Member(
        household_id=household.id,
        full_name='母亲',
        gender='female',
        age=58,
        status='active'
    )
    db.session.add(mother)
    
    db.session.commit()
    
    return {
        'user': user,
        'household': household,
        'members': {
            'self': self_member,
            'father': father,
            'mother': mother
        }
    }


class TestImportManagerParseFile:
    """Test file parsing functionality"""
    
    def test_parse_excel_file(self, app, import_manager):
        """Test parsing Excel file"""
        with app.app_context():
            # Create sample Excel data
            data = {
                '成员名称': ['Self', '父亲'],
                '测量时间': ['2025-12-19 08:30:00', '2025-12-19 09:00:00'],
                '收缩压': [120, 130],
                '舒张压': [80, 85],
                '心率': [72, 75],
                '标签': ['晨起', '餐后'],
                '备注': ['正常', '血压稍高']
            }
            df = pd.DataFrame(data)
            
            # Save to BytesIO
            excel_file = BytesIO()
            df.to_excel(excel_file, index=False, engine='openpyxl')
            excel_file.seek(0)
            
            # Parse file
            rows = import_manager.parse_file(excel_file, '.xlsx')
            
            assert len(rows) == 2
            assert rows[0]['成员名称'] == 'Self'
            assert rows[0]['收缩压'] == 120
    
    def test_parse_csv_file(self, app, import_manager):
        """Test parsing CSV file"""
        with app.app_context():
            # Create sample CSV data
            csv_content = """成员名称,测量时间,收缩压,舒张压,心率,标签,备注
Self,2025-12-19 08:30:00,120,80,72,晨起,正常
父亲,2025-12-19 09:00:00,130,85,75,餐后,血压稍高"""
            
            csv_file = BytesIO(csv_content.encode('utf-8-sig'))
            
            # Parse file
            rows = import_manager.parse_file(csv_file, '.csv')
            
            assert len(rows) == 2
            assert rows[0]['成员名称'] == 'Self'
            assert rows[1]['成员名称'] == '父亲'
    
    def test_parse_empty_file(self, app, import_manager):
        """Test parsing empty file"""
        with app.app_context():
            # Create empty CSV
            csv_content = "成员名称,测量时间,收缩压,舒张压,心率,标签,备注\n"
            csv_file = BytesIO(csv_content.encode('utf-8-sig'))
            
            # Parse file
            rows = import_manager.parse_file(csv_file, '.csv')
            
            assert len(rows) == 0
    
    def test_parse_unsupported_format(self, app, import_manager):
        """Test parsing unsupported file format"""
        with app.app_context():
            file = BytesIO(b"some content")
            
            with pytest.raises(ValueError, match="Unsupported file format"):
                import_manager.parse_file(file, '.txt')


class TestImportManagerValidateRow:
    """Test row validation functionality"""
    
    def test_validate_valid_row(self, app, import_manager, setup_user_with_members):
        """Test validating a valid row"""
        with app.app_context():
            data = setup_user_with_members
            row = {
                '成员名称': 'Self',
                '测量时间': '2025-12-19 08:30:00',
                '收缩压': 120,
                '舒张压': 80,
                '心率': 72,
                '标签': '晨起;空腹',
                '备注': '正常'
            }
            
            is_valid, cleaned, error = import_manager.validate_row(row, data['user'].id, 1)
            
            assert is_valid is True
            assert cleaned['systolic'] == 120
            assert cleaned['diastolic'] == 80
            assert cleaned['heart_rate'] == 72
            assert cleaned['tags'] == ['晨起', '空腹']
            assert cleaned['note'] == '正常'
            assert error is None
    
    def test_validate_missing_member_name(self, app, import_manager, setup_user_with_members):
        """Test validation with missing member name"""
        with app.app_context():
            data = setup_user_with_members
            row = {
                '测量时间': '2025-12-19 08:30:00',
                '收缩压': 120,
                '舒张压': 80
            }
            
            is_valid, cleaned, error = import_manager.validate_row(row, data['user'].id, 1)
            
            assert is_valid is False
            assert "成员名称为必填项" in error
    
    def test_validate_nonexistent_member(self, app, import_manager, setup_user_with_members):
        """Test validation with non-existent member name"""
        with app.app_context():
            data = setup_user_with_members
            row = {
                '成员名称': '不存在的成员',
                '测量时间': '2025-12-19 08:30:00',
                '收缩压': 120,
                '舒张压': 80
            }
            
            is_valid, cleaned, error = import_manager.validate_row(row, data['user'].id, 1)
            
            assert is_valid is False
            assert "不存在" in error
    
    def test_validate_self_variations(self, app, import_manager, setup_user_with_members):
        """Test validation with Self/自己/本人 variations"""
        with app.app_context():
            data = setup_user_with_members
            variations = ['Self', 'self', '自己', '本人']
            
            for variation in variations:
                row = {
                    '成员名称': variation,
                    '测量时间': '2025-12-19 08:30:00',
                    '收缩压': 120,
                    '舒张压': 80
                }
                
                is_valid, cleaned, error = import_manager.validate_row(row, data['user'].id, 1)
                
                assert is_valid is True, f"Failed for variation: {variation}"
                assert cleaned['member_id'] == data['members']['self'].id
    
    def test_validate_invalid_timestamp(self, app, import_manager, setup_user_with_members):
        """Test validation with invalid timestamp"""
        with app.app_context():
            data = setup_user_with_members
            row = {
                '成员名称': 'Self',
                '测量时间': 'invalid-date',
                '收缩压': 120,
                '舒张压': 80
            }
            
            is_valid, cleaned, error = import_manager.validate_row(row, data['user'].id, 1)
            
            assert is_valid is False
            assert "时间格式无效" in error
    
    def test_validate_blood_pressure_out_of_range(self, app, import_manager, setup_user_with_members):
        """Test validation with blood pressure out of range"""
        with app.app_context():
            data = setup_user_with_members
            
            # Systolic too low
            row = {
                '成员名称': 'Self',
                '测量时间': '2025-12-19 08:30:00',
                '收缩压': 20,
                '舒张压': 80
            }
            is_valid, cleaned, error = import_manager.validate_row(row, data['user'].id, 1)
            assert is_valid is False
            assert "收缩压" in error and "范围" in error
            
            # Diastolic too high
            row = {
                '成员名称': 'Self',
                '测量时间': '2025-12-19 08:30:00',
                '收缩压': 120,
                '舒张压': 260
            }
            is_valid, cleaned, error = import_manager.validate_row(row, data['user'].id, 1)
            assert is_valid is False
            assert "舒张压" in error and "范围" in error
    
    def test_validate_systolic_less_than_diastolic(self, app, import_manager, setup_user_with_members):
        """Test validation when systolic <= diastolic"""
        with app.app_context():
            data = setup_user_with_members
            row = {
                '成员名称': 'Self',
                '测量时间': '2025-12-19 08:30:00',
                '收缩压': 80,
                '舒张压': 90
            }
            
            is_valid, cleaned, error = import_manager.validate_row(row, data['user'].id, 1)
            
            assert is_valid is False
            assert "收缩压必须大于舒张压" in error
    
    def test_validate_heart_rate_optional(self, app, import_manager, setup_user_with_members):
        """Test validation with optional heart rate"""
        with app.app_context():
            data = setup_user_with_members
            
            # Without heart rate
            row = {
                '成员名称': 'Self',
                '测量时间': '2025-12-19 08:30:00',
                '收缩压': 120,
                '舒张压': 80
            }
            is_valid, cleaned, error = import_manager.validate_row(row, data['user'].id, 1)
            assert is_valid is True
            assert cleaned['heart_rate'] is None
            
            # With valid heart rate
            row['心率'] = 72
            is_valid, cleaned, error = import_manager.validate_row(row, data['user'].id, 1)
            assert is_valid is True
            assert cleaned['heart_rate'] == 72
            
            # Heart rate out of range
            row['心率'] = 160
            is_valid, cleaned, error = import_manager.validate_row(row, data['user'].id, 1)
            assert is_valid is False
            assert "心率" in error and "范围" in error
    
    def test_validate_note_too_long(self, app, import_manager, setup_user_with_members):
        """Test validation with note exceeding 500 characters"""
        with app.app_context():
            data = setup_user_with_members
            row = {
                '成员名称': 'Self',
                '测量时间': '2025-12-19 08:30:00',
                '收缩压': 120,
                '舒张压': 80,
                '备注': 'x' * 501
            }
            
            is_valid, cleaned, error = import_manager.validate_row(row, data['user'].id, 1)
            
            assert is_valid is False
            assert "备注" in error and "500" in error


class TestImportManagerBatchImport:
    """Test batch import functionality"""
    
    def test_batch_import_all_success(self, app, import_manager, setup_user_with_members):
        """Test batch import with all valid rows"""
        with app.app_context():
            data = setup_user_with_members
            rows = [
                {
                    '成员名称': 'Self',
                    '测量时间': '2025-12-19 08:30:00',
                    '收缩压': 120,
                    '舒张压': 80,
                    '心率': 72,
                    '标签': '晨起',
                    '备注': '正常'
                },
                {
                    '成员名称': '父亲',
                    '测量时间': '2025-12-19 09:00:00',
                    '收缩压': 130,
                    '舒张压': 85,
                    '心率': 75,
                    '标签': '餐后',
                    '备注': '血压稍高'
                }
            ]
            
            result = import_manager.batch_import(data['user'].id, rows, skip_errors=True)
            
            assert result['total'] == 2
            assert result['success'] == 2
            assert result['failed'] == 0
            assert len(result['errors']) == 0
            
            # Verify records in database
            records = HealthRecord.query.filter_by(user_id=data['user'].id).all()
            assert len(records) == 2
            
            subjects = RecordSubject.query.filter_by(created_by_user_id=data['user'].id).all()
            assert len(subjects) == 2
    
    def test_batch_import_partial_success(self, app, import_manager, setup_user_with_members):
        """Test batch import with some invalid rows"""
        with app.app_context():
            data = setup_user_with_members
            rows = [
                {
                    '成员名称': 'Self',
                    '测量时间': '2025-12-19 08:30:00',
                    '收缩压': 120,
                    '舒张压': 80
                },
                {
                    '成员名称': '不存在的成员',
                    '测量时间': '2025-12-19 09:00:00',
                    '收缩压': 130,
                    '舒张压': 85
                },
                {
                    '成员名称': '父亲',
                    '测量时间': '2025-12-19 10:00:00',
                    '收缩压': 140,
                    '舒张压': 90
                }
            ]
            
            result = import_manager.batch_import(data['user'].id, rows, skip_errors=True)
            
            assert result['total'] == 3
            assert result['success'] == 2
            assert result['failed'] == 1
            assert len(result['errors']) == 1
            assert result['errors'][0]['row'] == 2
            
            # Verify only valid records imported
            records = HealthRecord.query.filter_by(user_id=data['user'].id).all()
            assert len(records) == 2
    
    def test_batch_import_abort_on_error(self, app, import_manager, setup_user_with_members):
        """Test batch import aborting on first error"""
        with app.app_context():
            data = setup_user_with_members
            rows = [
                {
                    '成员名称': 'Self',
                    '测量时间': '2025-12-19 08:30:00',
                    '收缩压': 120,
                    '舒张压': 80
                },
                {
                    '成员名称': '不存在的成员',
                    '测量时间': '2025-12-19 09:00:00',
                    '收缩压': 130,
                    '舒张压': 85
                }
            ]
            
            result = import_manager.batch_import(data['user'].id, rows, skip_errors=False)
            
            assert result['total'] == 2
            assert result['success'] == 0
            assert result['failed'] == 2
            
            # Verify no records imported
            records = HealthRecord.query.filter_by(user_id=data['user'].id).all()
            assert len(records) == 0


class TestImportManagerSaveLog:
    """Test import log saving"""
    
    def test_save_import_log_success(self, app, import_manager, setup_user_with_members):
        """Test saving import log for successful import"""
        with app.app_context():
            data = setup_user_with_members
            result = {
                'total': 100,
                'success': 100,
                'failed': 0,
                'errors': []
            }
            
            log = import_manager.save_import_log(data['user'].id, 'test.xlsx', result)
            
            assert log.id is not None
            assert log.user_id == data['user'].id
            assert log.filename == 'test.xlsx'
            assert log.total_rows == 100
            assert log.success_rows == 100
            assert log.failed_rows == 0
            assert log.status == 'success'
    
    def test_save_import_log_partial(self, app, import_manager, setup_user_with_members):
        """Test saving import log for partial success"""
        with app.app_context():
            data = setup_user_with_members
            result = {
                'total': 100,
                'success': 95,
                'failed': 5,
                'errors': [{'row': 10, 'reason': 'error'}]
            }
            
            log = import_manager.save_import_log(data['user'].id, 'test.csv', result)
            
            assert log.status == 'partial'
            assert log.success_rows == 95
            assert log.failed_rows == 5
    
    def test_save_import_log_failed(self, app, import_manager, setup_user_with_members):
        """Test saving import log for failed import"""
        with app.app_context():
            data = setup_user_with_members
            result = {
                'total': 100,
                'success': 0,
                'failed': 100,
                'errors': [{'row': i, 'reason': 'error'} for i in range(1, 101)]
            }
            
            log = import_manager.save_import_log(data['user'].id, 'test.xlsx', result)
            
            assert log.status == 'failed'
            assert log.success_rows == 0
            assert log.failed_rows == 100
