/**
 * Global Member Selection Context. Generated by Zhuang
 */
import React, { createContext, useContext, useEffect, useState } from 'react';
import {
  getUserIdFromToken,
  MEMBER_SELECTION_KEY,
  MEMBER_SELECTION_OWNER_KEY,
} from '../utils/auth';

const MemberContext = createContext({ selectedMemberId: undefined, setSelectedMemberId: () => {} });

export const MemberProvider = ({ children }) => {
  const [selectedMemberId, setSelectedMemberId] = useState(() => {
    try {
      const userId = getUserIdFromToken();
      const owner = localStorage.getItem(MEMBER_SELECTION_OWNER_KEY);
      if (!userId || owner !== String(userId)) {
        return undefined;
      }
      const raw = localStorage.getItem(MEMBER_SELECTION_KEY);
      if (raw === null || raw === undefined) {
        return undefined;
      }
      const parsed = Number(raw);
      return Number.isFinite(parsed) ? parsed : undefined;
    } catch {
      return undefined;
    }
  });

  useEffect(() => {
    try {
      const userId = getUserIdFromToken();
      if (!userId) {
        localStorage.removeItem(MEMBER_SELECTION_KEY);
        localStorage.removeItem(MEMBER_SELECTION_OWNER_KEY);
        return;
      }
      if (selectedMemberId === undefined || selectedMemberId === null) {
        localStorage.removeItem(MEMBER_SELECTION_KEY);
      } else {
        localStorage.setItem(MEMBER_SELECTION_KEY, String(selectedMemberId));
      }
      localStorage.setItem(MEMBER_SELECTION_OWNER_KEY, String(userId));
    } catch {}
  }, [selectedMemberId]);

  return (
    <MemberContext.Provider value={{ selectedMemberId, setSelectedMemberId }}>
      {children}
    </MemberContext.Provider>
  );
};

export const useMember = () => useContext(MemberContext);
