/**
 * API Service for Health Platform
 * Generated by Zhuang
 */
import axios from 'axios';

// Generated by Zhuang: use same-origin by default so Nginx can proxy /api to backend
const BASE_URL = process.env.REACT_APP_API_URL || '';

// Create axios instance
const api = axios.create({
  baseURL: BASE_URL,
  headers: {
    'Content-Type': 'application/json',
  },
});

// Request interceptor to add auth token
api.interceptors.request.use(
  (config) => {
    const token = localStorage.getItem('access_token');
    if (token) {
      config.headers.Authorization = `Bearer ${token}`;
    }
    return config;
  },
  (error) => {
    return Promise.reject(error);
  }
);

// Response interceptor to handle token refresh
api.interceptors.response.use(
  (response) => {
    return response;
  },
  async (error) => {
    const originalRequest = error.config;

    if (error.response?.status === 401 && !originalRequest._retry) {
      originalRequest._retry = true;

      try {
        const refreshToken = localStorage.getItem('refresh_token');
        if (refreshToken) {
          const response = await axios.post(`${BASE_URL}/api/v1/auth/refresh`, {}, {
            headers: {
              Authorization: `Bearer ${refreshToken}`,
            },
          });

          const { access_token, refresh_token } = response.data;
          localStorage.setItem('access_token', access_token);
          localStorage.setItem('refresh_token', refresh_token);

          // Retry original request with new token
          originalRequest.headers.Authorization = `Bearer ${access_token}`;
          return api(originalRequest);
        }
      } catch (refreshError) {
        // Refresh failed, redirect to login
        localStorage.removeItem('access_token');
        localStorage.removeItem('refresh_token');
        window.location.href = '/login';
        return Promise.reject(refreshError);
      }
    }

    return Promise.reject(error);
  }
);

// Auth APIs
export const authAPI = {
  register: (userData) => api.post('/api/v1/auth/register', userData),
  login: (credentials) => api.post('/api/v1/auth/login', credentials),
  refresh: () => api.post('/api/v1/auth/refresh'),
  // logout requires refresh token; allow passing custom config with headers
  logout: (config) => api.post('/api/v1/auth/logout', {}, config),
  logoutAll: () => api.post('/api/v1/auth/logout-all'),
};

// User APIs
export const userAPI = {
  getProfile: (userId) => api.get(`/api/v1/user/${userId}`),
  updateProfile: (userId, userData) => api.put(`/api/v1/user/${userId}`, userData),
};

// Health Record APIs
export const healthAPI = {
  createRecord: (recordData) => api.post('/api/v1/health', recordData),
  getRecords: (params) => api.get('/api/v1/health', { params }),
  getRecord: (recordId) => api.get(`/api/v1/health/${recordId}`),
  updateRecord: (recordId, recordData) => api.put(`/api/v1/health/${recordId}`, recordData),
  deleteRecord: (recordId) => api.delete(`/api/v1/health/${recordId}`),
  // Generated by Zhuang: Export CSV respecting filters and subject_member_id
  exportCsv: (params) => api.get('/api/v1/health/export', { params, responseType: 'blob' }),
};

// Members APIs (simplified family management)
export const memberAPI = {
  list: () => api.get('/api/v1/members'),
  create: (member) => api.post('/api/v1/members', member),
  update: (memberId, member) => api.put(`/api/v1/members/${memberId}`, member),
  remove: (memberId) => api.delete(`/api/v1/members/${memberId}`),
};

export default api;
