/**
 * Time Synchronization Service
 * Generated by Copilot - addresses time discrepancy issues
 */

const TIME_DISCREPANCY_THRESHOLD_MS = 5 * 60 * 1000; // 5 minutes

export class TimeSyncService {
  static async checkTimeSync() {
    try {
      // Get client time before making request (more accurate)
      const clientTime = new Date();
      
      // Make request to get server time
      const response = await fetch('/api/v1/auth/time', {
        method: 'GET',
        headers: {
          'Content-Type': 'application/json',
        },
      });
      
      if (!response.ok) {
        console.warn('Failed to get server time for sync check');
        return { syncOk: true, discrepancy: 0 }; // Assume OK if we can't check
      }
      
      const data = await response.json();
      const serverTime = new Date(data.server_time);
      
      // Calculate discrepancy (client time - server time)
      const discrepancy = clientTime.getTime() - serverTime.getTime();
      const syncOk = Math.abs(discrepancy) <= TIME_DISCREPANCY_THRESHOLD_MS;
      
      return {
        syncOk,
        discrepancy,
        clientTime: clientTime.toISOString(),
        serverTime: serverTime.toISOString(),
        threshold: TIME_DISCREPANCY_THRESHOLD_MS
      };
    } catch (error) {
      console.warn('Time sync check failed:', error);
      return { syncOk: true, discrepancy: 0 }; // Assume OK if we can't check
    }
  }
  
  static formatDiscrepancy(discrepancyMs) {
    const seconds = Math.abs(discrepancyMs) / 1000;
    const minutes = Math.floor(seconds / 60);
    const remainingSeconds = Math.floor(seconds % 60);
    
    if (minutes > 0) {
      return `${minutes}m ${remainingSeconds}s`;
    }
    return `${remainingSeconds}s`;
  }
  
  static getDiscrepancyDirection(discrepancyMs) {
    if (discrepancyMs > 0) {
      return 'ahead';
    } else if (discrepancyMs < 0) {
      return 'behind';
    }
    return 'synchronized';
  }
}

export default TimeSyncService;