@echo off
REM Health Platform Configurable Deployment Script (Windows)
REM Generated by Zhuang

setlocal enabledelayedexpansion

set ENVIRONMENT=%1
if "%ENVIRONMENT%"=="" set ENVIRONMENT=dev

set CONFIG_FILE=deploy\config\%ENVIRONMENT%.env
set TEMPLATE_FILE=deploy\k8s-template.yaml
set OUTPUT_FILE=deploy\k8s-%ENVIRONMENT%.yaml

echo 🚀 Deploying Health Platform to %ENVIRONMENT% environment...

if not exist "%CONFIG_FILE%" (
    echo ❌ Config file %CONFIG_FILE% not found!
    echo Available environments:
    dir /b deploy\config\*.env 2>nul
    exit /b 1
)

echo 📋 Loading configuration from %CONFIG_FILE%...

REM Load environment variables from config file
for /f "usebackq tokens=1,2 delims==" %%a in ("%CONFIG_FILE%") do (
    set "%%a=%%b"
)

echo 📝 Generating Kubernetes manifests...
REM Note: Windows doesn't have envsubst, this would need a different approach
echo ⚠️  Windows deployment requires manual template substitution or WSL

echo ✅ For Windows deployment, please use WSL or manually edit the template file
echo Template: %TEMPLATE_FILE%
echo Config: %CONFIG_FILE%

pause
