apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-test
  namespace: health-platform
  labels:
    app: frontend-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-test
  template:
    metadata:
      labels:
        app: frontend-test
    spec:
      containers:
        - name: frontend
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
          env:
            - name: API_URL
              value: "http://backend-svc.health-platform.svc.cluster.local:5000"
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx-default.conf
          readinessProbe:
            httpGet:
              path: /nginx-health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /nginx-health  
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 20
      volumes:
        - name: html
          emptyDir: {}
        - name: nginx-conf
          configMap:
            name: frontend-nginx-conf
