"""
Test three-tier threshold validation and status computation.
Generated by Copilot
"""
import pytest
from src.manager.threshold_manager import ThresholdManager, ThresholdValidationError


class TestThreeTierThreshold:
    def test_validate_config_with_borderline_max(self):
        """Test that valid config with borderline_max passes validation."""
        manager = ThresholdManager()
        payload = {
            "systolic": {"min": 90, "max": 120, "borderline_max": 140},
            "diastolic": {"min": 60, "max": 80, "borderline_max": 90},
            "heart_rate": {"min": 60, "max": 100}
        }
        # Should not raise
        manager.validate_config(payload)
    
    def test_validate_config_missing_borderline_for_bp(self):
        """Test that missing borderline_max for blood pressure raises error."""
        manager = ThresholdManager()
        payload = {
            "systolic": {"min": 90, "max": 120},  # Missing borderline_max
            "diastolic": {"min": 60, "max": 80, "borderline_max": 90},
            "heart_rate": {"min": 60, "max": 100}
        }
        with pytest.raises(ThresholdValidationError, match="systolic must have borderline_max"):
            manager.validate_config(payload)
    
    def test_validate_config_borderline_less_than_max(self):
        """Test that borderline_max <= max raises error."""
        manager = ThresholdManager()
        payload = {
            "systolic": {"min": 90, "max": 120, "borderline_max": 115},  # Invalid: 115 <= 120
            "diastolic": {"min": 60, "max": 80, "borderline_max": 90},
            "heart_rate": {"min": 60, "max": 100}
        }
        with pytest.raises(ThresholdValidationError, match="borderline_max must be greater than max"):
            manager.validate_config(payload)
    
    def test_validate_config_borderline_exceeds_limit(self):
        """Test that borderline_max > hard limit raises error."""
        manager = ThresholdManager()
        payload = {
            "systolic": {"min": 90, "max": 120, "borderline_max": 260},  # Exceeds 250
            "diastolic": {"min": 60, "max": 80, "borderline_max": 90},
            "heart_rate": {"min": 60, "max": 100}
        }
        with pytest.raises(ThresholdValidationError, match="must be between"):
            manager.validate_config(payload)
    
    def test_compute_status_healthy(self):
        """Test that values within [min, max] are healthy."""
        manager = ThresholdManager()
        payload = {
            "systolic": {"min": 90, "max": 120, "borderline_max": 140},
            "diastolic": {"min": 60, "max": 80, "borderline_max": 90},
            "heart_rate": {"min": 60, "max": 100}
        }
        status = manager._compute_status(110, 75, 80, payload)
        assert status == "healthy"
    
    def test_compute_status_borderline(self):
        """Test that BP values in (max, borderline_max] are borderline."""
        manager = ThresholdManager()
        payload = {
            "systolic": {"min": 90, "max": 120, "borderline_max": 140},
            "diastolic": {"min": 60, "max": 80, "borderline_max": 90},
            "heart_rate": {"min": 60, "max": 100}
        }
        # Systolic 130 is in borderline zone (120, 140]
        status = manager._compute_status(130, 75, 80, payload)
        assert status == "borderline"
        
        # Diastolic 85 is in borderline zone (80, 90]
        status = manager._compute_status(110, 85, 80, payload)
        assert status == "borderline"
    
    def test_compute_status_out_of_range(self):
        """Test that values outside all ranges are out_of_range."""
        manager = ThresholdManager()
        payload = {
            "systolic": {"min": 90, "max": 120, "borderline_max": 140},
            "diastolic": {"min": 60, "max": 80, "borderline_max": 90},
            "heart_rate": {"min": 60, "max": 100}
        }
        # Systolic 150 exceeds borderline_max
        status = manager._compute_status(150, 75, 80, payload)
        assert status == "out_of_range"
        
        # Systolic 50 below min
        status = manager._compute_status(50, 75, 80, payload)
        assert status == "out_of_range"
        
        # Heart rate 110 exceeds max
        status = manager._compute_status(110, 75, 110, payload)
        assert status == "out_of_range"
    
    def test_compute_status_priority(self):
        """Test that out_of_range takes precedence over borderline."""
        manager = ThresholdManager()
        payload = {
            "systolic": {"min": 90, "max": 120, "borderline_max": 140},
            "diastolic": {"min": 60, "max": 80, "borderline_max": 90},
            "heart_rate": {"min": 60, "max": 100}
        }
        # Systolic borderline (130) but diastolic out_of_range (95)
        status = manager._compute_status(130, 95, 80, payload)
        assert status == "out_of_range"
    
    def test_heart_rate_no_borderline(self):
        """Test that heart rate does not use borderline zone."""
        manager = ThresholdManager()
        payload = {
            "systolic": {"min": 90, "max": 120, "borderline_max": 140},
            "diastolic": {"min": 60, "max": 80, "borderline_max": 90},
            "heart_rate": {"min": 60, "max": 100}
        }
        # Heart rate 101 should be out_of_range (no borderline for HR)
        status = manager._compute_status(110, 75, 101, payload)
        assert status == "out_of_range"
