"""
Revision ID: f041ccf3b820
Revises: add_user_roles_and_flags_e9u3xz
Create Date: 2025-12-02 20:07:22.852366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f041ccf3b820'
down_revision = 'add_user_roles_and_flags_e9u3xz'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

