import React, { useState, useEffect } from 'react';
import { Table, Card, Tag, Button, Space, message } from 'antd';
import { EyeOutlined, CheckCircleOutlined } from '@ant-design/icons';
import api from '../../services/api';

/**
 * ThresholdPreview - Component to preview draft threshold effects on sample records
 * Generated by Copilot
 */
const ThresholdPreview = ({ draftId, onPublish }) => {
  const [loading, setLoading] = useState(false);
  const [previewData, setPreviewData] = useState([]);
  const [publishing, setPublishing] = useState(false);

  useEffect(() => {
    if (draftId) {
      loadPreview();
    }
  }, [draftId]);

  const loadPreview = async () => {
    setLoading(true);
    try {
      const response = await api.get(`/api/v1/thresholds/preview`, {
        params: { draft_id: draftId, sample: 30 }
      });
      setPreviewData(response.data.preview || []);
    } catch (error) {
      message.error('预览加载失败: ' + (error.response?.data?.error || error.message));
    } finally {
      setLoading(false);
    }
  };

  const handlePublish = async () => {
    setPublishing(true);
    try {
      const response = await api.post('/api/v1/admin/thresholds/publish', {
        draft_id: draftId
      });
      message.success(`已发布版本 ${response.data.version}`);
      if (onPublish) {
        onPublish(response.data);
      }
    } catch (error) {
      message.error('发布失败: ' + (error.response?.data?.error || error.message));
    } finally {
      setPublishing(false);
    }
  };

  const getStatusTag = (status) => {
    const statusConfig = {
      healthy: { color: 'green', text: '健康' },
      borderline: { color: 'orange', text: '边界' },
      out_of_range: { color: 'red', text: '超出范围' }
    };
    const config = statusConfig[status] || { color: 'default', text: status };
    return <Tag color={config.color}>{config.text}</Tag>;
  };

  const columns = [
    {
      title: 'ID',
      dataIndex: 'id',
      key: 'id',
      width: 80
    },
    {
      title: '收缩压',
      dataIndex: 'systolic',
      key: 'systolic',
      width: 100,
      render: (value) => `${value} mmHg`
    },
    {
      title: '舒张压',
      dataIndex: 'diastolic',
      key: 'diastolic',
      width: 100,
      render: (value) => `${value} mmHg`
    },
    {
      title: '心率',
      dataIndex: 'heart_rate',
      key: 'heart_rate',
      width: 100,
      render: (value) => value ? `${value} bpm` : '-'
    },
    {
      title: '阈值状态',
      dataIndex: 'threshold_status',
      key: 'threshold_status',
      width: 120,
      render: (status) => getStatusTag(status)
    },
    {
      title: '记录时间',
      dataIndex: 'timestamp',
      key: 'timestamp',
      render: (value) => new Date(value).toLocaleString('zh-CN')
    }
  ];

  return (
    <Card 
      title="预览效果" 
      bordered={false}
      extra={
        <Space>
          <Button 
            icon={<EyeOutlined />} 
            onClick={loadPreview}
            loading={loading}
          >
            刷新预览
          </Button>
          <Button 
            type="primary" 
            icon={<CheckCircleOutlined />}
            onClick={handlePublish}
            loading={publishing}
            disabled={!draftId}
          >
            发布为活跃配置
          </Button>
        </Space>
      }
    >
      <Table
        columns={columns}
        dataSource={previewData}
        loading={loading}
        rowKey="id"
        pagination={{ pageSize: 10 }}
        size="small"
      />
    </Card>
  );
};

export default ThresholdPreview;
