"""
Super admin initialization utilities.
Generated by Copilot
"""
from typing import Optional
from sqlalchemy.exc import IntegrityError
from ..extensions import db
from ..models import User
from ..security import hash_password


def init_super_admin(username: str, email: str, password: str) -> Optional[User]:
    """
    Initialize the super admin user if not exists.
    Returns the super admin user or None if initialization failed.
    """
    # Check if super admin already exists
    existing_super_admin = User.query.filter_by(role="SUPER_ADMIN").first()
    if existing_super_admin:
        print(f"Super admin already exists: {existing_super_admin.email}")
        return existing_super_admin
    
    # Check if user with the email already exists (but with different role)
    existing_user = User.query.filter_by(email=email.lower()).first()
    if existing_user:
        # Upgrade existing user to super admin
        existing_user.role = "SUPER_ADMIN"
        existing_user.must_change_password = True  # Force password change on first login
        db.session.commit()
        print(f"Upgraded existing user to super admin: {existing_user.email}")
        return existing_user
    
    # Create new super admin user
    try:
        super_admin = User()
        super_admin.username = username.lower()  # Case insensitive
        super_admin.email = email.lower()  # Case insensitive
        super_admin.password_hash = hash_password(password)
        super_admin.role = "SUPER_ADMIN"
        super_admin.must_change_password = True  # Force password change on first login
        
        db.session.add(super_admin)
        db.session.commit()
        
        print(f"Created super admin user: {super_admin.email}")
        return super_admin
        
    except IntegrityError as e:
        db.session.rollback()
        print(f"Failed to create super admin: {e}")
        return None
    except Exception as e:
        db.session.rollback()
        print(f"Unexpected error creating super admin: {e}")
        return None


def validate_super_admin_uniqueness() -> bool:
    """
    Validate that only one super admin exists.
    Returns True if validation passes, False otherwise.
    """
    super_admin_count = User.query.filter_by(role="SUPER_ADMIN").count()
    if super_admin_count > 1:
        print(f"ERROR: Multiple super admins found ({super_admin_count}). System integrity violated!")
        return False
    elif super_admin_count == 0:
        print("WARNING: No super admin found.")
        return False
    
    return True