"""
Pagination utilities.
Generated by Copilot
"""
from typing import Any, Dict, Tuple
from flask import request


DEFAULT_PAGE_SIZE = 20
MAX_PAGE_SIZE = 100


def get_pagination_params() -> Tuple[int, int]:
    """Extract pagination parameters from request"""
    try:
        page = int(request.args.get("page", 1))
    except ValueError:
        page = 1
    try:
        size = int(request.args.get("size", DEFAULT_PAGE_SIZE))
    except ValueError:
        size = DEFAULT_PAGE_SIZE
    size = max(1, min(size, MAX_PAGE_SIZE))
    page = max(1, page)
    return page, size


def make_pagination(page: int, size: int, total: int) -> Dict[str, Any]:
    """Create pagination metadata"""
    pages = (total + size - 1) // size  # Calculate total pages (ceiling division)
    return {"page": page, "size": size, "total": total, "pages": pages}