/**
 * Admin Users Management Page
 * Generated by Copilot
 */
import React, { useState, useEffect } from 'react';
import {
  Table,
  Card,
  Button,
  Tag,
  Modal,
  Select,
  message,
  Typography,
  Space,
  Popconfirm,
  Input,
} from 'antd';
import {
  UserOutlined,
  KeyOutlined,
  EditOutlined,
  CrownOutlined,
} from '@ant-design/icons';
import { adminAPI, userAPI } from '../services/api';
import { getUserIdFromToken } from '../utils/auth';
import { useTranslation } from 'react-i18next';

const { Title } = Typography;
const { Option } = Select;

const AdminUsers = () => {
  const [users, setUsers] = useState([]);
  const [loading, setLoading] = useState(false);
  const [pagination, setPagination] = useState({ page: 1, size: 10, total: 0 });
  const [roleModalVisible, setRoleModalVisible] = useState(false);
  const [selectedUser, setSelectedUser] = useState(null);
  const [newRole, setNewRole] = useState('');
  const [tempPasswordModal, setTempPasswordModal] = useState({ visible: false, password: '' });
  const [currentUser, setCurrentUser] = useState(null); // Added for role-based UI control
  const { t } = useTranslation();

  const loadUsers = async (page = 1, size = 10) => {
    setLoading(true);
    try {
      const response = await adminAPI.getUsers({ page, size });
      setUsers(response.data.users);
      setPagination({
        page,
        size,
        total: response.data.pagination.total,
        pages: response.data.pagination.pages,
      });
    } catch (error) {
      console.error('Failed to load users:', error);
      message.error(t('admin.users.loadFailed'));
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    // Load current user info for role-based UI control
    const loadCurrentUser = async () => {
      try {
        const userId = getUserIdFromToken();
        if (userId) {
          const response = await userAPI.getProfile(userId);
          setCurrentUser(response.data);
        }
      } catch (error) {
        console.error('Failed to load current user:', error);
      }
    };

    loadCurrentUser();
    loadUsers();
  }, []);

  const handleChangeRole = async () => {
    if (!selectedUser || !newRole) return;

    try {
      await adminAPI.changeUserRole(selectedUser.id, newRole);
      message.success(t('admin.users.roleChangeSuccess'));
      setRoleModalVisible(false);
      setSelectedUser(null);
      setNewRole('');
      loadUsers(pagination.page, pagination.size);
    } catch (error) {
      console.error('Failed to change role:', error);
      const errorMessage = error.response?.data?.message || t('admin.users.roleChangeFailed');
      message.error(errorMessage);
    }
  };

  const handleResetPassword = async (user) => {
    try {
      const response = await adminAPI.resetUserPassword(user.id);
      setTempPasswordModal({
        visible: true,
        password: response.data.temporary_password,
        user: user,
      });
      loadUsers(pagination.page, pagination.size); // Reload to show updated must_change_password status
    } catch (error) {
      console.error('Failed to reset password:', error);
      const errorMessage = error.response?.data?.message || t('admin.users.passwordResetFailed');
      message.error(errorMessage);
    }
  };

  const getRoleColor = (role) => {
    switch (role) {
      case 'SUPER_ADMIN':
        return 'red';
      case 'ADMIN':
        return 'orange';
      case 'USER':
        return 'blue';
      default:
        return 'default';
    }
  };

  const getRoleIcon = (role) => {
    switch (role) {
      case 'SUPER_ADMIN':
        return <CrownOutlined />;
      case 'ADMIN':
        return <EditOutlined />;
      case 'USER':
        return <UserOutlined />;
      default:
        return <UserOutlined />;
    }
  };

  const columns = [
    {
      title: t('admin.users.username'),
      dataIndex: 'username',
      key: 'username',
    },
    {
      title: t('admin.users.email'),
      dataIndex: 'email',
      key: 'email',
    },
    {
      title: t('admin.users.role'),
      dataIndex: 'role',
      key: 'role',
      render: (role) => (
        <Tag color={getRoleColor(role)} icon={getRoleIcon(role)}>
          {t(`admin.roles.${role.toLowerCase()}`)}
        </Tag>
      ),
    },
    {
      title: t('admin.users.mustChangePassword'),
      dataIndex: 'must_change_password',
      key: 'must_change_password',
      render: (mustChange) => (
        <Tag color={mustChange ? 'warning' : 'success'}>
          {mustChange ? t('admin.users.yes') : t('admin.users.no')}
        </Tag>
      ),
    },
    {
      title: t('admin.users.actions'),
      key: 'actions',
      render: (_, user) => (
        <Space>
          {user.role !== 'SUPER_ADMIN' && (
            <>
              {/* Only SUPER_ADMIN can change roles */}
              {currentUser?.role === 'SUPER_ADMIN' && (
                <Button
                  type="primary"
                  size="small"
                  icon={<EditOutlined />}
                  onClick={() => {
                    setSelectedUser(user);
                    setNewRole(user.role);
                    setRoleModalVisible(true);
                  }}
                >
                  {t('admin.users.changeRole')}
                </Button>
              )}
              {/* Both ADMIN and SUPER_ADMIN can reset passwords */}
              <Popconfirm
                title={t('admin.users.resetPasswordConfirm')}
                description={t('admin.users.resetPasswordDescription')}
                onConfirm={() => handleResetPassword(user)}
                okText={t('admin.users.yes')}
                cancelText={t('admin.users.no')}
              >
                <Button
                  type="default"
                  size="small"
                  icon={<KeyOutlined />}
                  danger
                >
                  {t('admin.users.resetPassword')}
                </Button>
              </Popconfirm>
            </>
          )}
          {user.role === 'SUPER_ADMIN' && (
            <Tag color="gold">{t('admin.users.protected')}</Tag>
          )}
        </Space>
      ),
    },
  ];

  return (
    <div>
      <Title level={2}>{t('admin.users.title')}</Title>
      
      <Card>
        <Table
          columns={columns}
          dataSource={users}
          rowKey="id"
          loading={loading}
          pagination={{
            current: pagination.page,
            pageSize: pagination.size,
            total: pagination.total,
            showSizeChanger: true,
            showQuickJumper: true,
            onChange: (page, size) => loadUsers(page, size),
            showTotal: (total, range) =>
              t('admin.users.pagination', {
                start: range[0],
                end: range[1],
                total,
              }),
          }}
        />
      </Card>

      {/* Role Change Modal */}
      <Modal
        title={t('admin.users.changeRoleTitle')}
        open={roleModalVisible}
        onOk={handleChangeRole}
        onCancel={() => {
          setRoleModalVisible(false);
          setSelectedUser(null);
          setNewRole('');
        }}
        okText={t('admin.users.confirm')}
        cancelText={t('admin.users.cancel')}
      >
        {selectedUser && (
          <div>
            <p>
              <strong>{t('admin.users.user')}:</strong> {selectedUser.username} ({selectedUser.email})
            </p>
            <p>
              <strong>{t('admin.users.currentRole')}:</strong> 
              <Tag color={getRoleColor(selectedUser.role)} style={{ marginLeft: 8 }}>
                {t(`admin.roles.${selectedUser.role.toLowerCase()}`)}
              </Tag>
            </p>
            <p>
              <strong>{t('admin.users.newRole')}:</strong>
            </p>
            <Select
              value={newRole}
              onChange={setNewRole}
              style={{ width: '100%' }}
              placeholder={t('admin.users.selectRole')}
            >
              <Option value="USER">{t('admin.roles.user')}</Option>
              <Option value="ADMIN">{t('admin.roles.admin')}</Option>
            </Select>
          </div>
        )}
      </Modal>

      {/* Temporary Password Modal */}
      <Modal
        title={t('admin.users.temporaryPasswordTitle')}
        open={tempPasswordModal.visible}
        onOk={() => setTempPasswordModal({ visible: false, password: '' })}
        onCancel={() => setTempPasswordModal({ visible: false, password: '' })}
        cancelButtonProps={{ style: { display: 'none' } }}
        okText={t('admin.users.understood')}
      >
        <div>
          <p>{t('admin.users.passwordResetSuccess')} <strong>{tempPasswordModal.user?.username}</strong></p>
          <div style={{ 
            background: '#f5f5f5', 
            padding: '12px', 
            borderRadius: '4px', 
            marginBottom: '12px',
            fontFamily: 'monospace',
            fontSize: '16px',
            textAlign: 'center',
            border: '2px dashed #1890ff'
          }}>
            <strong>{tempPasswordModal.password}</strong>
          </div>
          <p style={{ color: '#fa8c16' }}>
            <strong>{t('admin.users.temporaryPasswordNote')}</strong>
          </p>
          <p>{t('admin.users.temporaryPasswordInstructions')}</p>
        </div>
      </Modal>
    </div>
  );
};

export default AdminUsers;