/**
 * Change Password Page Component (for forced password changes)
 * Generated by Copilot
 */
import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { Form, Input, Button, Card, Typography, message, Alert } from 'antd';
import { LockOutlined } from '@ant-design/icons';
import { authAPI } from '../services/api';
import { clearTokens } from '../utils/auth';
import { useTranslation } from 'react-i18next';

const { Title, Text } = Typography;

const ChangePassword = () => {
  const navigate = useNavigate();
  const [loading, setLoading] = useState(false);
  const [userInfo, setUserInfo] = useState(null);
  const { t } = useTranslation();

  useEffect(() => {
    // Get user info from session storage
    const storedUserInfo = sessionStorage.getItem('user_info');
    if (storedUserInfo) {
      setUserInfo(JSON.parse(storedUserInfo));
    } else {
      // If no user info, redirect to login
      navigate('/login');
    }
  }, [navigate]);

  const onFinish = async (values) => {
    setLoading(true);
    try {
      await authAPI.forceChangePassword({ new_password: values.password });
      
      // Clear tokens and user info to force fresh login
      clearTokens();
      sessionStorage.removeItem('user_info');
      
      message.success(t('messages.password.changeSuccess'));
      message.info(t('messages.password.pleaseLoginAgain'));
      navigate('/login');
    } catch (error) {
      console.error('Password change error:', error);
      const errorMessage = error.response?.data?.message || t('messages.password.changeFailed');
      message.error(errorMessage);
    } finally {
      setLoading(false);
    }
  };

  if (!userInfo) {
    return null; // Loading or redirecting
  }

  return (
    <div style={{ 
      minHeight: '100vh', 
      background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      padding: '20px'
    }}>
      <Card style={{ width: '100%', maxWidth: 400 }}>
        <div style={{ textAlign: 'center', marginBottom: 32 }}>
          <Title level={2} style={{ color: '#fa8c16', marginBottom: 8 }}>
            {t('changePassword.title')}
          </Title>
          <Text type="secondary">{t('changePassword.subtitle')}</Text>
        </div>

        <Alert
          message={t('changePassword.requiredMessage')}
          description={t('changePassword.requiredDescription')}
          type="warning"
          showIcon
          style={{ marginBottom: 24 }}
        />

        <div style={{ marginBottom: 16 }}>
          <Text strong>{t('changePassword.currentUser')}: </Text>
          <Text>{userInfo.username} ({userInfo.email})</Text>
        </div>

        <Form
          name="changePassword"
          onFinish={onFinish}
          size="large"
        >
          <Form.Item
            name="password"
            rules={[
              { required: true, message: t('changePassword.newPasswordRequired') },
              { min: 8, message: t('changePassword.passwordMinLength') },
              {
                pattern: /^(?=.*[A-Za-z])(?=.*\d).+$/,
                message: t('changePassword.passwordPattern')
              }
            ]}
          >
            <Input.Password
              prefix={<LockOutlined />}
              placeholder={t('changePassword.newPassword')}
              data-testid="new-password"
            />
          </Form.Item>

          <Form.Item
            name="confirmPassword"
            dependencies={['password']}
            rules={[
              { required: true, message: t('changePassword.confirmPasswordRequired') },
              ({ getFieldValue }) => ({
                validator(_, value) {
                  if (!value || getFieldValue('password') === value) {
                    return Promise.resolve();
                  }
                  return Promise.reject(new Error(t('changePassword.passwordMismatch')));
                },
              }),
            ]}
          >
            <Input.Password
              prefix={<LockOutlined />}
              placeholder={t('changePassword.confirmPassword')}
              data-testid="confirm-password"
            />
          </Form.Item>

          <Form.Item>
            <Button
              type="primary"
              htmlType="submit"
              loading={loading}
              block
              data-testid="change-password-submit"
            >
              {t('changePassword.submit')}
            </Button>
          </Form.Item>
        </Form>
      </Card>
    </div>
  );
};

export default ChangePassword;