/**
 * Dashboard Page Component
 * Generated by Zhuang
 */
import React, { useState, useEffect, useCallback } from 'react';
import { useNavigate } from 'react-router-dom';
import { Card, Row, Col, Statistic, Typography, message, Spin, Alert, Tooltip } from 'antd';
import { HeartOutlined, FileTextOutlined, CalendarOutlined } from '@ant-design/icons';
import { healthAPI } from '../services/api';
import HealthChart from '../components/HealthChart';
import HealthStandardsReference from '../components/HealthStandardsReference';
import { useMember } from '../context/MemberContext';
import { useTranslation } from 'react-i18next';
import { parseServerTime } from '../utils/date';
import { isAuthenticated } from '../utils/auth';

const { Title } = Typography;

const Dashboard = () => {
  const { t } = useTranslation();
  const navigate = useNavigate();
  const [loading, setLoading] = useState(true);
  const [statistics, setStatistics] = useState({
    totalRecords: 0,
    thisWeekRecords: 0,
    avgSystolic: 0,
    avgDiastolic: 0,
    avgHeartRate: 0,
  });
  const [recentRecords, setRecentRecords] = useState([]);
  const [thresholdInfo, setThresholdInfo] = useState(null);
  const { selectedMemberId } = useMember();

  const fetchDashboardData = useCallback(async () => {
    // Prevent API calls if user is not authenticated (e.g., during logout)
    if (!isAuthenticated()) {
      return;
    }
    
    try {
      setLoading(true);
      
      const params = { page: 1, size: 50 }; // Generated by Zhuang: backend expects 'size'
      if (selectedMemberId !== undefined && selectedMemberId !== null) {
        params.subject_member_id = selectedMemberId;
      }

      const [recordsResponse, thresholdResponse] = await Promise.all([
        healthAPI.getRecords(params),
        healthAPI.getActiveThreshold().catch((error) => {
          console.warn('Failed to fetch active thresholds for dashboard', error);
          return null;
        })
      ]);

      const records = recordsResponse.data.records || [];
      setRecentRecords(records.slice(0, 10)); // Keep only recent 10 for display
      
      // Calculate statistics
      const stats = calculateStatistics(records);
      setStatistics(stats);

      if (thresholdResponse?.data) {
        const data = thresholdResponse.data;
        let payload = {};
        
        // Handle different response structures
        if (data.profile && data.profile.payload) {
          try {
            payload = typeof data.profile.payload === 'string' 
              ? JSON.parse(data.profile.payload) 
              : data.profile.payload;
          } catch (e) {
            console.error('Failed to parse threshold payload', e);
          }
        } else if (data.payload) {
           payload = data.payload;
        }

        setThresholdInfo({
          version: data.version || 1,
          payload: payload
        });
      } else {
        setThresholdInfo(null);
      }
      
    } catch (error) {
      console.error('Failed to fetch dashboard data:', error);
      // Silent fail on 401 (logout scenario)
      if (error.response?.status !== 401) {
        message.error(t('health.messages.loadFail'));
      }
    } finally {
      setLoading(false);
    }
  }, [selectedMemberId, t]);

  useEffect(() => {
    fetchDashboardData();
  }, [fetchDashboardData]);

  const calculateStatistics = (records) => {
    if (!records.length) {
      return {
        totalRecords: 0,
        thisWeekRecords: 0,
        avgSystolic: 0,
        avgDiastolic: 0,
        avgHeartRate: 0,
      };
    }

    // Get current week's records
    const oneWeekAgo = new Date();
    oneWeekAgo.setDate(oneWeekAgo.getDate() - 7);
    
    const thisWeekRecords = records.filter(record => 
      parseServerTime(record.timestamp).toDate() >= oneWeekAgo
    );

    // Calculate averages (coerce values to numbers and validate)
    const getNum = (v) => {
      const n = Number(v);
      return Number.isFinite(n) ? n : 0;
    };

    const validRecords = records.filter(r => getNum(r.systolic) > 0 && getNum(r.diastolic) > 0);
    const validHeartRateRecords = records.filter(r => getNum(r.heart_rate) > 0);

    const totalSystolic = validRecords.reduce((sum, r) => sum + getNum(r.systolic), 0);
    const totalDiastolic = validRecords.reduce((sum, r) => sum + getNum(r.diastolic), 0);
    const totalHeartRate = validHeartRateRecords.reduce((sum, r) => sum + getNum(r.heart_rate), 0);

    return {
      totalRecords: records.length,
      thisWeekRecords: thisWeekRecords.length,
  avgSystolic: validRecords.length ? Math.round(totalSystolic / validRecords.length) : 0,
  avgDiastolic: validRecords.length ? Math.round(totalDiastolic / validRecords.length) : 0,
  avgHeartRate: validHeartRateRecords.length ? Math.round(totalHeartRate / validHeartRateRecords.length) : 0,
    };
  };

  if (loading) {
    return (
      <div style={{ textAlign: 'center', padding: '50px' }}>
        <Spin size="large" />
      </div>
    );
  }

  return (
    <div>
      <div className="page-header">
  <Title level={2}>{t('dashboard.title')}</Title>
      </div>

      {/* Threshold Info - Replaced by HealthStandardsReference */}
      <HealthStandardsReference config={thresholdInfo} />

      {/* Statistics Cards */}
      <Row gutter={[16, 16]} style={{ marginBottom: 24 }}>
        <Col xs={24} sm={12} md={8} lg={6}>
          <Tooltip title={t('dashboard.clickToView')}>
            <Card 
              hoverable 
              onClick={() => navigate('/health-records')}
              style={{ cursor: 'pointer' }}
            >
              <Statistic
                title={t('dashboard.totalRecords')}
                value={statistics.totalRecords}
                prefix={<FileTextOutlined />}
                valueStyle={{ color: '#3f8600' }}
              />
            </Card>
          </Tooltip>
        </Col>
        <Col xs={24} sm={12} md={8} lg={6}>
          <Tooltip title={t('dashboard.clickToView')}>
            <Card 
              hoverable
              onClick={() => navigate('/health-records')}
              style={{ cursor: 'pointer' }}
            >
              <Statistic
                title={t('dashboard.thisWeek')}
                value={statistics.thisWeekRecords}
                prefix={<CalendarOutlined />}
                valueStyle={{ color: '#1890ff' }}
              />
            </Card>
          </Tooltip>
        </Col>
        <Col xs={24} sm={12} md={8} lg={6}>
          <Card>
            <Statistic
              title={t('dashboard.avgSystolic')}
              value={statistics.avgSystolic}
              suffix="mmHg"
              prefix={<HeartOutlined />}
              valueStyle={{ color: '#cf1322' }}
            />
          </Card>
        </Col>
        <Col xs={24} sm={12} md={8} lg={6}>
          <Card>
            <Statistic
              title={t('dashboard.avgDiastolic')}
              value={statistics.avgDiastolic}
              suffix="mmHg"
              prefix={<HeartOutlined />}
              valueStyle={{ color: '#cf1322' }}
            />
          </Card>
        </Col>
        <Col xs={24} sm={12} md={8} lg={6}>
          <Card>
            <Statistic
              title={t('dashboard.avgHeartRate')}
              value={statistics.avgHeartRate}
              suffix="bpm"
              prefix={<HeartOutlined />}
              valueStyle={{ color: '#722ed1' }}
            />
          </Card>
        </Col>
      </Row>

      {/* Health Chart */}
      <Card title={t('dashboard.chartTitle')} className="chart-container">
        <HealthChart records={recentRecords} thresholdConfig={thresholdInfo} />
      </Card>
    </div>
  );
};

export default Dashboard;
