/**
 * Health Records Page Component
 * Generated by Zhuang
 */
import React, { useState, useEffect, useCallback } from 'react';
import {
  Card,
  Button,
  Table,
  Modal,
  Form,
  Input,
  InputNumber,
  DatePicker,
  Tag,
  Space,
  message,
  Popconfirm,
  Row,
  Col,
  Typography,
} from 'antd';
import {
  PlusOutlined,
  EditOutlined,
  DeleteOutlined,
  DownloadOutlined,
} from '@ant-design/icons';
import dayjs from 'dayjs';
import { healthAPI } from '../services/api';
import { useMember } from '../context/MemberContext';
import TagSelector from '../components/TagSelector';

const { TextArea } = Input;
const { Title } = Typography;

const HealthRecords = () => {
  const [records, setRecords] = useState([]);
  const [loading, setLoading] = useState(false);
  const [modalVisible, setModalVisible] = useState(false);
  const [editingRecord, setEditingRecord] = useState(null);
  const [form] = Form.useForm();
  const [pagination, setPagination] = useState({
    current: 1,
    pageSize: 10,
    total: 0,
  });
  const { selectedMemberId } = useMember();
  const [filters, setFilters] = useState({
    tags: [],
    dateRange: null,
  });
  // Generated by Zhuang: dynamic tag options
  const [tagOptions, setTagOptions] = useState([]);

  const fetchRecords = useCallback(async () => {
    try {
      setLoading(true);
      
      const params = {
        page: pagination.current,
        size: pagination.pageSize, // Generated by Zhuang: backend expects 'size'
      };

      if (filters.tags.length) {
        params.tags = filters.tags.join(',');
      }

      if (filters.dateRange) {
        params.date_from = filters.dateRange[0].startOf('day').toDate().toISOString();
        params.date_to = filters.dateRange[1].endOf('day').toDate().toISOString();
      }

  if (selectedMemberId !== undefined && selectedMemberId !== null) {
        params.subject_member_id = selectedMemberId;
      }

  const response = await healthAPI.getRecords(params);
      const data = response.data;

      setRecords(data.records || []);
  // Generated by Zhuang: collect unique tags from current page
  const uniq = new Set();
  (data.records || []).forEach(r => (r.tags || []).forEach(t => uniq.add(t)));
  setTagOptions(prev => Array.from(new Set([...(prev || []), ...Array.from(uniq)])));
      // Only update when total actually changes to avoid unnecessary re-renders
      setPagination(prev => {
        const newTotal = data.pagination?.total || 0;
        if (prev.total === newTotal) return prev;
        return { ...prev, total: newTotal };
      });
    } catch (error) {
      console.error('Failed to fetch records:', error);
      message.error('获取健康记录失败');
    } finally {
      setLoading(false);
    }
  }, [pagination, filters, selectedMemberId]); // Generated by Zhuang

  // Generated by Zhuang: also fetch a larger set once per member change
  useEffect(() => {
    const fetchAllForMember = async () => {
      try {
        const params = { page: 1, size: 1000 };
        if (selectedMemberId !== undefined && selectedMemberId !== null) {
          params.subject_member_id = selectedMemberId;
        }
        const resp = await healthAPI.getRecords(params);
        const uniq = new Set();
        (resp.data?.records || []).forEach(r => (r.tags || []).forEach(t => uniq.add(t)));
        setTagOptions(Array.from(uniq));
      } catch (e) {
        // ignore
      }
    };
    fetchAllForMember();
  }, [selectedMemberId]);

  useEffect(() => {
    fetchRecords();
  }, [fetchRecords]);

  const handleAdd = () => {
  setEditingRecord(null);
    form.resetFields();
    form.setFieldsValue({
      timestamp: dayjs(),
    });
    setModalVisible(true);
  };

  const handleEdit = (record) => {
    setEditingRecord(record);
    form.setFieldsValue({
      systolic_pressure: record.systolic,
      diastolic_pressure: record.diastolic,
      heart_rate: record.heart_rate,
      timestamp: dayjs(record.timestamp),
      tags: record.tags || [],
      notes: record.note,
    });
    setModalVisible(true);
  };

  const handleDelete = async (recordId) => {
    try {
      await healthAPI.deleteRecord(recordId);
      message.success('删除成功');
      fetchRecords();
    } catch (error) {
      console.error('Failed to delete record:', error);
      message.error('删除失败');
    }
  };

  const handleSubmit = async (values) => {
    try {
      const recordData = {
        systolic: values.systolic_pressure,
        diastolic: values.diastolic_pressure,
        heart_rate: values.heart_rate,
        timestamp: values.timestamp.toISOString(),
        tags: values.tags || [],
        note: values.notes,
      };

  if (selectedMemberId !== undefined && selectedMemberId !== null) {
        recordData.subject_member_id = selectedMemberId;
      }

      if (editingRecord) {
        await healthAPI.updateRecord(editingRecord.id, recordData);
        message.success('更新成功');
      } else {
        await healthAPI.createRecord(recordData);
        message.success('添加成功');
      }

      setModalVisible(false);
      fetchRecords();
    } catch (error) {
      console.error('Failed to save record:', error);
      const errorMessage = error.response?.data?.message || '保存失败';
      message.error(errorMessage);
    }
  };

  const handleTableChange = (newPagination) => {
    setPagination(prev => ({
      ...prev,
      current: newPagination.current,
      pageSize: newPagination.pageSize,
    }));
  };

  // Generated by Zhuang: inline filter handlers
  const handleDateRangeChange = (range) => {
    setFilters(prev => ({ ...prev, dateRange: range }));
    setPagination(prev => ({ ...prev, current: 1 }));
  };

  const handleTagsChange = (tags) => {
    setFilters(prev => ({ ...prev, tags }));
    setPagination(prev => ({ ...prev, current: 1 }));
  };

  const removeTagFilter = (tag) => {
    setFilters(prev => ({ ...prev, tags: (prev.tags || []).filter(t => t !== tag) }));
    setPagination(prev => ({ ...prev, current: 1 }));
  };

  const columns = [
    {
      title: '时间',
      dataIndex: 'timestamp',
      key: 'timestamp',
      render: (timestamp) => dayjs(timestamp).format('YYYY-MM-DD HH:mm'),
      sorter: true,
    },
    {
      title: '血压',
      key: 'blood_pressure',
      render: (_, record) => {
        // Backend fields are `systolic` and `diastolic`
        if (record.systolic && record.diastolic) {
          return `${record.systolic}/${record.diastolic} mmHg`;
        }
        return '-';
      },
    },
    {
      title: '心率',
      dataIndex: 'heart_rate',
      key: 'heart_rate',
      render: (heartRate) => heartRate ? `${heartRate} bpm` : '-',
    },
    {
      title: '标签',
      dataIndex: 'tags',
      key: 'tags',
      render: (tags) => (
        <Space wrap>
          {(tags || []).map(tag => (
            <Tag key={tag} color="blue">{tag}</Tag>
          ))}
        </Space>
      ),
    },
    {
      title: '备注',
  dataIndex: 'note',
  key: 'note',
  render: (note) => note || '-',
    },
    {
      title: '操作',
      key: 'actions',
      render: (_, record) => (
        <Space>
          <Button
            type="text"
            icon={<EditOutlined />}
            onClick={() => handleEdit(record)}
          >
            编辑
          </Button>
          <Popconfirm
            title="确定要删除这条记录吗？"
            onConfirm={() => handleDelete(record.id)}
            okText="确定"
            cancelText="取消"
          >
            <Button
              type="text"
              danger
              icon={<DeleteOutlined />}
            >
              删除
            </Button>
          </Popconfirm>
        </Space>
      ),
    },
  ];

  const handleExport = async () => {
    try {
      const params = {};
      if (filters.tags?.length) params.tags = filters.tags.join(',');
      if (filters.dateRange) {
        params.date_from = filters.dateRange[0].startOf('day').toDate().toISOString();
        params.date_to = filters.dateRange[1].endOf('day').toDate().toISOString();
      }
      if (selectedMemberId !== undefined && selectedMemberId !== null) {
        params.subject_member_id = selectedMemberId;
      }
      const resp = await healthAPI.exportCsv(params);
      const blob = new Blob([resp.data], { type: 'text/csv;charset=utf-8' });
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      // Generated by Zhuang: derive filename from Content-Disposition (supports RFC 5987 filename*)
      const cd = resp.headers && (resp.headers['content-disposition'] || resp.headers['Content-Disposition']);
      let filename = 'health_records.csv';
      if (cd) {
        // Try filename* first (RFC 5987)
        const fnStarMatch = /filename\*=UTF-8''([^;\n]+)/i.exec(cd);
        if (fnStarMatch && fnStarMatch[1]) {
          try {
            filename = decodeURIComponent(fnStarMatch[1]);
          } catch (_) { /* ignore decode error */ }
        } else {
          const fnMatch = /filename=\"?([^;\n\"]+)\"?/i.exec(cd);
          if (fnMatch && fnMatch[1]) {
            filename = fnMatch[1];
          }
        }
      }
      a.download = filename;
      a.click();
      window.URL.revokeObjectURL(url);
    } catch (e) {
      console.error('Export CSV failed', e);
      const msg = e.response?.data?.message || '导出失败';
      message.error(msg);
    }
  };

  return (
    <div>
      <div style={{ marginBottom: 8, display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 12 }}>
        <Title level={2}>健康记录</Title>
        <Space size={12} wrap>
          <Button
            icon={<DownloadOutlined />}
            onClick={handleExport}
          >
            导出 CSV
          </Button>
          <Button
            type="primary"
            icon={<PlusOutlined />}
            onClick={handleAdd}
          >
            添加记录
          </Button>
        </Space>
      </div>

      {/* Labeled inline filter bar - Generated by Zhuang */}
      <Card size="small" style={{ marginBottom: 8 }} bodyStyle={{ padding: 12 }}>
        <Form
          layout="inline"
          // Generated by Zhuang: keep filters strictly on one row
          style={{ display: 'flex', alignItems: 'center', gap: 12, flexWrap: 'nowrap' }}
          className="filter-bar"
        >
          <Form.Item label="日期" style={{ marginBottom: 0, flex: '0 0 auto' }}>
            <DatePicker.RangePicker
              data-testid="filter-date-range"
              value={filters.dateRange}
              onChange={handleDateRangeChange}
              style={{ width: 320 }}
            />
          </Form.Item>

          <Form.Item
            label="标签"
            // Generated by Zhuang: allow TagSelector to grow but also shrink to stay in one line
            style={{ marginBottom: 0, flex: '1 1 420px', minWidth: 260, alignItems: 'center' }}
            className="filter-tags-item"
          >
            <TagSelector
              data-testid="filter-tags"
              value={filters.tags}
              onChange={handleTagsChange}
              placeholder="输入或选择标签进行筛选"
              // Generated by Zhuang: width fills container; allow shrink with smaller minWidth
              style={{ width: '100%', minWidth: 260 }}
              maxTagCount="responsive"
              dropdownMatchSelectWidth={false}
              listHeight={320}
              options={tagOptions}
            />
          </Form.Item>

          <Form.Item style={{ marginLeft: 'auto', marginBottom: 0 }}>
            <Button onClick={() => { setFilters({ tags: [], dateRange: null }); setPagination(prev => ({ ...prev, current: 1 })); }}>清除筛选</Button>
          </Form.Item>
        </Form>
      </Card>

  {/* Removed extra date chip row to avoid duplication - Generated by Zhuang */}

      <Card>
        <Table
          columns={columns}
          dataSource={records}
          rowKey="id"
          loading={loading}
          pagination={{
            ...pagination,
            showSizeChanger: true,
            showQuickJumper: true,
            showTotal: (total, range) => `第 ${range[0]}-${range[1]} 条，共 ${total} 条`,
          }}
          onChange={handleTableChange}
          scroll={{ x: 'max-content' }}
        />
      </Card>

      {/* Add/Edit Modal */}
      <Modal
        title={editingRecord ? '编辑健康记录' : '添加健康记录'}
        open={modalVisible}
        onCancel={() => setModalVisible(false)}
        footer={null}
        width={600}
      >
        <Form
          form={form}
          layout="vertical"
          onFinish={handleSubmit}
        >
          <Form.Item
            name="timestamp"
            label="记录时间"
            rules={[{ required: true, message: '请选择记录时间' }]}
          >
            <DatePicker
              data-testid="timestamp"
              showTime
              style={{ width: '100%' }}
              format="YYYY-MM-DD HH:mm"
            />
          </Form.Item>

          <Row gutter={16}>
            <Col span={12}>
              <Form.Item
                name="systolic_pressure"
                label="收缩压 (mmHg)"
                rules={[
                  { required: true, message: '请输入收缩压' },
                  { type: 'number', min: 50, max: 250, message: '收缩压范围：50-250 mmHg' }
                ]}
              >
                <InputNumber
                  data-testid="systolic-pressure"
                  placeholder="收缩压"
                  style={{ width: '100%' }}
                  min={50}
                  max={250}
                />
              </Form.Item>
            </Col>
            <Col span={12}>
              <Form.Item
                name="diastolic_pressure"
                label="舒张压 (mmHg)"
                rules={[
                  { required: true, message: '请输入舒张压' },
                  { type: 'number', min: 50, max: 250, message: '舒张压范围：50-250 mmHg' }
                ]}
              >
                <InputNumber
                  data-testid="diastolic-pressure"
                  placeholder="舒张压"
                  style={{ width: '100%' }}
                  min={50}
                  max={250}
                />
              </Form.Item>
            </Col>
          </Row>

          <Form.Item
            name="heart_rate"
            label="心率 (bpm)"
            rules={[
              { type: 'number', min: 30, max: 200, message: '心率范围：30-200 bpm' }
            ]}
          >
            <InputNumber
              data-testid="heart-rate"
              placeholder="心率"
              style={{ width: '100%' }}
              min={30}
              max={200}
            />
          </Form.Item>

          <Form.Item
            name="tags"
            label="标签"
          >
            <TagSelector />
          </Form.Item>

          <Form.Item
            name="notes"
            label="备注"
          >
            <TextArea
              data-testid="notes"
              placeholder="可选填写备注信息"
              rows={3}
            />
          </Form.Item>

          <Form.Item>
            <Space>
              <Button type="primary" htmlType="submit">
                {editingRecord ? '更新' : '添加'}
              </Button>
              <Button onClick={() => setModalVisible(false)}>
                取消
              </Button>
            </Space>
          </Form.Item>
        </Form>
      </Modal>

  {/* Generated by Zhuang */}
    </div>
  );
};

export default HealthRecords;
