/**
 * Medical History Page - CRUD for family member medical history records.
 * Generated by Copilot
 */
import React, { useState, useEffect, useCallback } from 'react';
import {
  Card,
  Button,
  Table,
  Modal,
  Form,
  Input,
  DatePicker,
  Switch,
  Space,
  message,
  Popconfirm,
  Tag,
  Typography,
} from 'antd';
import { PlusOutlined, EditOutlined, DeleteOutlined } from '@ant-design/icons';
import dayjs from 'dayjs';
import { medicalHistoryAPI } from '../services/api';
import { useMember } from '../context/MemberContext';
import { useTranslation } from 'react-i18next';

const { Title } = Typography;
const { TextArea } = Input;

const MedicalHistory = () => {
  const { t } = useTranslation();
  const { selectedMemberId } = useMember();

  const [records, setRecords] = useState([]);
  const [loading, setLoading] = useState(false);
  const [modalVisible, setModalVisible] = useState(false);
  const [editingRecord, setEditingRecord] = useState(null);
  const [form] = Form.useForm();
  const [pagination, setPagination] = useState({ current: 1, pageSize: 10, total: 0 });

  // ---------------------------------------------------------------------------
  // Fetch
  // ---------------------------------------------------------------------------

  const fetchRecords = useCallback(
    async (page = 1, pageSize = 10) => {
      if (!selectedMemberId) return;
      setLoading(true);
      try {
        const resp = await medicalHistoryAPI.list({
          member_id: selectedMemberId,
          page,
          size: pageSize,
        });
        const { histories, pagination: pg } = resp.data;
        setRecords(histories || []);
        setPagination({ current: pg.page, pageSize: pg.size, total: pg.total });
      } catch {
        message.error(t('medicalHistory.load.fail'));
      } finally {
        setLoading(false);
      }
    },
    [selectedMemberId, t]
  );

  useEffect(() => {
    fetchRecords();
  }, [fetchRecords]);

  // ---------------------------------------------------------------------------
  // Modal helpers
  // ---------------------------------------------------------------------------

  const openAdd = () => {
    setEditingRecord(null);
    setModalVisible(true);
  };

  const openEdit = (record) => {
    setEditingRecord(record);
    setModalVisible(true);
  };

  useEffect(() => {
    if (!modalVisible) {
      return;
    }

    if (editingRecord) {
      form.setFieldsValue({
        disease_name: editingRecord.disease_name,
        onset_date: editingRecord.onset_date ? dayjs(editingRecord.onset_date) : null,
        description: editingRecord.description || '',
        is_ongoing: editingRecord.is_ongoing,
        is_on_medication: editingRecord.is_on_medication,
      });
      return;
    }

    form.resetFields();
    form.setFieldsValue({ is_ongoing: true, is_on_medication: false });
  }, [modalVisible, editingRecord, form]);

  const handleCancel = () => {
    setModalVisible(false);
    setEditingRecord(null);
  };

  // ---------------------------------------------------------------------------
  // Submit
  // ---------------------------------------------------------------------------

  const handleSubmit = async () => {
    try {
      const values = await form.validateFields();
      const payload = {
        ...values,
        onset_date: values.onset_date ? values.onset_date.format('YYYY-MM-DD') : undefined,
        member_id: selectedMemberId,
      };

      if (editingRecord) {
        await medicalHistoryAPI.update(editingRecord.id, payload);
        message.success(t('medicalHistory.update.success'));
      } else {
        await medicalHistoryAPI.create(payload);
        message.success(t('medicalHistory.add.success'));
      }

      setModalVisible(false);
      form.resetFields();
      setEditingRecord(null);
      fetchRecords(pagination.current, pagination.pageSize);
    } catch (err) {
      if (err?.errorFields) return; // form validation failure, antd handles it
      const detail = err?.response?.data?.message || t('medicalHistory.save.fail');
      message.error(detail);
    }
  };

  // ---------------------------------------------------------------------------
  // Delete
  // ---------------------------------------------------------------------------

  const handleDelete = async (id) => {
    try {
      await medicalHistoryAPI.remove(id);
      message.success(t('medicalHistory.delete.success'));
      // Go back one page if the last item on a page > 1 was just deleted
      const newTotal = pagination.total - 1;
      const maxPage = Math.max(1, Math.ceil(newTotal / pagination.pageSize));
      const targetPage = Math.min(pagination.current, maxPage);
      fetchRecords(targetPage, pagination.pageSize);
    } catch {
      message.error(t('medicalHistory.delete.fail'));
    }
  };

  // ---------------------------------------------------------------------------
  // Table columns
  // ---------------------------------------------------------------------------

  const columns = [
    {
      title: t('medicalHistory.diseaseName'),
      dataIndex: 'disease_name',
      key: 'disease_name',
      width: 180,
    },
    {
      title: t('medicalHistory.onsetDate'),
      dataIndex: 'onset_date',
      key: 'onset_date',
      width: 130,
      render: (val) => val || '-',
    },
    {
      title: t('medicalHistory.isOngoing'),
      dataIndex: 'is_ongoing',
      key: 'is_ongoing',
      width: 110,
      render: (val) =>
        val ? (
          <Tag color="orange">{t('medicalHistory.ongoing')}</Tag>
        ) : (
          <Tag color="green">{t('medicalHistory.resolved')}</Tag>
        ),
    },
    {
      title: t('medicalHistory.isOnMedication'),
      dataIndex: 'is_on_medication',
      key: 'is_on_medication',
      width: 110,
      render: (val) =>
        val ? (
          <Tag color="blue">{t('medicalHistory.yes')}</Tag>
        ) : (
          <Tag>{t('medicalHistory.no')}</Tag>
        ),
    },
    {
      title: t('medicalHistory.description'),
      dataIndex: 'description',
      key: 'description',
      ellipsis: true,
      render: (val) => val || '-',
    },
    {
      title: t('health.columns.actions'),
      key: 'actions',
      width: 120,
      render: (_, record) => (
        <Space>
          <Button
            type="link"
            size="small"
            icon={<EditOutlined />}
            onClick={() => openEdit(record)}
          />
          <Popconfirm
            title={t('medicalHistory.deleteConfirm')}
            onConfirm={() => handleDelete(record.id)}
            okText={t('common.confirm')}
            cancelText={t('common.close')}
          >
            <Button danger type="link" size="small" icon={<DeleteOutlined />} />
          </Popconfirm>
        </Space>
      ),
    },
  ];

  // ---------------------------------------------------------------------------
  // Render
  // ---------------------------------------------------------------------------

  return (
    <div style={{ padding: '24px' }}>
      <Card
        title={
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: 8 }}>
            <Title level={4} style={{ margin: 0 }}>
              {t('medicalHistory.title')}
            </Title>
            <Button type="primary" icon={<PlusOutlined />} onClick={openAdd}>
              {t('medicalHistory.addRecord')}
            </Button>
          </div>
        }
      >
        <Table
          rowKey="id"
          dataSource={records}
          columns={columns}
          loading={loading}
          pagination={{
            current: pagination.current,
            pageSize: pagination.pageSize,
            total: pagination.total,
            showSizeChanger: true,
            pageSizeOptions: ['10', '20', '50'],
            onChange: (page, pageSize) => fetchRecords(page, pageSize),
          }}
          scroll={{ x: 700 }}
        />
      </Card>

      {/* Add / Edit Modal */}
      <Modal
        title={editingRecord ? t('medicalHistory.editRecord') : t('medicalHistory.addRecord')}
        open={modalVisible}
        onOk={handleSubmit}
        onCancel={handleCancel}
        okText={t('common.confirm')}
        cancelText={t('common.close')}
        forceRender
        destroyOnClose
      >
        <Form form={form} layout="vertical" style={{ marginTop: 16 }}>
          <Form.Item
            name="disease_name"
            label={t('medicalHistory.diseaseName')}
            rules={[
              {
                required: true,
                message: t('common.requiredField', { field: t('medicalHistory.diseaseName') }),
              },
              { max: 120, message: t('common.maxLength', { max: 120 }) },
            ]}
          >
            <Input placeholder={t('medicalHistory.namePlaceholder')} />
          </Form.Item>

          <Form.Item
            name="onset_date"
            label={t('medicalHistory.onsetDate')}
            rules={[
              {
                required: true,
                message: t('common.requiredField', { field: t('medicalHistory.onsetDate') }),
              },
            ]}
          >
            <DatePicker style={{ width: '100%' }} />
          </Form.Item>

          <Form.Item name="description" label={t('medicalHistory.description')}>
            <TextArea rows={3} placeholder={t('medicalHistory.descriptionPlaceholder')} />
          </Form.Item>

          <Form.Item
            name="is_ongoing"
            label={t('medicalHistory.isOngoing')}
            valuePropName="checked"
          >
            <Switch
              checkedChildren={t('medicalHistory.yes')}
              unCheckedChildren={t('medicalHistory.no')}
            />
          </Form.Item>

          <Form.Item
            name="is_on_medication"
            label={t('medicalHistory.isOnMedication')}
            valuePropName="checked"
          >
            <Switch
              checkedChildren={t('medicalHistory.yes')}
              unCheckedChildren={t('medicalHistory.no')}
            />
          </Form.Item>
        </Form>
      </Modal>
    </div>
  );
};

export default MedicalHistory;
