/**
 * Medical History Page - CRUD for family member medical history records.
 * Generated by Copilot
 */
import React, { useState, useEffect, useCallback } from 'react';
import {
  Card,
  Button,
  Table,
  Modal,
  Form,
  Input,
  DatePicker,
  Switch,
  Space,
  message,
  Popconfirm,
  Tag,
  Typography,
  Drawer,
  Upload,
  Alert,
} from 'antd';
import { PlusOutlined, EditOutlined, DeleteOutlined, PaperClipOutlined, DownloadOutlined, UploadOutlined } from '@ant-design/icons';
import dayjs from 'dayjs';
import { medicalHistoryAPI } from '../services/api';
import { useMember } from '../context/MemberContext';
import { useTranslation } from 'react-i18next';

const { Title } = Typography;
const { TextArea } = Input;
const MAX_ATTACHMENTS_PER_HISTORY = 10;

const MedicalHistory = () => {
  const { t } = useTranslation();
  const { selectedMemberId } = useMember();

  const [records, setRecords] = useState([]);
  const [loading, setLoading] = useState(false);
  const [modalVisible, setModalVisible] = useState(false);
  const [editingRecord, setEditingRecord] = useState(null);
  const [form] = Form.useForm();
  const [pagination, setPagination] = useState({ current: 1, pageSize: 10, total: 0 });
  const [attachmentDrawerOpen, setAttachmentDrawerOpen] = useState(false);
  const [attachmentHistory, setAttachmentHistory] = useState(null);
  const [attachments, setAttachments] = useState([]);
  const [attachmentsLoading, setAttachmentsLoading] = useState(false);
  const [uploadingAttachment, setUploadingAttachment] = useState(false);
  const [attachmentPagination, setAttachmentPagination] = useState({ current: 1, pageSize: 10, total: 0 });

  // ---------------------------------------------------------------------------
  // Fetch
  // ---------------------------------------------------------------------------

  const fetchRecords = useCallback(
    async (page = 1, pageSize = 10) => {
      if (!selectedMemberId) return;
      setLoading(true);
      try {
        const resp = await medicalHistoryAPI.list({
          member_id: selectedMemberId,
          page,
          size: pageSize,
        });
        const { histories, pagination: pg } = resp.data;
        setRecords(histories || []);
        setPagination({ current: pg.page, pageSize: pg.size, total: pg.total });
      } catch {
        message.error(t('medicalHistory.load.fail'));
      } finally {
        setLoading(false);
      }
    },
    [selectedMemberId, t]
  );

  useEffect(() => {
    fetchRecords();
  }, [fetchRecords]);

  // ---------------------------------------------------------------------------
  // Modal helpers
  // ---------------------------------------------------------------------------

  const openAdd = () => {
    setEditingRecord(null);
    setModalVisible(true);
  };

  const openEdit = (record) => {
    setEditingRecord(record);
    setModalVisible(true);
  };

  useEffect(() => {
    if (!modalVisible) {
      return;
    }

    if (editingRecord) {
      form.setFieldsValue({
        disease_name: editingRecord.disease_name,
        onset_date: editingRecord.onset_date ? dayjs(editingRecord.onset_date) : null,
        description: editingRecord.description || '',
        is_ongoing: editingRecord.is_ongoing,
        is_on_medication: editingRecord.is_on_medication,
      });
      return;
    }

    form.resetFields();
    form.setFieldsValue({ is_ongoing: true, is_on_medication: false });
  }, [modalVisible, editingRecord, form]);

  const handleCancel = () => {
    setModalVisible(false);
    setEditingRecord(null);
  };

  // ---------------------------------------------------------------------------
  // Submit
  // ---------------------------------------------------------------------------

  const handleSubmit = async () => {
    try {
      const values = await form.validateFields();
      const payload = {
        ...values,
        onset_date: values.onset_date ? values.onset_date.format('YYYY-MM-DD') : undefined,
        member_id: selectedMemberId,
      };

      if (editingRecord) {
        await medicalHistoryAPI.update(editingRecord.id, payload);
        message.success(t('medicalHistory.update.success'));
      } else {
        await medicalHistoryAPI.create(payload);
        message.success(t('medicalHistory.add.success'));
      }

      setModalVisible(false);
      form.resetFields();
      setEditingRecord(null);
      fetchRecords(pagination.current, pagination.pageSize);
    } catch (err) {
      if (err?.errorFields) return; // form validation failure, antd handles it
      const detail = err?.response?.data?.message || t('medicalHistory.save.fail');
      message.error(detail);
    }
  };

  // ---------------------------------------------------------------------------
  // Delete
  // ---------------------------------------------------------------------------

  const handleDelete = async (id) => {
    try {
      await medicalHistoryAPI.remove(id);
      message.success(t('medicalHistory.delete.success'));
      // Go back one page if the last item on a page > 1 was just deleted
      const newTotal = pagination.total - 1;
      const maxPage = Math.max(1, Math.ceil(newTotal / pagination.pageSize));
      const targetPage = Math.min(pagination.current, maxPage);
      fetchRecords(targetPage, pagination.pageSize);
    } catch {
      message.error(t('medicalHistory.delete.fail'));
    }
  };

  const fetchAttachments = useCallback(async (historyId, page = 1, pageSize = 10) => {
    if (!historyId) return;
    setAttachmentsLoading(true);
    try {
      const resp = await medicalHistoryAPI.listAttachments(historyId, { page, size: pageSize });
      setAttachments(resp.data.attachments || []);
      const pg = resp.data.pagination || { page, size: pageSize, total: 0 };
      setAttachmentPagination({ current: pg.page, pageSize: pg.size, total: pg.total });
    } catch {
      message.error(t('medicalHistory.attachments.loadFail'));
    } finally {
      setAttachmentsLoading(false);
    }
  }, [t]);

  const openAttachmentDrawer = (record) => {
    setAttachmentHistory(record);
    setAttachmentDrawerOpen(true);
    fetchAttachments(record.id, 1, attachmentPagination.pageSize);
  };

  const closeAttachmentDrawer = () => {
    setAttachmentDrawerOpen(false);
    setAttachmentHistory(null);
    setAttachments([]);
  };

  const handleAttachmentUpload = async ({ file, onSuccess, onError }) => {
    if (!attachmentHistory) {
      onError?.(new Error('No history selected'));
      return;
    }
    if (attachmentPagination.total >= MAX_ATTACHMENTS_PER_HISTORY) {
      const limitError = new Error('attachment limit reached');
      message.error(t('medicalHistory.attachments.limitReached', { max: MAX_ATTACHMENTS_PER_HISTORY }));
      onError?.(limitError);
      return;
    }
    const ext = `.${(file.name || '').split('.').pop()?.toLowerCase() || ''}`;
    const allowed = ['.jpg', '.jpeg', '.png', '.pdf', '.doc', '.docx'];
    const maxSize = 20 * 1024 * 1024;
    if (!allowed.includes(ext)) {
      message.error(t('medicalHistory.attachments.typeNotAllowed'));
      onError?.(new Error('type not allowed'));
      return;
    }
    if (file.size > maxSize) {
      message.error(t('medicalHistory.attachments.sizeExceeded'));
      onError?.(new Error('size exceeded'));
      return;
    }

    try {
      setUploadingAttachment(true);
      const formData = new FormData();
      formData.append('file', file);
      await medicalHistoryAPI.uploadAttachment(attachmentHistory.id, formData);
      message.success(t('medicalHistory.attachments.uploadSuccess'));
      await fetchAttachments(
        attachmentHistory.id,
        attachmentPagination.current,
        attachmentPagination.pageSize
      );
      onSuccess?.();
    } catch (err) {
      message.error(err?.response?.data?.message || t('medicalHistory.attachments.uploadFail'));
      onError?.(err);
    } finally {
      setUploadingAttachment(false);
    }
  };

  const handleAttachmentDownload = async (item) => {
    if (!attachmentHistory) return;
    try {
      const resp = await medicalHistoryAPI.downloadAttachment(attachmentHistory.id, item.id);
      const blob = new Blob([resp.data], { type: item.mime_type || 'application/octet-stream' });
      const href = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = href;
      a.download = item.file_name || `attachment_${item.id}`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(href);
    } catch {
      message.error(t('medicalHistory.attachments.downloadFail'));
    }
  };

  const handleAttachmentDelete = async (item) => {
    if (!attachmentHistory) return;
    try {
      await medicalHistoryAPI.removeAttachment(attachmentHistory.id, item.id);
      message.success(t('medicalHistory.attachments.deleteSuccess'));
      const newTotal = attachmentPagination.total - 1;
      const maxPage = Math.max(1, Math.ceil(newTotal / attachmentPagination.pageSize));
      const targetPage = Math.min(attachmentPagination.current, maxPage);
      await fetchAttachments(attachmentHistory.id, targetPage, attachmentPagination.pageSize);
    } catch {
      message.error(t('medicalHistory.attachments.deleteFail'));
    }
  };

  // ---------------------------------------------------------------------------
  // Table columns
  // ---------------------------------------------------------------------------

  const columns = [
    {
      title: t('medicalHistory.diseaseName'),
      dataIndex: 'disease_name',
      key: 'disease_name',
      width: 180,
    },
    {
      title: t('medicalHistory.onsetDate'),
      dataIndex: 'onset_date',
      key: 'onset_date',
      width: 130,
      render: (val) => val || '-',
    },
    {
      title: t('medicalHistory.isOngoing'),
      dataIndex: 'is_ongoing',
      key: 'is_ongoing',
      width: 110,
      render: (val) =>
        val ? (
          <Tag color="orange">{t('medicalHistory.ongoing')}</Tag>
        ) : (
          <Tag color="green">{t('medicalHistory.resolved')}</Tag>
        ),
    },
    {
      title: t('medicalHistory.isOnMedication'),
      dataIndex: 'is_on_medication',
      key: 'is_on_medication',
      width: 110,
      render: (val) =>
        val ? (
          <Tag color="blue">{t('medicalHistory.yes')}</Tag>
        ) : (
          <Tag>{t('medicalHistory.no')}</Tag>
        ),
    },
    {
      title: t('medicalHistory.description'),
      dataIndex: 'description',
      key: 'description',
      ellipsis: true,
      render: (val) => val || '-',
    },
    {
      title: t('health.columns.actions'),
      key: 'actions',
      width: 220,
      render: (_, record) => (
        <Space>
          <Button
            type="link"
            size="small"
            icon={<EditOutlined />}
            onClick={() => openEdit(record)}
          />
          <Button
            type="link"
            size="small"
            icon={<PaperClipOutlined />}
            onClick={() => openAttachmentDrawer(record)}
          >
            {t('medicalHistory.attachments.manage')}
          </Button>
          <Popconfirm
            title={t('medicalHistory.deleteConfirm')}
            onConfirm={() => handleDelete(record.id)}
            okText={t('common.confirm')}
            cancelText={t('common.close')}
          >
            <Button danger type="link" size="small" icon={<DeleteOutlined />} />
          </Popconfirm>
        </Space>
      ),
    },
  ];

  // ---------------------------------------------------------------------------
  // Render
  // ---------------------------------------------------------------------------

  return (
    <div style={{ padding: '24px' }}>
      <Card
        title={
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: 8 }}>
            <Title level={4} style={{ margin: 0 }}>
              {t('medicalHistory.title')}
            </Title>
            <Button type="primary" icon={<PlusOutlined />} onClick={openAdd}>
              {t('medicalHistory.addRecord')}
            </Button>
          </div>
        }
      >
        {!selectedMemberId && (
          <Alert
            type="info"
            showIcon
            style={{ marginBottom: 16 }}
            message={t('medicalHistory.attachments.noMemberHint')}
          />
        )}
        {selectedMemberId && !loading && records.length === 0 && (
          <Alert
            type="info"
            showIcon
            style={{ marginBottom: 16 }}
            message={t('medicalHistory.attachments.noRecordHint')}
          />
        )}
        <Table
          rowKey="id"
          dataSource={records}
          columns={columns}
          loading={loading}
          pagination={{
            current: pagination.current,
            pageSize: pagination.pageSize,
            total: pagination.total,
            showSizeChanger: true,
            pageSizeOptions: ['10', '20', '50'],
            onChange: (page, pageSize) => fetchRecords(page, pageSize),
          }}
          scroll={{ x: 700 }}
        />
      </Card>

      <Drawer
        title={`${t('medicalHistory.attachments.title')} - ${attachmentHistory?.disease_name || ''}`}
        open={attachmentDrawerOpen}
        onClose={closeAttachmentDrawer}
        width={760}
      >
        <Space direction="vertical" size={8} style={{ width: '100%', marginBottom: 16 }}>
          <Alert
            type="info"
            showIcon
            message={t('medicalHistory.attachments.entryHint')}
          />
          <div style={{ color: '#595959', fontSize: 14 }}>
            {t('medicalHistory.attachments.count', {
              count: attachmentPagination.total,
              max: MAX_ATTACHMENTS_PER_HISTORY,
            })}
          </div>
        </Space>
        <Space style={{ marginBottom: 16 }}>
          <Upload
            customRequest={handleAttachmentUpload}
            showUploadList={false}
            disabled={uploadingAttachment || attachmentPagination.total >= MAX_ATTACHMENTS_PER_HISTORY}
          >
            <Button icon={<UploadOutlined />} loading={uploadingAttachment}>
              {t('medicalHistory.attachments.upload')}
            </Button>
          </Upload>
        </Space>
        <Table
          rowKey="id"
          dataSource={attachments}
          loading={attachmentsLoading}
          locale={{ emptyText: t('medicalHistory.attachments.empty') }}
          columns={[
            {
              title: t('medicalHistory.attachments.fileName'),
              dataIndex: 'file_name',
              key: 'file_name',
              ellipsis: true,
            },
            {
              title: t('medicalHistory.attachments.fileType'),
              dataIndex: 'file_ext',
              key: 'file_ext',
              width: 120,
            },
            {
              title: t('medicalHistory.attachments.fileSize'),
              dataIndex: 'file_size',
              key: 'file_size',
              width: 140,
              render: (size) => `${(size / 1024).toFixed(1)} KB`,
            },
            {
              title: t('medicalHistory.attachments.uploadedAt'),
              dataIndex: 'created_at',
              key: 'created_at',
              width: 220,
            },
            {
              title: t('health.columns.actions'),
              key: 'actions',
              width: 140,
              render: (_, item) => (
                <Space>
                  <Button
                    type="link"
                    size="small"
                    icon={<DownloadOutlined />}
                    onClick={() => handleAttachmentDownload(item)}
                  />
                  <Popconfirm
                    title={t('medicalHistory.attachments.deleteConfirm')}
                    onConfirm={() => handleAttachmentDelete(item)}
                    okText={t('common.confirm')}
                    cancelText={t('common.close')}
                  >
                    <Button danger type="link" size="small" icon={<DeleteOutlined />} />
                  </Popconfirm>
                </Space>
              ),
            },
          ]}
          pagination={{
            current: attachmentPagination.current,
            pageSize: attachmentPagination.pageSize,
            total: attachmentPagination.total,
            onChange: (page, pageSize) => fetchAttachments(attachmentHistory?.id, page, pageSize),
          }}
        />
      </Drawer>

      {/* Add / Edit Modal */}
      <Modal
        title={editingRecord ? t('medicalHistory.editRecord') : t('medicalHistory.addRecord')}
        open={modalVisible}
        onOk={handleSubmit}
        onCancel={handleCancel}
        okText={t('common.confirm')}
        cancelText={t('common.close')}
        forceRender
        destroyOnClose
      >
        <Form form={form} layout="vertical" style={{ marginTop: 16 }}>
          <Form.Item
            name="disease_name"
            label={t('medicalHistory.diseaseName')}
            rules={[
              {
                required: true,
                message: t('common.requiredField', { field: t('medicalHistory.diseaseName') }),
              },
              { max: 120, message: t('common.maxLength', { max: 120 }) },
            ]}
          >
            <Input placeholder={t('medicalHistory.namePlaceholder')} />
          </Form.Item>

          <Form.Item
            name="onset_date"
            label={t('medicalHistory.onsetDate')}
            rules={[
              {
                required: true,
                message: t('common.requiredField', { field: t('medicalHistory.onsetDate') }),
              },
            ]}
          >
            <DatePicker style={{ width: '100%' }} />
          </Form.Item>

          <Form.Item name="description" label={t('medicalHistory.description')}>
            <TextArea rows={3} placeholder={t('medicalHistory.descriptionPlaceholder')} />
          </Form.Item>

          <Form.Item
            name="is_ongoing"
            label={t('medicalHistory.isOngoing')}
            valuePropName="checked"
          >
            <Switch
              checkedChildren={t('medicalHistory.yes')}
              unCheckedChildren={t('medicalHistory.no')}
            />
          </Form.Item>

          <Form.Item
            name="is_on_medication"
            label={t('medicalHistory.isOnMedication')}
            valuePropName="checked"
          >
            <Switch
              checkedChildren={t('medicalHistory.yes')}
              unCheckedChildren={t('medicalHistory.no')}
            />
          </Form.Item>
        </Form>
      </Modal>
    </div>
  );
};

export default MedicalHistory;
