/**
 * Main App Component
 * Generated by Zhuang
 */
import React, { useMemo, useState, useEffect } from 'react';
import { BrowserRouter as Router, Routes, Route, Navigate, useLocation } from 'react-router-dom';
import { ConfigProvider } from 'antd';
import zhCN from 'antd/locale/zh_CN';
import enUS from 'antd/locale/en_US';
import 'antd/dist/reset.css';
import './App.css';
import './i18n'; // Generated by Zhuang: initialize i18n
import { useTranslation } from 'react-i18next';
import dayjs from 'dayjs';
import utc from 'dayjs/plugin/utc';
import timezone from 'dayjs/plugin/timezone';
import 'dayjs/locale/zh-cn';
import 'dayjs/locale/en';
import Layout from './components/Layout';
import Login from './pages/Login';
import Register from './pages/Register';
import Dashboard from './pages/Dashboard';
import HealthRecords from './pages/HealthRecords';
import Profile from './pages/Profile';
import Members from './pages/Members';
import Settings from './pages/Settings';
import AdminUsers from './pages/AdminUsers';
import { MemberProvider } from './context/MemberContext';
import { isAuthenticated, getMustChangeFromToken } from './utils/auth';
import ChangePassword from './pages/ChangePassword';

dayjs.extend(utc);
dayjs.extend(timezone);

// Protected Route Component (redirects to change-password if required)
const ProtectedRoute = ({ children }) => {
  const location = useLocation();
  const authed = isAuthenticated();
  if (!authed) return <Navigate to="/login" />;
  const mustChange = getMustChangeFromToken();
  if (mustChange && location.pathname !== '/settings') {
    return <Navigate to="/settings?first=1" />;
  }
  return children;
};

// Public Route Component (redirect to dashboard if authenticated)
const PublicRoute = ({ children }) => {
  return !isAuthenticated() ? children : <Navigate to="/dashboard" />;
};

function App() {
  // Generated by Zhuang: react-i18next hook
  const { i18n, t } = useTranslation();
  const [lang, setLang] = useState(i18n.language || 'zh');

  // Sync from i18n on start and when language changes elsewhere
  useEffect(() => {
    const applyLocale = (lng) => {
      setLang(lng);
      dayjs.locale(lng && lng.startsWith('en') ? 'en' : 'zh-cn');
    };
    // initialize once
    applyLocale(i18n.language || 'zh');
    // subscribe and cleanup correctly
    const onChange = (lng) => applyLocale(lng);
    i18n.on('languageChanged', onChange);
    return () => {
      i18n.off('languageChanged', onChange);
    };
  }, [i18n]);

  // Map app language to AntD locale
  const antdLocale = useMemo(() => (lang === 'en' ? enUS : zhCN), [lang]);

  // Generated by Zhuang: keep document title and <html lang> in sync with current language
  useEffect(() => {
    try {
      const title = t('app.title');
      if (title) document.title = title;
      const html = document.documentElement;
      if (html) html.lang = (i18n.language || 'zh').startsWith('en') ? 'en' : 'zh-CN';
    } catch (_) {
      // no-op in non-browser environments
    }
  }, [i18n.language, t]);

  return (
    <ConfigProvider locale={antdLocale}>
      <Router>
        <MemberProvider>
        <div className="App">
          <Routes>
            {/* Public Routes */}
            <Route path="/login" element={
              <PublicRoute>
                <Login />
              </PublicRoute>
            } />
            <Route path="/register" element={
              <PublicRoute>
                <Register />
              </PublicRoute>
            } />
            
          {/* Protected Routes */}
          <Route path="/" element={
            <ProtectedRoute>
              <Layout />
            </ProtectedRoute>
          }>
              <Route index element={<Navigate to="/dashboard" />} />
              <Route path="dashboard" element={<Dashboard />} />
              <Route path="health-records" element={<HealthRecords />} />
              <Route path="members" element={<Members />} />
              <Route path="profile" element={<Profile />} />
              <Route path="settings" element={<Settings />} />
              <Route path="admin/users" element={<AdminUsers />} />
            </Route>
            {/* Change Password (standalone to avoid loading Layout) */}
            <Route path="/change-password" element={
              <ProtectedRoute>
                <ChangePassword />
              </ProtectedRoute>
            } />
            
            {/* Fallback */}
            <Route path="*" element={<Navigate to="/" />} />
          </Routes>
        </div>
        </MemberProvider>
      </Router>
    </ConfigProvider>
  );
}

export default App;
