@echo off
REM Generated by Zhuang
REM Script to extract kubectl configuration for GitHub Environment setup

echo 🔍 Extracting kubectl configuration for GitHub Environment setup
echo =================================================

REM Check if kubectl is available
kubectl version --client >nul 2>&1
if errorlevel 1 (
    echo ❌ kubectl is not installed or not in PATH
    exit /b 1
)

REM Get current context
for /f "delims=" %%i in ('kubectl config current-context 2^>nul') do set CURRENT_CONTEXT=%%i
if "%CURRENT_CONTEXT%"=="" (
    echo ❌ No current kubectl context found
    echo 💡 Please configure kubectl to connect to your cluster first
    exit /b 1
)

echo ✅ Current kubectl context: %CURRENT_CONTEXT%

REM Get cluster name
for /f "delims=" %%i in ('kubectl config view --minify -o jsonpath^="{.clusters[].name}" 2^>nul') do set CLUSTER_NAME=%%i
echo ✅ Cluster name: %CLUSTER_NAME%

REM Get server URL (for verification)
for /f "delims=" %%i in ('kubectl config view --minify -o jsonpath^="{.clusters[].cluster.server}" 2^>nul') do set SERVER_URL=%%i
echo ✅ Cluster server: %SERVER_URL%

echo.
echo 📋 GitHub Environment Secrets to configure:
echo =================================================

echo.
echo 🔑 KUBE_CONTEXT:
echo %CURRENT_CONTEXT%

echo.
echo 🔑 KUBE_CONFIG:
echo Copy the entire output below (including -----BEGIN/END----- lines):
echo ---

REM Get base64 encoded kubeconfig
kubectl config view --minify --raw 2>nul

echo ---

echo.
echo 💡 Instructions:
echo 1. Go to GitHub → Repository → Settings → Environments
echo 2. Select your environment (development/production)
echo 3. Add the following secrets:
echo    - KUBE_CONTEXT: %CURRENT_CONTEXT%
echo    - KUBE_CONFIG: [copy and base64 encode the YAML content above]
echo    - GHCR_USERNAME: your-github-username
echo    - GHCR_TOKEN: [your personal access token with packages:write scope]

echo.
echo 💡 To base64 encode the KUBE_CONFIG on Windows:
echo    1. Save the YAML output above to a file (e.g., kubeconfig.yaml)
echo    2. Use: certutil -encode kubeconfig.yaml kubeconfig-base64.txt
echo    3. Copy content from kubeconfig-base64.txt (remove header/footer lines)

echo.
echo ✅ Configuration extraction complete!
