#!/bin/bash
# Generated by Zhuang
# Script to extract kubectl configuration for GitHub Environment setup

set -e

echo "🔍 Extracting kubectl configuration for GitHub Environment setup"
echo "================================================="

# Check if kubectl is available
if ! command -v kubectl &> /dev/null; then
    echo "❌ kubectl is not installed or not in PATH"
    exit 1
fi

# Get current context
CURRENT_CONTEXT=$(kubectl config current-context 2>/dev/null || echo "")
if [ -z "$CURRENT_CONTEXT" ]; then
    echo "❌ No current kubectl context found"
    echo "💡 Please configure kubectl to connect to your cluster first"
    exit 1
fi

echo "✅ Current kubectl context: $CURRENT_CONTEXT"

# Get cluster name
CLUSTER_NAME=$(kubectl config view --minify -o jsonpath='{.clusters[].name}' 2>/dev/null || echo "")
echo "✅ Cluster name: $CLUSTER_NAME"

# Get server URL (for verification)
SERVER_URL=$(kubectl config view --minify -o jsonpath='{.clusters[].cluster.server}' 2>/dev/null || echo "")
echo "✅ Cluster server: $SERVER_URL"

echo ""
echo "📋 GitHub Environment Secrets to configure:"
echo "================================================="

echo ""
echo "🔑 KUBE_CONTEXT:"
echo "$CURRENT_CONTEXT"

echo ""
echo "🔑 KUBE_CONFIG:"
echo "Copy the entire output below (including -----BEGIN/END----- lines):"
echo "---"
kubectl config view --minify --raw 2>/dev/null | base64 -w 0 || kubectl config view --minify --raw 2>/dev/null | base64
echo ""
echo "---"

echo ""
echo "💡 Instructions:"
echo "1. Go to GitHub → Repository → Settings → Environments"
echo "2. Select your environment (development/production)"  
echo "3. Add the following secrets:"
echo "   - KUBE_CONTEXT: $CURRENT_CONTEXT"
echo "   - KUBE_CONFIG: [paste the base64 content above]"
echo "   - GHCR_USERNAME: your-github-username"
echo "   - GHCR_TOKEN: [your personal access token with packages:write scope]"

echo ""
echo "✅ Configuration extraction complete!"
