/**
 * Authentication utilities
 * Generated by Zhuang
 */

export const getToken = () => {
  return localStorage.getItem('access_token');
};

export const getRefreshToken = () => {
  return localStorage.getItem('refresh_token');
};

export const MEMBER_SELECTION_KEY = 'selected_member_id';
export const MEMBER_SELECTION_OWNER_KEY = 'selected_member_owner';

export const setTokens = (accessToken, refreshToken) => {
  localStorage.setItem('access_token', accessToken);
  localStorage.setItem('refresh_token', refreshToken);
};

export const clearTokens = () => {
  localStorage.removeItem('access_token');
  localStorage.removeItem('refresh_token');
  localStorage.removeItem(MEMBER_SELECTION_KEY);
  localStorage.removeItem(MEMBER_SELECTION_OWNER_KEY);
};

export const isAuthenticated = () => {
  const token = getToken();
  if (!token) return false;
  try {
    // JWT uses base64url encoding (no padding, -_/). Normalize then decode.
    const b64 = token.split('.')[1];
    if (!b64) return false;
    // base64url -> base64
    let base64 = b64.replace(/-/g, '+').replace(/_/g, '/');
    // add padding
    const pad = base64.length % 4;
    if (pad) base64 += '='.repeat(4 - pad);
    const json = atob(base64);
    const payload = JSON.parse(json);
    const currentTime = Date.now() / 1000;
    return payload.exp && payload.exp > currentTime;
  } catch (error) {
    return false;
  }
};

export const getUserIdFromToken = () => {
  const token = getToken();
  if (!token) return null;
  try {
    const b64 = token.split('.')[1];
    if (!b64) return null;
    let base64 = b64.replace(/-/g, '+').replace(/_/g, '/');
    const pad = base64.length % 4;
    if (pad) base64 += '='.repeat(4 - pad);
    const json = atob(base64);
    const payload = JSON.parse(json);
    return payload.sub || payload.identity || null;
  } catch (error) {
    return null;
  }
};

export const getMustChangeFromToken = () => {
  const token = getToken();
  if (!token) return false;
  try {
    const b64 = token.split('.')[1];
    if (!b64) return false;
    let base64 = b64.replace(/-/g, '+').replace(/_/g, '/');
    const pad = base64.length % 4;
    if (pad) base64 += '='.repeat(4 - pad);
    const json = atob(base64);
    const payload = JSON.parse(json);
    return !!payload.must_change_password;
  } catch (e) {
    return false;
  }
};

export const getRoleFromToken = () => {
  const token = getToken();
  if (!token) return null;
  try {
    const b64 = token.split('.')[1];
    if (!b64) return null;
    let base64 = b64.replace(/-/g, '+').replace(/_/g, '/');
    const pad = base64.length % 4;
    if (pad) base64 += '='.repeat(4 - pad);
    const json = atob(base64);
    const payload = JSON.parse(json);
    return payload.role || null;
  } catch (error) {
    return null;
  }
};
