// Generated by Copilot
import { parseServerTime } from './date';

export const SYSTOLIC_COLOR = '#1890ff';
export const DIASTOLIC_COLOR = '#52c41a';
export const HEART_RATE_COLOR = '#722ed1';
export const ABNORMAL_COLOR = '#ff4d4f';

const SYSTOLIC_THRESHOLD = 120;
const DIASTOLIC_THRESHOLD = 80;

const toNumOrNull = (value) => {
  const num = Number(value);
  return Number.isFinite(num) ? num : null;
};

const decorateAbnormalPoint = (value, isAbnormal) => {
  if (value === null) {
    return null;
  }
  if (!isAbnormal) {
    return value;
  }
  return {
    value,
    itemStyle: {
      color: ABNORMAL_COLOR,
      borderColor: ABNORMAL_COLOR,
    },
    symbolSize: 8,
  };
};

export const buildHealthChartSeries = (records = []) => {
  const chartPoints = records.map(record => {
    const systolic = toNumOrNull(record?.systolic);
    const diastolic = toNumOrNull(record?.diastolic);
    const heartRate = toNumOrNull(record?.heart_rate);
    const ts = parseServerTime(record?.timestamp);
    const label = ts.isValid() ? ts.format('MM-DD HH:mm') : (record?.timestamp || '');
    const isAbnormal = (systolic !== null && systolic >= SYSTOLIC_THRESHOLD) ||
      (diastolic !== null && diastolic >= DIASTOLIC_THRESHOLD);

    return {
      label,
      systolic,
      diastolic,
      heartRate,
      isAbnormal,
    };
  });

  const timeAxis = chartPoints.map(point => point.label);
  const systolicData = chartPoints.map(point => decorateAbnormalPoint(point.systolic, point.isAbnormal));
  const diastolicData = chartPoints.map(point => decorateAbnormalPoint(point.diastolic, point.isAbnormal));
  const heartRateData = chartPoints.map(point => (point.heartRate === null ? null : point.heartRate));

  const numericValues = chartPoints
    .flatMap(point => [point.systolic, point.diastolic, point.heartRate])
    .filter(value => typeof value === 'number');

  let yMin = 0;
  let yMax = 200;
  if (numericValues.length) {
    const minVal = Math.min(...numericValues);
    const maxVal = Math.max(...numericValues);
    const span = Math.max(10, maxVal - minVal);
    const padding = Math.max(5, Math.round(span * 0.1));
    yMin = Math.max(0, minVal - padding);
    yMax = maxVal + padding;
  }

  return {
    timeAxis,
    systolicData,
    diastolicData,
    heartRateData,
    yMin,
    yMax,
  };
};
