/**
 * Tag i18n helpers
 * Generated by Zhuang
 * Generated by Copilot
 */

// Canonical mapping: id -> Chinese value (stored in DB)
export const COMMON_TAG_DEFS = [
  { id: 'morning', value: '晨起' },
  { id: 'before_bed', value: '睡前' },
  { id: 'pre_exercise', value: '运动前' },
  { id: 'post_exercise', value: '运动后' },
  { id: 'before_meal', value: '餐前' },
  { id: 'after_meal', value: '餐后' },
  { id: 'before_med', value: '服药前' },
  { id: 'after_med', value: '服药后' },
  { id: 'at_work', value: '工作时' },
  { id: 'at_rest', value: '休息时' },
  { id: 'under_stress', value: '紧张时' },
  { id: 'relaxed', value: '放松时' },
  { id: 'headache', value: '头痛' },
  { id: 'dizziness', value: '头晕' },
  { id: 'chest_tightness', value: '胸闷' },
  { id: 'palpitations', value: '心悸' },
  { id: 'fatigue', value: '疲劳' },
];

/**
 * Convert a stored tag value (Chinese) to a localized label using i18n.
 * Falls back to original value if unknown.
 */
export function tagValueToLabel(value, t) {
  const def = COMMON_TAG_DEFS.find(d => d.value === value);
  if (!def) return value;
  return t(`tags.${def.id}`);
}

/** Map an array of tag values to localized labels. */
export function mapTagsToLabels(values, t) {
  return (values || []).map(v => tagValueToLabel(v, t));
}
