/**
 * Threshold status calculator - computes health status dynamically
 * Generated by Copilot
 */

/**
 * Compute threshold status for a health record
 * @param {number} systolic - Systolic blood pressure
 * @param {number} diastolic - Diastolic blood pressure
 * @param {number|null} heartRate - Heart rate (optional)
 * @param {object} config - Active threshold configuration
 * @returns {string} Status: 'healthy', 'borderline', or 'out_of_range'
 */
export const computeThresholdStatus = (systolic, diastolic, heartRate, config) => {
  if (!config || !config.payload) {
    return null; // No active configuration
  }

  const payload = config.payload;
  
  // Extract ranges with defaults
  const sHealthy = payload.systolic_healthy || [90, 120];
  const sBorderline = payload.systolic_borderline || [120, 140];
  const dHealthy = payload.diastolic_healthy || [60, 80];
  const dBorderline = payload.diastolic_borderline || [80, 90];

  // Determine systolic status
  let sStatus = 'out_of_range';
  if (systolic >= sHealthy[0] && systolic <= sHealthy[1]) {
    sStatus = 'healthy';
  } else if (systolic >= sBorderline[0] && systolic <= sBorderline[1]) {
    sStatus = 'borderline';
  }

  // Determine diastolic status
  let dStatus = 'out_of_range';
  if (diastolic >= dHealthy[0] && diastolic <= dHealthy[1]) {
    dStatus = 'healthy';
  } else if (diastolic >= dBorderline[0] && diastolic <= dBorderline[1]) {
    dStatus = 'borderline';
  }

  // Combine: worst status wins
  if (sStatus === 'out_of_range' || dStatus === 'out_of_range') {
    return 'out_of_range';
  }
  if (sStatus === 'borderline' || dStatus === 'borderline') {
    return 'borderline';
  }
  return 'healthy';
};

/**
 * Get display color for status
 */
export const getStatusColor = (status) => {
  switch (status) {
    case 'healthy':
      return 'green';
    case 'borderline':
      return 'orange';
    case 'out_of_range':
      return 'red';
    default:
      return 'default';
  }
};

/**
 * Get display text for status
 */
export const getStatusText = (status, t) => {
  switch (status) {
    case 'healthy':
      return t('threshold.status.healthy');
    case 'borderline':
      return t('threshold.status.borderline');
    case 'out_of_range':
      return t('threshold.status.outOfRange');
    default:
      return '-';
  }
};
