"""
Application configuration. Generated by Zhuang
"""
import os
from datetime import timedelta
from dotenv import load_dotenv  # Generated by Zhuang

# Generated by Zhuang: load environment variables from a .env file at project root
load_dotenv()


class Config:
    # Generated by Zhuang: default to SQLite file under instance/ for predictable location
    SQLALCHEMY_DATABASE_URI = os.getenv("DATABASE_URL", "sqlite:///instance/health_platform.db")
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    # Generated by Zhuang: engine options for better reliability across MySQL/others
    SQLALCHEMY_ENGINE_OPTIONS = {
        "pool_pre_ping": True,
    "pool_recycle": int(os.getenv("SQLALCHEMY_POOL_RECYCLE", "280")),
    }
    JWT_SECRET_KEY = os.getenv("JWT_SECRET", "dev-secret-change-me")
    JWT_ACCESS_TOKEN_EXPIRES = timedelta(minutes=int(os.getenv("JWT_ACCESS_MINUTES", "30")))
    JWT_REFRESH_TOKEN_EXPIRES = timedelta(days=int(os.getenv("JWT_REFRESH_DAYS", "7")))
    # Generated by Zhuang: include both localhost and 127.0.0.1 by default for dev
    CORS_ORIGINS = os.getenv(
        "CORS_ORIGINS",
        "http://localhost:3000,http://127.0.0.1:3000"
    ).split(",")
    RATELIMIT_DEFAULT = os.getenv("RATELIMIT_DEFAULT", "60 per minute")
    RATELIMIT_AUTH = os.getenv("RATELIMIT_AUTH", "5 per minute")
    # WeChat mini-app configuration. Generated by Copilot
    WECHAT_APP_ID = os.getenv("WECHAT_APP_ID")
    WECHAT_APP_SECRET = os.getenv("WECHAT_APP_SECRET")
