"""
Security helpers. Generated by Zhuang
"""
from datetime import timedelta
from typing import Union, Optional, Dict
from flask_jwt_extended import create_access_token, create_refresh_token
from werkzeug.security import generate_password_hash, check_password_hash


def hash_password(password: str) -> str:
    return generate_password_hash(password)


def verify_password(password: str, password_hash: str) -> bool:
    return check_password_hash(password_hash, password)


def make_tokens(identity: Union[str, int], token_version: int, additional_claims: Optional[Dict] = None,
                access_expires: Optional[timedelta] = None, refresh_expires: Optional[timedelta] = None) -> Dict:
    claims = {"token_version": token_version}
    if additional_claims:
        claims.update(additional_claims)
    at = create_access_token(identity=identity, additional_claims=claims, expires_delta=access_expires)
    rt = create_refresh_token(identity=identity, additional_claims=claims, expires_delta=refresh_expires)
    return {"access_token": at, "refresh_token": rt}
