/**
 * i18n initialization for the Health Platform frontend
 * Generated by Zhuang
 * Generated by Copilot
 */
import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

// Import translation resources
import zh from './locales/zh/translation.json';
import en from './locales/en/translation.json';

// Determine initial language from localStorage or browser
const LS_KEY = 'app_language';
// Default to Simplified Chinese unless user has explicitly saved a preference
const savedLang = localStorage.getItem(LS_KEY);
const defaultLang = savedLang || 'zh';

i18n
  .use(initReactI18next)
  .init({
    resources: {
      zh: { translation: zh },
      en: { translation: en },
    },
    lng: defaultLang,
    fallbackLng: 'zh',
    interpolation: { escapeValue: false },
    returnEmptyString: false,
  });

export default i18n;
